CREATE TABLE [stg_navdb].[CompanyInformation] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [Primary Key]                  NVARCHAR (10)      NOT NULL,
    [Name]                         NVARCHAR (50)      NOT NULL,
    [Name 2]                       NVARCHAR (50)      NOT NULL,
    [Address]                      NVARCHAR (50)      NOT NULL,
    [Address 2]                    NVARCHAR (50)      NOT NULL,
    [City]                         NVARCHAR (30)      NOT NULL,
    [Phone No_]                    NVARCHAR (20)      NOT NULL,
    [Phone No_ 2]                  NVARCHAR (20)      NOT NULL,
    [Telex No_]                    NVARCHAR (20)      NOT NULL,
    [Fax No_]                      NVARCHAR (20)      NOT NULL,
    [Giro No_]                     NVARCHAR (20)      NOT NULL,
    [Bank Name]                    NVARCHAR (50)      NOT NULL,
    [Bank Branch No_]              NVARCHAR (20)      NOT NULL,
    [Bank Account No_]             NVARCHAR (30)      NOT NULL,
    [Payment Routing No_]          NVARCHAR (20)      NOT NULL,
    [Customs Permit No_]           NVARCHAR (10)      NOT NULL,
    [Customs Permit Date]          DATETIME           NOT NULL,
    [VAT Registration No_]         NVARCHAR (20)      NOT NULL,
    [Registration No_]             NVARCHAR (20)      NOT NULL,
    [Telex Answer Back]            NVARCHAR (20)      NOT NULL,
    [Ship-to Name]                 NVARCHAR (50)      NOT NULL,
    [Ship-to Name 2]               NVARCHAR (50)      NOT NULL,
    [Ship-to Address]              NVARCHAR (50)      NOT NULL,
    [Ship-to Address 2]            NVARCHAR (50)      NOT NULL,
    [Ship-to City]                 NVARCHAR (30)      NOT NULL,
    [Ship-to Contact]              NVARCHAR (50)      NOT NULL,
    [Location Code]                NVARCHAR (10)      NOT NULL,
    [Picture]                      VARBINARY (MAX)    NULL,
    [Post Code]                    NVARCHAR (20)      NOT NULL,
    [County]                       NVARCHAR (30)      NOT NULL,
    [Ship-to Post Code]            NVARCHAR (20)      NOT NULL,
    [Ship-to County]               NVARCHAR (30)      NOT NULL,
    [E-Mail]                       NVARCHAR (80)      NOT NULL,
    [Home Page]                    NVARCHAR (80)      NOT NULL,
    [Country_Region Code]          NVARCHAR (10)      NOT NULL,
    [Ship-to Country_Region Code]  NVARCHAR (10)      NOT NULL,
    [IBAN]                         NVARCHAR (50)      NOT NULL,
    [SWIFT Code]                   NVARCHAR (20)      NOT NULL,
    [Industrial Classification]    NVARCHAR (30)      NOT NULL,
    [IC Partner Code]              NVARCHAR (20)      NOT NULL,
    [IC Inbox Type]                INT                NOT NULL,
    [IC Inbox Details]             NVARCHAR (250)     NOT NULL,
    [Responsibility Center]        NVARCHAR (10)      NOT NULL,
    [Check-Avail_ Period Calc_]    NVARCHAR (32)      NOT NULL,
    [Check-Avail_ Time Bucket]     INT                NOT NULL,
    [Base Calendar Code]           NVARCHAR (10)      NOT NULL,
    [Cal_ Convergence Time Frame]  NVARCHAR (32)      NOT NULL,
    [IBAN (PM)]                    NVARCHAR (50)      NOT NULL,
    [Customer Service Phone No_]   NVARCHAR (20)      NOT NULL,
    [Customer Service Fax No_]     NVARCHAR (20)      NOT NULL,
    [VAT No_]                      NVARCHAR (20)      NOT NULL,
    [Lessor Portal Source Version] NVARCHAR (16)      NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_CompanyInformation_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_CompanyInformation_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_CompanyInformation_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_navdb_CompanyInformation] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Primary Key] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

