CREATE TABLE [stg_navdb].[Customer] (
    [CompanyID]                      TINYINT            NOT NULL,
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [No_]                            VARCHAR (20)       NOT NULL,
    [Name]                           VARCHAR (50)       NOT NULL,
    [Search Name]                    VARCHAR (50)       NOT NULL,
    [Name 2]                         VARCHAR (50)       NOT NULL,
    [Address]                        VARCHAR (50)       NOT NULL,
    [Address 2]                      VARCHAR (50)       NOT NULL,
    [City]                           VARCHAR (30)       NOT NULL,
    [Contact]                        VARCHAR (50)       NOT NULL,
    [Phone No_]                      VARCHAR (30)       NOT NULL,
    [Telex No_]                      VARCHAR (20)       NOT NULL,
    [Our Account No_]                VARCHAR (20)       NOT NULL,
    [Territory Code]                 VARCHAR (10)       NOT NULL,
    [Global Dimension 1 Code]        VARCHAR (20)       NOT NULL,
    [Global Dimension 2 Code]        VARCHAR (20)       NOT NULL,
    [Chain Name]                     VARCHAR (10)       NOT NULL,
    [Budgeted Amount]                DECIMAL (38, 20)   NOT NULL,
    [Credit Limit (LCY)]             DECIMAL (38, 20)   NOT NULL,
    [Customer Posting Group]         VARCHAR (10)       NOT NULL,
    [Currency Code]                  VARCHAR (10)       NOT NULL,
    [Customer Price Group]           VARCHAR (10)       NOT NULL,
    [Language Code]                  VARCHAR (10)       NOT NULL,
    [Statistics Group]               INT                NOT NULL,
    [Payment Terms Code]             VARCHAR (10)       NOT NULL,
    [Fin_ Charge Terms Code]         VARCHAR (10)       NOT NULL,
    [Salesperson Code]               VARCHAR (10)       NOT NULL,
    [Shipment Method Code]           VARCHAR (10)       NOT NULL,
    [Shipping Agent Code]            VARCHAR (10)       NOT NULL,
    [Place of Export]                VARCHAR (20)       NOT NULL,
    [Invoice Disc_ Code]             VARCHAR (20)       NOT NULL,
    [Customer Disc_ Group]           VARCHAR (10)       NOT NULL,
    [Country_Region Code]            VARCHAR (10)       NOT NULL,
    [Collection Method]              VARCHAR (20)       NOT NULL,
    [Amount]                         DECIMAL (38, 20)   NOT NULL,
    [Blocked]                        INT                NOT NULL,
    [Invoice Copies]                 INT                NOT NULL,
    [Last Statement No_]             INT                NOT NULL,
    [Print Statements]               TINYINT            NOT NULL,
    [Bill-to Customer No_]           VARCHAR (20)       NOT NULL,
    [Priority]                       INT                NOT NULL,
    [Payment Method Code]            VARCHAR (10)       NOT NULL,
    [Last Date Modified]             DATETIME           NOT NULL,
    [Application Method]             INT                NOT NULL,
    [Prices Including VAT]           TINYINT            NOT NULL,
    [Location Code]                  VARCHAR (10)       NOT NULL,
    [Fax No_]                        VARCHAR (30)       NOT NULL,
    [Telex Answer Back]              VARCHAR (20)       NOT NULL,
    [VAT Registration No_]           VARCHAR (20)       NOT NULL,
    [Combine Shipments]              TINYINT            NOT NULL,
    [Gen_ Bus_ Posting Group]        VARCHAR (10)       NOT NULL,
    [Picture]                        VARBINARY (MAX)    NULL,
    [Post Code]                      VARCHAR (20)       NOT NULL,
    [County]                         VARCHAR (30)       NOT NULL,
    [E-Mail]                         VARCHAR (80)       NOT NULL,
    [Home Page]                      VARCHAR (80)       NOT NULL,
    [Reminder Terms Code]            VARCHAR (10)       NOT NULL,
    [No_ Series]                     VARCHAR (10)       NOT NULL,
    [Tax Area Code]                  VARCHAR (20)       NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]         VARCHAR (10)       NOT NULL,
    [Reserve]                        INT                NOT NULL,
    [Block Payment Tolerance]        TINYINT            NOT NULL,
    [IC Partner Code]                VARCHAR (20)       NOT NULL,
    [Prepayment %]                   DECIMAL (38, 20)   NOT NULL,
    [Primary Contact No_]            VARCHAR (20)       NOT NULL,
    [Responsibility Center]          VARCHAR (10)       NOT NULL,
    [Shipping Advice]                INT                NOT NULL,
    [Shipping Time]                  VARCHAR (32)       NOT NULL,
    [Shipping Agent Service Code]    VARCHAR (10)       NOT NULL,
    [Service Zone Code]              VARCHAR (10)       NOT NULL,
    [Allow Line Disc_]               TINYINT            NOT NULL,
    [Base Calendar Code]             VARCHAR (10)       NOT NULL,
    [Copy Sell-to Addr_ to Qte From] INT                NOT NULL,
    [EAN No_]                        VARCHAR (13)       NOT NULL,
    [Account Code]                   VARCHAR (30)       NOT NULL,
    [ClaimsPassword]                 VARCHAR (10)       NOT NULL,
    [Credit Insurance Amount]        DECIMAL (38, 20)   NOT NULL,
    [Delete back order]              TINYINT            NOT NULL,
    [Invoice copy to agent]          TINYINT            NOT NULL,
    [No_ of inv_ copy to agent]      INT                NOT NULL,
    [Agent e-mail]                   VARCHAR (50)       NOT NULL,
    [Dimension & Salesinfo from]     INT                NOT NULL,
    [Bank Account]                   VARCHAR (20)       NOT NULL,
    [Chain Code]                     VARCHAR (20)       NOT NULL,
    [Chain Group Code]               VARCHAR (20)       NOT NULL,
    [Invoice-Show Country of Origin] TINYINT            NOT NULL,
    [Category]                       VARCHAR (10)       NOT NULL,
    [Batch Posting]                  TINYINT            NOT NULL,
    [Calculate freight]              TINYINT            NOT NULL,
    [Ship-to Code]                   VARCHAR (10)       NOT NULL,
    [Transfer-to Code]               VARCHAR (10)       NOT NULL,
    [Webshop link]                   VARCHAR (20)       NOT NULL,
    [ShowBarcodeRef on Invoice]      TINYINT            NOT NULL,
    [Tote-pick]                      TINYINT            NOT NULL,
    [Allow Qty on Claims]            TINYINT            NOT NULL,
    [Sales Order Priority]           INT                NOT NULL,
    [Oprydning spærret]              TINYINT            NOT NULL,
    [PipelineName]                   NVARCHAR (128)     NULL,
    [PipelineRunId]                  NVARCHAR (36)      NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) NULL,
    CONSTRAINT [PK_stg_navdb_Customer] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_navdb_Customer_timestamp]
    ON [stg_navdb].[Customer]([CompanyID] ASC, [timestamp] ASC);


GO

