CREATE TABLE [stg_navdb].[FALedgerEntry] (
    [CompanyID]                      TINYINT            NOT NULL,
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Entry No_]                      INT                NOT NULL,
    [G_L Entry No_]                  INT                NOT NULL,
    [FA No_]                         VARCHAR (20)       NOT NULL,
    [FA Posting Date]                DATETIME           NOT NULL,
    [Posting Date]                   DATETIME           NOT NULL,
    [Document Type]                  INT                NOT NULL,
    [Document Date]                  DATETIME           NOT NULL,
    [Document No_]                   VARCHAR (20)       NOT NULL,
    [External Document No_]          VARCHAR (20)       NOT NULL,
    [Description]                    VARCHAR (50)       NOT NULL,
    [Depreciation Book Code]         VARCHAR (10)       NOT NULL,
    [FA Posting Category]            INT                NOT NULL,
    [FA Posting Type]                INT                NOT NULL,
    [Amount]                         DECIMAL (38, 20)   NOT NULL,
    [Debit Amount]                   DECIMAL (38, 20)   NOT NULL,
    [Credit Amount]                  DECIMAL (38, 20)   NOT NULL,
    [Reclassification Entry]         TINYINT            NOT NULL,
    [Part of Book Value]             TINYINT            NOT NULL,
    [Part of Depreciable Basis]      TINYINT            NOT NULL,
    [Disposal Calculation Method]    INT                NOT NULL,
    [Disposal Entry No_]             INT                NOT NULL,
    [No_ of Depreciation Days]       INT                NOT NULL,
    [Quantity]                       DECIMAL (38, 20)   NOT NULL,
    [FA No__Budgeted FA No_]         VARCHAR (20)       NOT NULL,
    [FA Subclass Code]               VARCHAR (10)       NOT NULL,
    [FA Location Code]               VARCHAR (10)       NOT NULL,
    [FA Posting Group]               VARCHAR (10)       NOT NULL,
    [Global Dimension 1 Code]        VARCHAR (20)       NOT NULL,
    [Global Dimension 2 Code]        VARCHAR (20)       NOT NULL,
    [Location Code]                  VARCHAR (10)       NOT NULL,
    [User ID]                        VARCHAR (20)       NOT NULL,
    [Depreciation Method]            INT                NOT NULL,
    [Depreciation Starting Date]     DATETIME           NOT NULL,
    [Straight-Line %]                DECIMAL (38, 20)   NOT NULL,
    [No_ of Depreciation Years]      DECIMAL (38, 20)   NOT NULL,
    [Fixed Depr_ Amount]             DECIMAL (38, 20)   NOT NULL,
    [Declining-Balance %]            DECIMAL (38, 20)   NOT NULL,
    [Depreciation Table Code]        VARCHAR (10)       NOT NULL,
    [Journal Batch Name]             VARCHAR (10)       NOT NULL,
    [Source Code]                    VARCHAR (10)       NOT NULL,
    [Reason Code]                    VARCHAR (10)       NOT NULL,
    [Transaction No_]                INT                NOT NULL,
    [Bal_ Account Type]              INT                NOT NULL,
    [Bal_ Account No_]               VARCHAR (20)       NOT NULL,
    [VAT Amount]                     DECIMAL (38, 20)   NOT NULL,
    [Gen_ Posting Type]              INT                NOT NULL,
    [Gen_ Bus_ Posting Group]        VARCHAR (10)       NOT NULL,
    [Gen_ Prod_ Posting Group]       VARCHAR (10)       NOT NULL,
    [FA Class Code]                  VARCHAR (10)       NOT NULL,
    [FA Exchange Rate]               DECIMAL (38, 20)   NOT NULL,
    [Amount (LCY)]                   DECIMAL (38, 20)   NOT NULL,
    [Result on Disposal]             INT                NOT NULL,
    [Correction]                     TINYINT            NOT NULL,
    [Index Entry]                    TINYINT            NOT NULL,
    [Canceled from FA No_]           VARCHAR (20)       NOT NULL,
    [Depreciation Ending Date]       DATETIME           NOT NULL,
    [Use FA Ledger Check]            TINYINT            NOT NULL,
    [Automatic Entry]                TINYINT            NOT NULL,
    [Depr_ Starting Date (Custom 1)] DATETIME           NOT NULL,
    [Depr_ Ending Date (Custom 1)]   DATETIME           NOT NULL,
    [Accum_ Depr_ % (Custom 1)]      DECIMAL (38, 20)   NOT NULL,
    [Depr_ % this year (Custom 1)]   DECIMAL (38, 20)   NOT NULL,
    [Property Class (Custom 1)]      INT                NOT NULL,
    [No_ Series]                     VARCHAR (10)       NOT NULL,
    [Tax Area Code]                  VARCHAR (20)       NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [Tax Group Code]                 VARCHAR (10)       NOT NULL,
    [Use Tax]                        TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]         VARCHAR (10)       NOT NULL,
    [VAT Prod_ Posting Group]        VARCHAR (10)       NOT NULL,
    [Reversed]                       TINYINT            NOT NULL,
    [Reversed by Entry No_]          INT                NOT NULL,
    [Reversed Entry No_]             INT                NOT NULL,
    [PipelineName]                   NVARCHAR (128)     NULL,
    [PipelineRunId]                  NVARCHAR (36)      NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) NULL,
    CONSTRAINT [PK_stg_navdb_FALedgerEntry] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Posting Date] ASC, [Entry No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_navdb_FALedgerEntry_timestamp]
    ON [stg_navdb].[FALedgerEntry]([CompanyID] ASC, [timestamp] ASC);


GO

