CREATE TABLE [stg_navdb].[GeneralLedgerSetup] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Primary Key]                    NVARCHAR (10)      NOT NULL,
    [Allow Posting From]             DATETIME           NOT NULL,
    [Allow Posting To]               DATETIME           NOT NULL,
    [Register Time]                  TINYINT            NOT NULL,
    [Pmt_ Disc_ Excl_ VAT]           TINYINT            NOT NULL,
    [Unrealized VAT]                 TINYINT            NOT NULL,
    [Adjust for Payment Disc_]       TINYINT            NOT NULL,
    [Mark Cr_ Memos as Corrections]  TINYINT            NOT NULL,
    [Local Address Format]           INT                NOT NULL,
    [Inv_ Rounding Precision (LCY)]  DECIMAL (38, 20)   NOT NULL,
    [Inv_ Rounding Type (LCY)]       INT                NOT NULL,
    [Local Cont_ Addr_ Format]       INT                NOT NULL,
    [Bank Account Nos_]              NVARCHAR (10)      NOT NULL,
    [Summarize G_L Entries]          TINYINT            NOT NULL,
    [Amount Decimal Places]          NVARCHAR (5)       NOT NULL,
    [Unit-Amount Decimal Places]     NVARCHAR (5)       NOT NULL,
    [Additional Reporting Currency]  NVARCHAR (10)      NOT NULL,
    [VAT Tolerance %]                DECIMAL (38, 20)   NOT NULL,
    [EMU Currency]                   TINYINT            NOT NULL,
    [LCY Code]                       NVARCHAR (10)      NOT NULL,
    [VAT Exchange Rate Adjustment]   INT                NOT NULL,
    [Amount Rounding Precision]      DECIMAL (38, 20)   NOT NULL,
    [Unit-Amount Rounding Precision] DECIMAL (38, 20)   NOT NULL,
    [Appln_ Rounding Precision]      DECIMAL (38, 20)   NOT NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)      NOT NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 3 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 4 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 5 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 6 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 7 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 8 Code]      NVARCHAR (20)      NOT NULL,
    [Max_ VAT Difference Allowed]    DECIMAL (38, 20)   NOT NULL,
    [VAT Rounding Type]              INT                NOT NULL,
    [Pmt_ Disc_ Tolerance Posting]   INT                NOT NULL,
    [Payment Discount Grace Period]  NVARCHAR (32)      NOT NULL,
    [Payment Tolerance %]            DECIMAL (38, 20)   NOT NULL,
    [Max_ Payment Tolerance Amount]  DECIMAL (38, 20)   NOT NULL,
    [Adapt Main Menu to Permissions] TINYINT            NOT NULL,
    [Allow G_L Acc_ Deletion Before] DATETIME           NOT NULL,
    [Check G_L Account Usage]        TINYINT            NOT NULL,
    [Payment Tolerance Posting]      INT                NOT NULL,
    [Pmt_ Disc_ Tolerance Warning]   TINYINT            NOT NULL,
    [Payment Tolerance Warning]      TINYINT            NOT NULL,
    [Last IC Transaction No_]        INT                NOT NULL,
    [Bill-to_Sell-to VAT Calc_]      INT                NOT NULL,
    [Print VAT specification in LCY] TINYINT            NOT NULL,
    [Prepayment Unrealized VAT]      TINYINT            NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_GeneralLedgerSetup_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_GeneralLedgerSetup_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_GeneralLedgerSetup_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_navdb_GeneralLedgerSetup] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Primary Key] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

