CREATE TABLE [stg_navdb].[InterimTable_368479df-0e33-464e-aaa0-77e968c3457b] (
    [timestamp]                      VARBINARY (8)      NULL,
    [Document No_]                   VARCHAR (20)       NULL,
    [Line No_]                       INT                NULL,
    [Buy-from Vendor No_]            VARCHAR (20)       NULL,
    [Type]                           INT                NULL,
    [No_]                            VARCHAR (20)       NULL,
    [Location Code]                  VARCHAR (10)       NULL,
    [Posting Group]                  VARCHAR (10)       NULL,
    [Expected Receipt Date]          DATETIME           NULL,
    [Description]                    VARCHAR (50)       NULL,
    [Description 2]                  VARCHAR (50)       NULL,
    [Unit of Measure]                VARCHAR (10)       NULL,
    [Quantity]                       DECIMAL (38, 20)   NULL,
    [Direct Unit Cost]               DECIMAL (38, 20)   NULL,
    [Unit Cost (LCY)]                DECIMAL (38, 20)   NULL,
    [VAT %]                          DECIMAL (38, 20)   NULL,
    [Line Discount %]                DECIMAL (38, 20)   NULL,
    [Line Discount Amount]           DECIMAL (38, 20)   NULL,
    [Amount]                         DECIMAL (38, 20)   NULL,
    [Amount Including VAT]           DECIMAL (38, 20)   NULL,
    [Unit Price (LCY)]               DECIMAL (38, 20)   NULL,
    [Allow Invoice Disc_]            TINYINT            NULL,
    [Gross Weight]                   DECIMAL (38, 20)   NULL,
    [Net Weight]                     DECIMAL (38, 20)   NULL,
    [Units per Parcel]               DECIMAL (38, 20)   NULL,
    [Unit Volume]                    DECIMAL (38, 20)   NULL,
    [Appl_-to Item Entry]            INT                NULL,
    [Shortcut Dimension 1 Code]      VARCHAR (20)       NULL,
    [Shortcut Dimension 2 Code]      VARCHAR (20)       NULL,
    [Job No_]                        VARCHAR (20)       NULL,
    [Indirect Cost %]                DECIMAL (38, 20)   NULL,
    [Pay-to Vendor No_]              VARCHAR (20)       NULL,
    [Inv_ Discount Amount]           DECIMAL (38, 20)   NULL,
    [Vendor Item No_]                VARCHAR (20)       NULL,
    [Gen_ Bus_ Posting Group]        VARCHAR (10)       NULL,
    [Gen_ Prod_ Posting Group]       VARCHAR (10)       NULL,
    [VAT Calculation Type]           INT                NULL,
    [Transaction Type]               VARCHAR (10)       NULL,
    [Transport Method]               VARCHAR (10)       NULL,
    [Attached to Line No_]           INT                NULL,
    [Entry Point]                    VARCHAR (10)       NULL,
    [Area]                           VARCHAR (10)       NULL,
    [Transaction Specification]      VARCHAR (10)       NULL,
    [Tax Area Code]                  VARCHAR (20)       NULL,
    [Tax Liable]                     TINYINT            NULL,
    [Tax Group Code]                 VARCHAR (10)       NULL,
    [Use Tax]                        TINYINT            NULL,
    [VAT Bus_ Posting Group]         VARCHAR (10)       NULL,
    [VAT Prod_ Posting Group]        VARCHAR (10)       NULL,
    [Blanket Order No_]              VARCHAR (20)       NULL,
    [Blanket Order Line No_]         INT                NULL,
    [VAT Base Amount]                DECIMAL (38, 20)   NULL,
    [Unit Cost]                      DECIMAL (38, 20)   NULL,
    [System-Created Entry]           TINYINT            NULL,
    [Line Amount]                    DECIMAL (38, 20)   NULL,
    [VAT Difference]                 DECIMAL (38, 20)   NULL,
    [VAT Identifier]                 VARCHAR (10)       NULL,
    [IC Partner Ref_ Type]           INT                NULL,
    [IC Partner Reference]           VARCHAR (20)       NULL,
    [Prepayment Line]                TINYINT            NULL,
    [IC Partner Code]                VARCHAR (20)       NULL,
    [Posting Date]                   DATETIME           NULL,
    [Job Task No_]                   VARCHAR (20)       NULL,
    [Job Line Type]                  INT                NULL,
    [Job Unit Price]                 DECIMAL (38, 20)   NULL,
    [Job Total Price]                DECIMAL (38, 20)   NULL,
    [Job Line Amount]                DECIMAL (38, 20)   NULL,
    [Job Line Discount Amount]       DECIMAL (38, 20)   NULL,
    [Job Line Discount %]            DECIMAL (38, 20)   NULL,
    [Job Unit Price (LCY)]           DECIMAL (38, 20)   NULL,
    [Job Total Price (LCY)]          DECIMAL (38, 20)   NULL,
    [Job Line Amount (LCY)]          DECIMAL (38, 20)   NULL,
    [Job Line Disc_ Amount (LCY)]    DECIMAL (38, 20)   NULL,
    [Job Currency Factor]            DECIMAL (38, 20)   NULL,
    [Job Currency Code]              VARCHAR (20)       NULL,
    [Prod_ Order No_]                VARCHAR (20)       NULL,
    [Variant Code]                   VARCHAR (10)       NULL,
    [Bin Code]                       VARCHAR (20)       NULL,
    [Qty_ per Unit of Measure]       DECIMAL (38, 20)   NULL,
    [Unit of Measure Code]           VARCHAR (10)       NULL,
    [Quantity (Base)]                DECIMAL (38, 20)   NULL,
    [FA Posting Date]                DATETIME           NULL,
    [FA Posting Type]                INT                NULL,
    [Depreciation Book Code]         VARCHAR (10)       NULL,
    [Salvage Value]                  DECIMAL (38, 20)   NULL,
    [Depr_ until FA Posting Date]    TINYINT            NULL,
    [Depr_ Acquisition Cost]         TINYINT            NULL,
    [Maintenance Code]               VARCHAR (10)       NULL,
    [Insurance No_]                  VARCHAR (20)       NULL,
    [Budgeted FA No_]                VARCHAR (20)       NULL,
    [Duplicate in Depreciation Book] VARCHAR (10)       NULL,
    [Use Duplication List]           TINYINT            NULL,
    [Responsibility Center]          VARCHAR (10)       NULL,
    [Cross-Reference No_]            VARCHAR (20)       NULL,
    [Unit of Measure (Cross Ref_)]   VARCHAR (10)       NULL,
    [Cross-Reference Type]           INT                NULL,
    [Cross-Reference Type No_]       VARCHAR (30)       NULL,
    [Item Category Code]             VARCHAR (10)       NULL,
    [Nonstock]                       TINYINT            NULL,
    [Purchasing Code]                VARCHAR (10)       NULL,
    [Product Group Code]             VARCHAR (10)       NULL,
    [Return Reason Code]             VARCHAR (10)       NULL,
    [WHT Business Posting Group]     VARCHAR (10)       NULL,
    [WHT Product Posting Group]      VARCHAR (10)       NULL,
    [WHT Absorb Base]                DECIMAL (38, 20)   NULL,
    [VAT Base (ACY)]                 DECIMAL (38, 20)   NULL,
    [VAT Amount (ACY)]               DECIMAL (38, 20)   NULL,
    [Amount Including VAT (ACY)]     DECIMAL (38, 20)   NULL,
    [Amount (ACY)]                   DECIMAL (38, 20)   NULL,
    [VAT Difference (ACY)]           DECIMAL (38, 20)   NULL,
    [Prepayment %]                   DECIMAL (38, 20)   NULL,
    [Routing No_]                    VARCHAR (20)       NULL,
    [Operation No_]                  VARCHAR (10)       NULL,
    [Work Center No_]                VARCHAR (20)       NULL,
    [Prod_ Order Line No_]           INT                NULL,
    [Overhead Rate]                  DECIMAL (38, 20)   NULL,
    [Routing Reference No_]          INT                NULL,
    [PipelineName]                   NVARCHAR (200)     NULL,
    [PipelineRunId]                  NVARCHAR (36)      NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) NULL,
    [CompanyID]                      INT                NULL,
    [BatchIdentifier]                BIGINT             IDENTITY (1, 1) NOT NULL
);


GO

