CREATE TABLE [stg_navdb].[Item] (
    [CompanyID]                      TINYINT            NOT NULL,
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [No_]                            VARCHAR (20)       NOT NULL,
    [No_ 2]                          VARCHAR (20)       NOT NULL,
    [Description]                    VARCHAR (30)       NOT NULL,
    [Search Description]             VARCHAR (30)       NOT NULL,
    [Description 2]                  VARCHAR (30)       NOT NULL,
    [Base Unit of Measure]           VARCHAR (10)       NOT NULL,
    [Price Unit Conversion]          INT                NOT NULL,
    [Inventory Posting Group]        VARCHAR (10)       NOT NULL,
    [Shelf No_]                      VARCHAR (10)       NOT NULL,
    [Item Disc_ Group]               VARCHAR (10)       NOT NULL,
    [Allow Invoice Disc_]            TINYINT            NOT NULL,
    [Statistics Group]               INT                NOT NULL,
    [Commission Group]               INT                NOT NULL,
    [Unit Price]                     DECIMAL (38, 20)   NOT NULL,
    [Price_Profit Calculation]       INT                NOT NULL,
    [Profit %]                       DECIMAL (38, 20)   NOT NULL,
    [Costing Method]                 INT                NOT NULL,
    [Unit Cost]                      DECIMAL (38, 20)   NOT NULL,
    [Standard Cost]                  DECIMAL (38, 20)   NOT NULL,
    [Last Direct Cost]               DECIMAL (38, 20)   NOT NULL,
    [Indirect Cost %]                DECIMAL (38, 20)   NOT NULL,
    [Cost is Adjusted]               TINYINT            NOT NULL,
    [Allow Online Adjustment]        TINYINT            NOT NULL,
    [Vendor No_]                     VARCHAR (20)       NOT NULL,
    [Vendor Item No_]                VARCHAR (20)       NOT NULL,
    [Lead Time Calculation]          VARCHAR (32)       NOT NULL,
    [Reorder Point]                  DECIMAL (38, 20)   NOT NULL,
    [Maximum Inventory]              DECIMAL (38, 20)   NOT NULL,
    [Reorder Quantity]               DECIMAL (38, 20)   NOT NULL,
    [Alternative Item No_]           VARCHAR (20)       NOT NULL,
    [Unit List Price]                DECIMAL (38, 20)   NOT NULL,
    [Duty Due %]                     DECIMAL (38, 20)   NOT NULL,
    [Duty Code]                      VARCHAR (10)       NOT NULL,
    [Gross Weight]                   DECIMAL (38, 20)   NOT NULL,
    [Net Weight]                     DECIMAL (38, 20)   NOT NULL,
    [Units per Parcel]               DECIMAL (38, 20)   NOT NULL,
    [Unit Volume]                    DECIMAL (38, 20)   NOT NULL,
    [Durability]                     VARCHAR (10)       NOT NULL,
    [Freight Type]                   VARCHAR (10)       NOT NULL,
    [Tariff No_]                     VARCHAR (10)       NOT NULL,
    [Duty Unit Conversion]           DECIMAL (38, 20)   NOT NULL,
    [Country_Region Purchased Code]  VARCHAR (10)       NOT NULL,
    [Budget Quantity]                DECIMAL (38, 20)   NOT NULL,
    [Budgeted Amount]                DECIMAL (38, 20)   NOT NULL,
    [Budget Profit]                  DECIMAL (38, 20)   NOT NULL,
    [Blocked]                        TINYINT            NOT NULL,
    [Last Date Modified]             DATETIME           NOT NULL,
    [Price Includes VAT]             TINYINT            NOT NULL,
    [VAT Bus_ Posting Gr_ (Price)]   VARCHAR (10)       NOT NULL,
    [Gen_ Prod_ Posting Group]       VARCHAR (10)       NOT NULL,
    [Picture]                        VARBINARY (MAX)    NULL,
    [Country_Region of Origin Code]  VARCHAR (10)       NOT NULL,
    [Automatic Ext_ Texts]           TINYINT            NOT NULL,
    [No_ Series]                     VARCHAR (10)       NOT NULL,
    [Tax Group Code]                 VARCHAR (10)       NOT NULL,
    [VAT Prod_ Posting Group]        VARCHAR (10)       NOT NULL,
    [Reserve]                        INT                NOT NULL,
    [Global Dimension 1 Code]        VARCHAR (20)       NOT NULL,
    [Global Dimension 2 Code]        VARCHAR (20)       NOT NULL,
    [Low-Level Code]                 INT                NOT NULL,
    [Lot Size]                       DECIMAL (38, 20)   NOT NULL,
    [Serial Nos_]                    VARCHAR (10)       NOT NULL,
    [Last Unit Cost Calc_ Date]      DATETIME           NOT NULL,
    [Rolled-up Material Cost]        DECIMAL (38, 20)   NOT NULL,
    [Rolled-up Capacity Cost]        DECIMAL (38, 20)   NOT NULL,
    [Scrap %]                        DECIMAL (38, 20)   NOT NULL,
    [Inventory Value Zero]           TINYINT            NOT NULL,
    [Discrete Order Quantity]        INT                NOT NULL,
    [Minimum Order Quantity]         DECIMAL (38, 20)   NOT NULL,
    [Maximum Order Quantity]         DECIMAL (38, 20)   NOT NULL,
    [Safety Stock Quantity]          DECIMAL (38, 20)   NOT NULL,
    [Order Multiple]                 DECIMAL (38, 20)   NOT NULL,
    [Safety Lead Time]               VARCHAR (32)       NOT NULL,
    [Flushing Method]                INT                NOT NULL,
    [Replenishment System]           INT                NOT NULL,
    [Rounding Precision]             DECIMAL (38, 20)   NOT NULL,
    [Sales Unit of Measure]          VARCHAR (10)       NOT NULL,
    [Purch_ Unit of Measure]         VARCHAR (10)       NOT NULL,
    [Reorder Cycle]                  VARCHAR (32)       NOT NULL,
    [Reordering Policy]              INT                NOT NULL,
    [Include Inventory]              TINYINT            NOT NULL,
    [Manufacturing Policy]           INT                NOT NULL,
    [Manufacturer Code]              VARCHAR (10)       NOT NULL,
    [Item Category Code]             VARCHAR (10)       NOT NULL,
    [Created From Nonstock Item]     TINYINT            NOT NULL,
    [Product Group Code]             VARCHAR (10)       NOT NULL,
    [Service Item Group]             VARCHAR (10)       NOT NULL,
    [Item Tracking Code]             VARCHAR (10)       NOT NULL,
    [Lot Nos_]                       VARCHAR (10)       NOT NULL,
    [Expiration Calculation]         VARCHAR (32)       NOT NULL,
    [Special Equipment Code]         VARCHAR (10)       NOT NULL,
    [Put-away Template Code]         VARCHAR (10)       NOT NULL,
    [Put-away Unit of Measure Code]  VARCHAR (10)       NOT NULL,
    [Phys Invt Counting Period Code] VARCHAR (10)       NOT NULL,
    [Last Counting Period Update]    DATETIME           NOT NULL,
    [Next Counting Period]           VARCHAR (250)      NOT NULL,
    [Use Cross-Docking]              TINYINT            NOT NULL,
    [NettoPris]                      DECIMAL (38, 20)   NOT NULL,
    [BruttoAvance %]                 DECIMAL (38, 20)   NOT NULL,
    [ClaimsErstatNr]                 VARCHAR (20)       NOT NULL,
    [Quality]                        INT                NOT NULL,
    [Business Area Code]             VARCHAR (10)       NOT NULL,
    [Item Group Code]                VARCHAR (10)       NOT NULL,
    [Coating]                        VARCHAR (10)       NOT NULL,
    [Product Line Code]              VARCHAR (10)       NOT NULL,
    [Packing Method]                 VARCHAR (10)       NOT NULL,
    [Prod_ Department Code]          VARCHAR (10)       NOT NULL,
    [Sizes Needs Correction]         TINYINT            NOT NULL,
    [Normtid (Støberi)]              DECIMAL (38, 20)   NOT NULL,
    [Normtid (Bearbejdning)]         DECIMAL (38, 20)   NOT NULL,
    [Normtid (Pakkeri)]              DECIMAL (38, 20)   NOT NULL,
    [Routing No_]                    VARCHAR (20)       NOT NULL,
    [Production BOM No_]             VARCHAR (20)       NOT NULL,
    [Single-Level Material Cost]     DECIMAL (38, 20)   NOT NULL,
    [Single-Level Capacity Cost]     DECIMAL (38, 20)   NOT NULL,
    [Single-Level Subcontrd_ Cost]   DECIMAL (38, 20)   NOT NULL,
    [Single-Level Cap_ Ovhd Cost]    DECIMAL (38, 20)   NOT NULL,
    [Single-Level Mfg_ Ovhd Cost]    DECIMAL (38, 20)   NOT NULL,
    [Overhead Rate]                  DECIMAL (38, 20)   NOT NULL,
    [Rolled-up Subcontracted Cost]   DECIMAL (38, 20)   NOT NULL,
    [Rolled-up Mfg_ Ovhd Cost]       DECIMAL (38, 20)   NOT NULL,
    [Rolled-up Cap_ Overhead Cost]   DECIMAL (38, 20)   NOT NULL,
    [Order Tracking Policy]          INT                NOT NULL,
    [Critical]                       TINYINT            NOT NULL,
    [Common Item No_]                VARCHAR (20)       NOT NULL,
    [Unit Cost (Locked)]             DECIMAL (38, 20)   NOT NULL,
    [Item Brand]                     VARCHAR (10)       NOT NULL,
    [Unit Cost II]                   DECIMAL (38, 20)   NOT NULL,
    [Product Usage]                  VARCHAR (10)       NOT NULL,
    [With Lid]                       TINYINT            NOT NULL,
    [ABCD Category]                  VARCHAR (10)       NOT NULL,
    [Item Type]                      INT                NOT NULL,
    [Size]                           VARCHAR (10)       NOT NULL,
    [Volume]                         VARCHAR (10)       NOT NULL,
    [Color]                          VARCHAR (10)       NOT NULL,
    [Size Variant]                   TINYINT            NOT NULL,
    [Volume Variant]                 TINYINT            NOT NULL,
    [Color Variant]                  TINYINT            NOT NULL,
    [Show on Web]                    INT                NOT NULL,
    [Featured on web]                TINYINT            NOT NULL,
    [Web visibility]                 INT                NOT NULL,
    [Image Name]                     VARCHAR (200)      NOT NULL,
    [Stock Group]                    VARCHAR (20)       NOT NULL,
    [360G link]                      VARCHAR (50)       NOT NULL,
    [Variantgroup]                   INT                NOT NULL,
    [Base Diameter]                  VARCHAR (50)       NOT NULL,
    [Placering (Lager)]              VARCHAR (10)       NOT NULL,
    [Weight Classification]          INT                NOT NULL,
    [Item Size]                      VARCHAR (10)       NOT NULL,
    [Manufacturer]                   VARCHAR (20)       NOT NULL,
    [Oprydning spærret]              TINYINT            NOT NULL,
    [PipelineName]                   NVARCHAR (128)     NULL,
    [PipelineRunId]                  NVARCHAR (36)      NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) NULL,
    CONSTRAINT [PK_stg_navdb_Item] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_navdb_Item_timestamp]
    ON [stg_navdb].[Item]([CompanyID] ASC, [timestamp] ASC);


GO

