CREATE TABLE [stg_navdb].[ItemLedgerEntry] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [Entry No_]                    INT                NOT NULL,
    [Item No_]                     VARCHAR (20)       NOT NULL,
    [Posting Date]                 DATETIME           NOT NULL,
    [Entry Type]                   INT                NOT NULL,
    [Source No_]                   VARCHAR (20)       NOT NULL,
    [Document No_]                 VARCHAR (20)       NOT NULL,
    [Description]                  VARCHAR (50)       NOT NULL,
    [Location Code]                VARCHAR (10)       NOT NULL,
    [Quantity]                     DECIMAL (18)       NOT NULL,
    [Remaining Quantity]           DECIMAL (18)       NOT NULL,
    [Invoiced Quantity]            DECIMAL (18)       NOT NULL,
    [Applies-to Entry]             INT                NOT NULL,
    [Open]                         TINYINT            NOT NULL,
    [Global Dimension 1 Code]      VARCHAR (20)       NOT NULL,
    [Global Dimension 2 Code]      VARCHAR (20)       NOT NULL,
    [Positive]                     TINYINT            NOT NULL,
    [Source Type]                  INT                NOT NULL,
    [Drop Shipment]                TINYINT            NOT NULL,
    [Transaction Type]             VARCHAR (10)       NOT NULL,
    [Transport Method]             VARCHAR (10)       NOT NULL,
    [Country_Region Code]          VARCHAR (10)       NOT NULL,
    [Entry_Exit Point]             VARCHAR (10)       NOT NULL,
    [Document Date]                DATETIME           NOT NULL,
    [External Document No_]        VARCHAR (20)       NOT NULL,
    [Area]                         VARCHAR (10)       NOT NULL,
    [Transaction Specification]    VARCHAR (10)       NOT NULL,
    [No_ Series]                   VARCHAR (10)       NOT NULL,
    [Document Type]                INT                NOT NULL,
    [Document Line No_]            INT                NOT NULL,
    [Job No_]                      VARCHAR (20)       NOT NULL,
    [Job Task No_]                 VARCHAR (20)       NOT NULL,
    [Job Purchase]                 TINYINT            NOT NULL,
    [Prod_ Order No_]              VARCHAR (20)       NOT NULL,
    [Variant Code]                 VARCHAR (10)       NOT NULL,
    [Qty_ per Unit of Measure]     DECIMAL (18)       NOT NULL,
    [Unit of Measure Code]         VARCHAR (10)       NOT NULL,
    [Derived from Blanket Order]   TINYINT            NOT NULL,
    [Cross-Reference No_]          VARCHAR (20)       NOT NULL,
    [Originally Ordered No_]       VARCHAR (20)       NOT NULL,
    [Originally Ordered Var_ Code] VARCHAR (10)       NOT NULL,
    [Out-of-Stock Substitution]    TINYINT            NOT NULL,
    [Item Category Code]           VARCHAR (10)       NOT NULL,
    [Nonstock]                     TINYINT            NOT NULL,
    [Purchasing Code]              VARCHAR (10)       NOT NULL,
    [Product Group Code]           VARCHAR (10)       NOT NULL,
    [Transfer Order No_]           VARCHAR (20)       NOT NULL,
    [Completely Invoiced]          TINYINT            NOT NULL,
    [Last Invoice Date]            DATETIME           NOT NULL,
    [Applied Entry to Adjust]      TINYINT            NOT NULL,
    [Correction]                   TINYINT            NOT NULL,
    [Shipped Qty_ Not Returned]    DECIMAL (18)       NOT NULL,
    [Prod_ Order Line No_]         INT                NOT NULL,
    [Prod_ Order Comp_ Line No_]   INT                NOT NULL,
    [Service Order No_]            VARCHAR (20)       NOT NULL,
    [Serial No_]                   VARCHAR (20)       NOT NULL,
    [Lot No_]                      VARCHAR (20)       NOT NULL,
    [Warranty Date]                DATETIME           NOT NULL,
    [Expiration Date]              DATETIME           NOT NULL,
    [Item Tracking]                INT                NOT NULL,
    [Return Reason Code]           VARCHAR (10)       NOT NULL,
    [Campaign Price]               TINYINT            NOT NULL,
    [Campaign No_]                 VARCHAR (20)       NOT NULL,
    [Quality]                      INT                NOT NULL,
    [Business Area Code]           VARCHAR (10)       NOT NULL,
    [Item Group Code]              VARCHAR (10)       NOT NULL,
    [Coating]                      VARCHAR (10)       NOT NULL,
    [Product Line Code]            VARCHAR (10)       NOT NULL,
    [Packing Method]               VARCHAR (10)       NOT NULL,
    [Prod_ Department Code]        VARCHAR (10)       NOT NULL,
    [YearCode Text]                VARCHAR (10)       NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_ItemLedgerEntry_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_ItemLedgerEntry_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_ItemLedgerEntry_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_navdb_ItemLedgerEntry] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Entry No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

