CREATE TABLE [stg_navdb].[PurchInvHeader] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [No_]                          VARCHAR (20)       NOT NULL,
    [Buy-from Vendor No_]          VARCHAR (20)       NOT NULL,
    [Pay-to Vendor No_]            VARCHAR (20)       NOT NULL,
    [Pay-to Name]                  VARCHAR (50)       NOT NULL,
    [Pay-to Name 2]                VARCHAR (50)       NOT NULL,
    [Pay-to Address]               VARCHAR (50)       NOT NULL,
    [Pay-to Address 2]             VARCHAR (50)       NOT NULL,
    [Pay-to City]                  VARCHAR (30)       NOT NULL,
    [Pay-to Contact]               VARCHAR (50)       NOT NULL,
    [Your Reference]               VARCHAR (30)       NOT NULL,
    [Ship-to Code]                 VARCHAR (10)       NOT NULL,
    [Ship-to Name]                 VARCHAR (50)       NOT NULL,
    [Ship-to Name 2]               VARCHAR (50)       NOT NULL,
    [Ship-to Address]              VARCHAR (50)       NOT NULL,
    [Ship-to Address 2]            VARCHAR (50)       NOT NULL,
    [Ship-to City]                 VARCHAR (30)       NOT NULL,
    [Ship-to Contact]              VARCHAR (50)       NOT NULL,
    [Order Date]                   DATETIME           NOT NULL,
    [Posting Date]                 DATETIME           NOT NULL,
    [Expected Receipt Date]        DATETIME           NOT NULL,
    [Posting Description]          VARCHAR (50)       NOT NULL,
    [Payment Terms Code]           VARCHAR (10)       NOT NULL,
    [Due Date]                     DATETIME           NOT NULL,
    [Payment Discount %]           DECIMAL (38, 20)   NOT NULL,
    [Pmt_ Discount Date]           DATETIME           NOT NULL,
    [Shipment Method Code]         VARCHAR (10)       NOT NULL,
    [Location Code]                VARCHAR (10)       NOT NULL,
    [Shortcut Dimension 1 Code]    VARCHAR (20)       NOT NULL,
    [Shortcut Dimension 2 Code]    VARCHAR (20)       NOT NULL,
    [Vendor Posting Group]         VARCHAR (10)       NOT NULL,
    [Currency Code]                VARCHAR (10)       NOT NULL,
    [Currency Factor]              DECIMAL (38, 20)   NOT NULL,
    [Prices Including VAT]         TINYINT            NOT NULL,
    [Invoice Disc_ Code]           VARCHAR (20)       NOT NULL,
    [Language Code]                VARCHAR (10)       NOT NULL,
    [Purchaser Code]               VARCHAR (10)       NOT NULL,
    [Order No_]                    VARCHAR (20)       NOT NULL,
    [No_ Printed]                  INT                NOT NULL,
    [On Hold]                      VARCHAR (3)        NOT NULL,
    [Applies-to Doc_ Type]         INT                NOT NULL,
    [Applies-to Doc_ No_]          VARCHAR (20)       NOT NULL,
    [Bal_ Account No_]             VARCHAR (20)       NOT NULL,
    [Vendor Order No_]             VARCHAR (20)       NOT NULL,
    [Vendor Invoice No_]           VARCHAR (20)       NOT NULL,
    [VAT Registration No_]         VARCHAR (20)       NOT NULL,
    [Sell-to Customer No_]         VARCHAR (20)       NOT NULL,
    [Reason Code]                  VARCHAR (10)       NOT NULL,
    [Gen_ Bus_ Posting Group]      VARCHAR (10)       NOT NULL,
    [Transaction Type]             VARCHAR (10)       NOT NULL,
    [Transport Method]             VARCHAR (10)       NOT NULL,
    [VAT Country_Region Code]      VARCHAR (10)       NOT NULL,
    [Buy-from Vendor Name]         VARCHAR (50)       NOT NULL,
    [Buy-from Vendor Name 2]       VARCHAR (50)       NOT NULL,
    [Buy-from Address]             VARCHAR (50)       NOT NULL,
    [Buy-from Address 2]           VARCHAR (50)       NOT NULL,
    [Buy-from City]                VARCHAR (30)       NOT NULL,
    [Buy-from Contact]             VARCHAR (50)       NOT NULL,
    [Pay-to Post Code]             VARCHAR (20)       NOT NULL,
    [Pay-to County]                VARCHAR (30)       NOT NULL,
    [Pay-to Country_Region Code]   VARCHAR (10)       NOT NULL,
    [Buy-from Post Code]           VARCHAR (20)       NOT NULL,
    [Buy-from County]              VARCHAR (30)       NOT NULL,
    [Buy-from Country_Region Code] VARCHAR (10)       NOT NULL,
    [Ship-to Post Code]            VARCHAR (20)       NOT NULL,
    [Ship-to County]               VARCHAR (30)       NOT NULL,
    [Ship-to Country_Region Code]  VARCHAR (10)       NOT NULL,
    [Bal_ Account Type]            INT                NOT NULL,
    [Order Address Code]           VARCHAR (10)       NOT NULL,
    [Entry Point]                  VARCHAR (10)       NOT NULL,
    [Correction]                   TINYINT            NOT NULL,
    [Document Date]                DATETIME           NOT NULL,
    [Area]                         VARCHAR (10)       NOT NULL,
    [Transaction Specification]    VARCHAR (10)       NOT NULL,
    [Payment Method Code]          VARCHAR (10)       NOT NULL,
    [Pre-Assigned No_ Series]      VARCHAR (10)       NOT NULL,
    [No_ Series]                   VARCHAR (10)       NOT NULL,
    [Order No_ Series]             VARCHAR (10)       NOT NULL,
    [Pre-Assigned No_]             VARCHAR (20)       NOT NULL,
    [User ID]                      VARCHAR (20)       NOT NULL,
    [Source Code]                  VARCHAR (10)       NOT NULL,
    [Tax Area Code]                VARCHAR (20)       NOT NULL,
    [Tax Liable]                   TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]       VARCHAR (10)       NOT NULL,
    [VAT Base Discount %]          DECIMAL (38, 20)   NOT NULL,
    [Prepayment No_ Series]        VARCHAR (10)       NOT NULL,
    [Prepayment Invoice]           TINYINT            NOT NULL,
    [Prepayment Order No_]         VARCHAR (20)       NOT NULL,
    [Quote No_]                    VARCHAR (20)       NOT NULL,
    [Campaign No_]                 VARCHAR (20)       NOT NULL,
    [Buy-from Contact No_]         VARCHAR (20)       NOT NULL,
    [Pay-to Contact No_]           VARCHAR (20)       NOT NULL,
    [Responsibility Center]        VARCHAR (10)       NOT NULL,
    [ABN]                          VARCHAR (14)       NOT NULL,
    [ABN Division Part No_]        VARCHAR (3)        NOT NULL,
    [WHT Business Posting Group]   VARCHAR (10)       NOT NULL,
    [Actual Vendor No_]            VARCHAR (20)       NOT NULL,
    [Printed Tax Document]         TINYINT            NOT NULL,
    [Posted Tax Document]          TINYINT            NOT NULL,
    [Tax Document Marked]          TINYINT            NOT NULL,
    [Invoice Print Type]           INT                NOT NULL,
    [Date Received]                DATETIME           NOT NULL,
    [Time Received]                DATETIME           NOT NULL,
    [BizTalk Purchase Invoice]     TINYINT            NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_PurchInvHeader_PipeHdrName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_PurchInvHeader_PipeHdrRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_PurchInvHeader_PipeHdrTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_navdb_PurchInvHeader] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC)
);


GO

