CREATE TABLE [stg_navdb].[SalesHeader] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Document Type]                  INT                NOT NULL,
    [No_]                            NVARCHAR (20)      NOT NULL,
    [Sell-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Bill-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Bill-to Name]                   NVARCHAR (50)      NOT NULL,
    [Bill-to Name 2]                 NVARCHAR (50)      NOT NULL,
    [Bill-to Address]                NVARCHAR (50)      NOT NULL,
    [Bill-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Bill-to City]                   NVARCHAR (30)      NOT NULL,
    [Bill-to Contact]                NVARCHAR (50)      NOT NULL,
    [Your Reference]                 NVARCHAR (30)      NOT NULL,
    [Ship-to Code]                   NVARCHAR (10)      NOT NULL,
    [Ship-to Name]                   NVARCHAR (50)      NOT NULL,
    [Ship-to Name 2]                 NVARCHAR (50)      NOT NULL,
    [Ship-to Address]                NVARCHAR (50)      NOT NULL,
    [Ship-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Ship-to City]                   NVARCHAR (30)      NOT NULL,
    [Ship-to Contact]                NVARCHAR (50)      NOT NULL,
    [Order Date]                     DATETIME           NOT NULL,
    [Posting Date]                   DATETIME           NOT NULL,
    [Shipment Date]                  DATETIME           NOT NULL,
    [Posting Description]            NVARCHAR (50)      NOT NULL,
    [Payment Terms Code]             NVARCHAR (10)      NOT NULL,
    [Due Date]                       DATETIME           NOT NULL,
    [Payment Discount %]             DECIMAL (38, 20)   NOT NULL,
    [Pmt_ Discount Date]             DATETIME           NOT NULL,
    [Shipment Method Code]           NVARCHAR (10)      NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Customer Posting Group]         NVARCHAR (10)      NOT NULL,
    [Currency Code]                  NVARCHAR (10)      NOT NULL,
    [Currency Factor]                DECIMAL (38, 20)   NOT NULL,
    [Customer Price Group]           NVARCHAR (10)      NOT NULL,
    [Prices Including VAT]           TINYINT            NOT NULL,
    [Invoice Disc_ Code]             NVARCHAR (20)      NOT NULL,
    [Customer Disc_ Group]           NVARCHAR (10)      NOT NULL,
    [Language Code]                  NVARCHAR (10)      NOT NULL,
    [Salesperson Code]               NVARCHAR (10)      NOT NULL,
    [Order Class]                    NVARCHAR (10)      NOT NULL,
    [No_ Printed]                    INT                NOT NULL,
    [On Hold]                        NVARCHAR (3)       NOT NULL,
    [Applies-to Doc_ Type]           INT                NOT NULL,
    [Applies-to Doc_ No_]            NVARCHAR (20)      NOT NULL,
    [Bal_ Account No_]               NVARCHAR (20)      NOT NULL,
    [Ship]                           TINYINT            NOT NULL,
    [Invoice]                        TINYINT            NOT NULL,
    [Shipping No_]                   NVARCHAR (20)      NOT NULL,
    [Posting No_]                    NVARCHAR (20)      NOT NULL,
    [Last Shipping No_]              NVARCHAR (20)      NOT NULL,
    [Last Posting No_]               NVARCHAR (20)      NOT NULL,
    [Prepayment No_]                 NVARCHAR (20)      NOT NULL,
    [Last Prepayment No_]            NVARCHAR (20)      NOT NULL,
    [Prepmt_ Cr_ Memo No_]           NVARCHAR (20)      NOT NULL,
    [Last Prepmt_ Cr_ Memo No_]      NVARCHAR (20)      NOT NULL,
    [VAT Registration No_]           NVARCHAR (20)      NOT NULL,
    [Combine Shipments]              TINYINT            NOT NULL,
    [Reason Code]                    NVARCHAR (10)      NOT NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (10)      NOT NULL,
    [EU 3-Party Trade]               TINYINT            NOT NULL,
    [Transaction Type]               NVARCHAR (10)      NOT NULL,
    [Transport Method]               NVARCHAR (10)      NOT NULL,
    [VAT Country_Region Code]        NVARCHAR (10)      NOT NULL,
    [Sell-to Customer Name]          NVARCHAR (50)      NOT NULL,
    [Sell-to Customer Name 2]        NVARCHAR (50)      NOT NULL,
    [Sell-to Address]                NVARCHAR (50)      NOT NULL,
    [Sell-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Sell-to City]                   NVARCHAR (30)      NOT NULL,
    [Sell-to Contact]                NVARCHAR (50)      NOT NULL,
    [Bill-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Bill-to County]                 NVARCHAR (30)      NOT NULL,
    [Bill-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [Sell-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Sell-to County]                 NVARCHAR (30)      NOT NULL,
    [Sell-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [Ship-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Ship-to County]                 NVARCHAR (30)      NOT NULL,
    [Ship-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [Bal_ Account Type]              INT                NOT NULL,
    [Exit Point]                     NVARCHAR (10)      NOT NULL,
    [Correction]                     TINYINT            NOT NULL,
    [Document Date]                  DATETIME           NOT NULL,
    [External Document No_]          NVARCHAR (20)      NOT NULL,
    [Area]                           NVARCHAR (10)      NOT NULL,
    [Transaction Specification]      NVARCHAR (10)      NOT NULL,
    [Payment Method Code]            NVARCHAR (10)      NOT NULL,
    [Shipping Agent Code]            NVARCHAR (10)      NOT NULL,
    [Package Tracking No_]           NVARCHAR (30)      NOT NULL,
    [No_ Series]                     NVARCHAR (10)      NOT NULL,
    [Posting No_ Series]             NVARCHAR (10)      NOT NULL,
    [Shipping No_ Series]            NVARCHAR (10)      NOT NULL,
    [Tax Area Code]                  NVARCHAR (20)      NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (10)      NOT NULL,
    [Reserve]                        INT                NOT NULL,
    [Applies-to ID]                  NVARCHAR (20)      NOT NULL,
    [VAT Base Discount %]            DECIMAL (38, 20)   NOT NULL,
    [Status]                         INT                NOT NULL,
    [Invoice Discount Calculation]   INT                NOT NULL,
    [Invoice Discount Value]         DECIMAL (38, 20)   NOT NULL,
    [Send IC Document]               TINYINT            NOT NULL,
    [IC Status]                      INT                NOT NULL,
    [Sell-to IC Partner Code]        NVARCHAR (20)      NOT NULL,
    [Bill-to IC Partner Code]        NVARCHAR (20)      NOT NULL,
    [IC Direction]                   INT                NOT NULL,
    [Prepayment %]                   DECIMAL (38, 20)   NOT NULL,
    [Prepayment No_ Series]          NVARCHAR (10)      NOT NULL,
    [Compress Prepayment]            TINYINT            NOT NULL,
    [Prepayment Due Date]            DATETIME           NOT NULL,
    [Prepmt_ Cr_ Memo No_ Series]    NVARCHAR (10)      NOT NULL,
    [Prepmt_ Posting Description]    NVARCHAR (50)      NOT NULL,
    [Prepmt_ Pmt_ Discount Date]     DATETIME           NOT NULL,
    [Prepmt_ Payment Terms Code]     NVARCHAR (10)      NOT NULL,
    [Prepmt_ Payment Discount %]     DECIMAL (38, 20)   NOT NULL,
    [Quote No_]                      NVARCHAR (20)      NOT NULL,
    [Doc_ No_ Occurrence]            INT                NOT NULL,
    [Campaign No_]                   NVARCHAR (20)      NOT NULL,
    [Sell-to Customer Template Code] NVARCHAR (10)      NOT NULL,
    [Sell-to Contact No_]            NVARCHAR (20)      NOT NULL,
    [Bill-to Contact No_]            NVARCHAR (20)      NOT NULL,
    [Bill-to Customer Template Code] NVARCHAR (10)      NOT NULL,
    [Opportunity No_]                NVARCHAR (20)      NOT NULL,
    [Responsibility Center]          NVARCHAR (10)      NOT NULL,
    [Shipping Advice]                INT                NOT NULL,
    [Posting from Whse_ Ref_]        INT                NOT NULL,
    [Requested Delivery Date]        DATETIME           NOT NULL,
    [Promised Delivery Date]         DATETIME           NOT NULL,
    [Shipping Time]                  NVARCHAR (32)      NOT NULL,
    [Outbound Whse_ Handling Time]   NVARCHAR (32)      NOT NULL,
    [Shipping Agent Service Code]    NVARCHAR (10)      NOT NULL,
    [Receive]                        TINYINT            NOT NULL,
    [Return Receipt No_]             NVARCHAR (20)      NOT NULL,
    [Return Receipt No_ Series]      NVARCHAR (10)      NOT NULL,
    [Last Return Receipt No_]        NVARCHAR (20)      NOT NULL,
    [Allow Line Disc_]               TINYINT            NOT NULL,
    [Get Shipment Used]              TINYINT            NOT NULL,
    [Signature]                      VARBINARY (MAX)    NULL,
    [Assigned User ID]               NVARCHAR (20)      NOT NULL,
    [EAN No_]                        NVARCHAR (13)      NOT NULL,
    [Account Code]                   NVARCHAR (30)      NOT NULL,
    [Sell-to Contact Phone No_]      NVARCHAR (30)      NOT NULL,
    [Sell-to Contact Fax No_]        NVARCHAR (30)      NOT NULL,
    [Sell-to Contact E-Mail]         NVARCHAR (80)      NOT NULL,
    [Sell-to Contact Role]           INT                NOT NULL,
    [Payment Channel]                INT                NOT NULL,
    [Calculate freight]              TINYINT            NOT NULL,
    [Order note 1]                   NVARCHAR (250)     NOT NULL,
    [Order note 2]                   NVARCHAR (250)     NOT NULL,
    [Sent as E-mail]                 TINYINT            NOT NULL,
    [Ready to ship]                  TINYINT            NOT NULL,
    [Total volume]                   DECIMAL (38, 20)   NOT NULL,
    [Dimension & Salesinfo from]     INT                NOT NULL,
    [Total weight]                   DECIMAL (38, 20)   NOT NULL,
    [Chain Code]                     NVARCHAR (20)      NOT NULL,
    [Chain Group Code]               NVARCHAR (20)      NOT NULL,
    [Invoice-Show Country of Origin] TINYINT            NOT NULL,
    [Transf_ To_From Company]        TINYINT            NOT NULL,
    [Transf_ To_From Company Name]   NVARCHAR (30)      NOT NULL,
    [Transf_ To_From Doc_ Type]      INT                NOT NULL,
    [Transf_ To_From Doc_ No_]       NVARCHAR (20)      NOT NULL,
    [Transf_ Direction]              INT                NOT NULL,
    [Batch Posting]                  TINYINT            NOT NULL,
    [KøbersRef_Nr]                   NVARCHAR (20)      NOT NULL,
    [KøbersRef_Dato]                 DATETIME           NOT NULL,
    [Date Received]                  DATETIME           NOT NULL,
    [Time Received]                  DATETIME           NOT NULL,
    [BizTalk Request for Sales Qte_] TINYINT            NOT NULL,
    [BizTalk Sales Order]            TINYINT            NOT NULL,
    [Date Sent]                      DATETIME           NOT NULL,
    [Time Sent]                      DATETIME           NOT NULL,
    [BizTalk Sales Quote]            TINYINT            NOT NULL,
    [BizTalk Sales Order Cnfmn_]     TINYINT            NOT NULL,
    [Customer Quote No_]             NVARCHAR (20)      NOT NULL,
    [Customer Order No_]             NVARCHAR (20)      NOT NULL,
    [BizTalk Document Sent]          TINYINT            NOT NULL,
    [Delete back order]              TINYINT            NOT NULL,
    [Order confirmation Printed]     DATETIME           NOT NULL,
    [Dont Use Delivery Date (Price)] TINYINT            NOT NULL,
    [Allow EDI]                      TINYINT            NOT NULL,
    [Starting Date]                  DATETIME           NOT NULL,
    [Ending Date]                    DATETIME           NOT NULL,
    [Created Date]                   DATETIME           NOT NULL,
    [Created By]                     NVARCHAR (20)      NOT NULL,
    [Modified Date]                  DATETIME           NOT NULL,
    [Modified By]                    NVARCHAR (20)      NOT NULL,
    [N-lwi Order]                    TINYINT            NOT NULL,
    [N-lwi Payment ID]               NVARCHAR (40)      NOT NULL,
    [N-lwi Payment Order No]         NVARCHAR (40)      NOT NULL,
    [N-lwi Coupon Code]              NVARCHAR (30)      NOT NULL,
    [Container No_]                  NVARCHAR (15)      NOT NULL,
    [Payment Reference]              NVARCHAR (30)      NOT NULL,
    [ReqDeliveryDateSend]            INT                NOT NULL,
    [Release date]                   DATETIME           NOT NULL,
    [CustomsRefNo]                   NVARCHAR (15)      NOT NULL,
    [Sales Order Priority]           INT                NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_SalesHeader_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_SalesHeader_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_SalesHeader_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_navdb_SalesHeader] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document Type] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

