CREATE TABLE [stg_navdb].[SalesInvoiceLine] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Document No_]                   NVARCHAR (20)      NOT NULL,
    [Line No_]                       INT                NOT NULL,
    [Sell-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Type]                           INT                NOT NULL,
    [No_]                            NVARCHAR (20)      NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Posting Group]                  NVARCHAR (10)      NOT NULL,
    [Shipment Date]                  DATETIME           NOT NULL,
    [Description]                    NVARCHAR (50)      NOT NULL,
    [Description 2]                  NVARCHAR (50)      NOT NULL,
    [Unit of Measure]                NVARCHAR (10)      NOT NULL,
    [Quantity]                       DECIMAL (38, 20)   NOT NULL,
    [Unit Price]                     DECIMAL (38, 20)   NOT NULL,
    [Unit Cost (LCY)]                DECIMAL (38, 20)   NOT NULL,
    [VAT %]                          DECIMAL (38, 20)   NOT NULL,
    [Line Discount %]                DECIMAL (38, 20)   NOT NULL,
    [Line Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Amount]                         DECIMAL (38, 20)   NOT NULL,
    [Amount Including VAT]           DECIMAL (38, 20)   NOT NULL,
    [Allow Invoice Disc_]            TINYINT            NOT NULL,
    [Gross Weight]                   DECIMAL (38, 20)   NOT NULL,
    [Net Weight]                     DECIMAL (38, 20)   NOT NULL,
    [Units per Parcel]               DECIMAL (38, 20)   NOT NULL,
    [Unit Volume]                    DECIMAL (38, 20)   NOT NULL,
    [Appl_-to Item Entry]            INT                NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Customer Price Group]           NVARCHAR (10)      NOT NULL,
    [Job No_]                        NVARCHAR (20)      NOT NULL,
    [Work Type Code]                 NVARCHAR (10)      NOT NULL,
    [Shipment No_]                   NVARCHAR (20)      NOT NULL,
    [Shipment Line No_]              INT                NOT NULL,
    [Bill-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Inv_ Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Drop Shipment]                  TINYINT            NOT NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (10)      NOT NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (10)      NOT NULL,
    [VAT Calculation Type]           INT                NOT NULL,
    [Transaction Type]               NVARCHAR (10)      NOT NULL,
    [Transport Method]               NVARCHAR (10)      NOT NULL,
    [Attached to Line No_]           INT                NOT NULL,
    [Exit Point]                     NVARCHAR (10)      NOT NULL,
    [Area]                           NVARCHAR (10)      NOT NULL,
    [Transaction Specification]      NVARCHAR (10)      NOT NULL,
    [Tax Area Code]                  NVARCHAR (20)      NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [Tax Group Code]                 NVARCHAR (10)      NOT NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (10)      NOT NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (10)      NOT NULL,
    [Blanket Order No_]              NVARCHAR (20)      NOT NULL,
    [Blanket Order Line No_]         INT                NOT NULL,
    [VAT Base Amount]                DECIMAL (38, 20)   NOT NULL,
    [Unit Cost]                      DECIMAL (38, 20)   NOT NULL,
    [System-Created Entry]           TINYINT            NOT NULL,
    [Line Amount]                    DECIMAL (38, 20)   NOT NULL,
    [VAT Difference]                 DECIMAL (38, 20)   NOT NULL,
    [VAT Identifier]                 NVARCHAR (10)      NOT NULL,
    [IC Partner Ref_ Type]           INT                NOT NULL,
    [IC Partner Reference]           NVARCHAR (20)      NOT NULL,
    [Prepayment Line]                TINYINT            NOT NULL,
    [IC Partner Code]                NVARCHAR (20)      NOT NULL,
    [Posting Date]                   DATETIME           NOT NULL,
    [Job Task No_]                   NVARCHAR (20)      NOT NULL,
    [Job Contract Entry No_]         INT                NOT NULL,
    [Variant Code]                   NVARCHAR (10)      NOT NULL,
    [Bin Code]                       NVARCHAR (20)      NOT NULL,
    [Qty_ per Unit of Measure]       DECIMAL (38, 20)   NOT NULL,
    [Unit of Measure Code]           NVARCHAR (10)      NOT NULL,
    [Quantity (Base)]                DECIMAL (38, 20)   NOT NULL,
    [FA Posting Date]                DATETIME           NOT NULL,
    [Depreciation Book Code]         NVARCHAR (10)      NOT NULL,
    [Depr_ until FA Posting Date]    TINYINT            NOT NULL,
    [Duplicate in Depreciation Book] NVARCHAR (10)      NOT NULL,
    [Use Duplication List]           TINYINT            NOT NULL,
    [Responsibility Center]          NVARCHAR (10)      NOT NULL,
    [Cross-Reference No_]            NVARCHAR (20)      NOT NULL,
    [Unit of Measure (Cross Ref_)]   NVARCHAR (10)      NOT NULL,
    [Cross-Reference Type]           INT                NOT NULL,
    [Cross-Reference Type No_]       NVARCHAR (30)      NOT NULL,
    [Item Category Code]             NVARCHAR (10)      NOT NULL,
    [Nonstock]                       TINYINT            NOT NULL,
    [Purchasing Code]                NVARCHAR (10)      NOT NULL,
    [Product Group Code]             NVARCHAR (10)      NOT NULL,
    [Appl_-from Item Entry]          INT                NOT NULL,
    [Return Reason Code]             NVARCHAR (10)      NOT NULL,
    [Allow Line Disc_]               TINYINT            NOT NULL,
    [Customer Disc_ Group]           NVARCHAR (10)      NOT NULL,
    [Account Code]                   NVARCHAR (30)      NOT NULL,
    [Campaign Price]                 TINYINT            NOT NULL,
    [Campaign No_]                   NVARCHAR (20)      NOT NULL,
    [Seal No_]                       NVARCHAR (20)      NOT NULL,
    [Container No_]                  NVARCHAR (20)      NOT NULL,
    [Country_Region of Origin Code]  NVARCHAR (10)      NOT NULL,
    [Intrastat Code]                 NVARCHAR (10)      NOT NULL,
    [YearCode Text]                  NVARCHAR (10)      NOT NULL,
    [Unit Cost II (LCY)]             DECIMAL (38, 20)   NOT NULL,
    [Product Line Code]              NVARCHAR (10)      NOT NULL,
    [Item Brand]                     NVARCHAR (10)      NOT NULL,
    [Created Date]                   DATETIME           NOT NULL,
    [Created By]                     NVARCHAR (20)      NOT NULL,
    [Modified Date]                  DATETIME           NOT NULL,
    [Modified By]                    NVARCHAR (20)      NOT NULL,
    [Normal Net Price]               DECIMAL (38, 20)   NOT NULL,
    [Normal Net Amount]              DECIMAL (38, 20)   NOT NULL,
    [Original Line Quantity]         DECIMAL (38, 20)   NOT NULL,
    [KSD Container No_]              NVARCHAR (11)      NOT NULL,
    [CustomsRefNo]                   NVARCHAR (15)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_SalesInvoiceLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_SalesInvoiceLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_SalesInvoiceLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_navdb_SalesInvoiceLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document No_] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

CREATE NONCLUSTERED INDEX [NIX_stg_navdb_SalesInvoiceLine_Type_PostingDate_WithIncluded]
    ON [stg_navdb].[SalesInvoiceLine]([Type] ASC, [Posting Date] ASC)
    INCLUDE([timestamp], [No_], [Location Code], [Quantity], [Unit Cost (LCY)], [Amount], [Shortcut Dimension 1 Code], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [Unit Cost], [Return Reason Code]) WITH (DATA_COMPRESSION = ROW);


GO

