CREATE TABLE [stg_navdb].[SalesLine] (
    [CompanyID]                      TINYINT            NOT NULL,
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Document Type]                  INT                NOT NULL,
    [Document No_]                   VARCHAR (20)       NOT NULL,
    [Line No_]                       INT                NOT NULL,
    [Sell-to Customer No_]           VARCHAR (20)       NOT NULL,
    [Type]                           INT                NOT NULL,
    [No_]                            VARCHAR (20)       NOT NULL,
    [Location Code]                  VARCHAR (10)       NOT NULL,
    [Posting Group]                  VARCHAR (10)       NOT NULL,
    [Shipment Date]                  DATETIME           NOT NULL,
    [Description]                    VARCHAR (50)       NOT NULL,
    [Description 2]                  VARCHAR (50)       NOT NULL,
    [Unit of Measure]                VARCHAR (40)       NOT NULL,
    [Quantity]                       DECIMAL (38, 20)   NOT NULL,
    [Outstanding Quantity]           DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Invoice]                DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Ship]                   DECIMAL (38, 20)   NOT NULL,
    [Unit Price]                     DECIMAL (38, 20)   NOT NULL,
    [Unit Cost (LCY)]                DECIMAL (38, 20)   NOT NULL,
    [VAT %]                          DECIMAL (38, 20)   NOT NULL,
    [Line Discount %]                DECIMAL (38, 20)   NOT NULL,
    [Line Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Amount]                         DECIMAL (38, 20)   NOT NULL,
    [Amount Including VAT]           DECIMAL (38, 20)   NOT NULL,
    [Allow Invoice Disc_]            TINYINT            NOT NULL,
    [Gross Weight]                   DECIMAL (38, 20)   NOT NULL,
    [Net Weight]                     DECIMAL (38, 20)   NOT NULL,
    [Units per Parcel]               DECIMAL (38, 20)   NOT NULL,
    [Unit Volume]                    DECIMAL (38, 20)   NOT NULL,
    [Appl_-to Item Entry]            INT                NOT NULL,
    [Shortcut Dimension 1 Code]      VARCHAR (20)       NOT NULL,
    [Shortcut Dimension 2 Code]      VARCHAR (20)       NOT NULL,
    [Customer Price Group]           VARCHAR (10)       NOT NULL,
    [Job No_]                        VARCHAR (20)       NOT NULL,
    [Work Type Code]                 VARCHAR (10)       NOT NULL,
    [Outstanding Amount]             DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped Not Invoiced]      DECIMAL (38, 20)   NOT NULL,
    [Shipped Not Invoiced]           DECIMAL (38, 20)   NOT NULL,
    [Quantity Shipped]               DECIMAL (38, 20)   NOT NULL,
    [Quantity Invoiced]              DECIMAL (38, 20)   NOT NULL,
    [Shipment No_]                   VARCHAR (20)       NOT NULL,
    [Shipment Line No_]              INT                NOT NULL,
    [Profit %]                       DECIMAL (38, 20)   NOT NULL,
    [Bill-to Customer No_]           VARCHAR (20)       NOT NULL,
    [Inv_ Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Purchase Order No_]             VARCHAR (20)       NOT NULL,
    [Purch_ Order Line No_]          INT                NOT NULL,
    [Drop Shipment]                  TINYINT            NOT NULL,
    [Gen_ Bus_ Posting Group]        VARCHAR (10)       NOT NULL,
    [Gen_ Prod_ Posting Group]       VARCHAR (10)       NOT NULL,
    [VAT Calculation Type]           INT                NOT NULL,
    [Transaction Type]               VARCHAR (10)       NOT NULL,
    [Transport Method]               VARCHAR (10)       NOT NULL,
    [Attached to Line No_]           INT                NOT NULL,
    [Exit Point]                     VARCHAR (10)       NOT NULL,
    [Area]                           VARCHAR (10)       NOT NULL,
    [Transaction Specification]      VARCHAR (10)       NOT NULL,
    [Tax Area Code]                  VARCHAR (20)       NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [Tax Group Code]                 VARCHAR (10)       NOT NULL,
    [VAT Bus_ Posting Group]         VARCHAR (10)       NOT NULL,
    [VAT Prod_ Posting Group]        VARCHAR (10)       NOT NULL,
    [Currency Code]                  VARCHAR (10)       NOT NULL,
    [Outstanding Amount (LCY)]       DECIMAL (38, 20)   NOT NULL,
    [Shipped Not Invoiced (LCY)]     DECIMAL (38, 20)   NOT NULL,
    [Reserve]                        INT                NOT NULL,
    [Blanket Order No_]              VARCHAR (20)       NOT NULL,
    [Blanket Order Line No_]         INT                NOT NULL,
    [VAT Base Amount]                DECIMAL (38, 20)   NOT NULL,
    [Unit Cost]                      DECIMAL (38, 20)   NOT NULL,
    [System-Created Entry]           TINYINT            NOT NULL,
    [Line Amount]                    DECIMAL (38, 20)   NOT NULL,
    [VAT Difference]                 DECIMAL (38, 20)   NOT NULL,
    [Inv_ Disc_ Amount to Invoice]   DECIMAL (38, 20)   NOT NULL,
    [VAT Identifier]                 VARCHAR (10)       NOT NULL,
    [IC Partner Ref_ Type]           INT                NOT NULL,
    [IC Partner Reference]           VARCHAR (20)       NOT NULL,
    [Prepayment %]                   DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Line Amount]            DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Amt_ Inv_]              DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Amt_ Incl_ VAT]         DECIMAL (38, 20)   NOT NULL,
    [Prepayment Amount]              DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ VAT Base Amt_]          DECIMAL (38, 20)   NOT NULL,
    [Prepayment VAT %]               DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ VAT Calc_ Type]         INT                NOT NULL,
    [Prepayment VAT Identifier]      VARCHAR (10)       NOT NULL,
    [Prepayment Tax Area Code]       VARCHAR (20)       NOT NULL,
    [Prepayment Tax Liable]          TINYINT            NOT NULL,
    [Prepayment Tax Group Code]      VARCHAR (10)       NOT NULL,
    [Prepmt Amt to Deduct]           DECIMAL (38, 20)   NOT NULL,
    [Prepmt Amt Deducted]            DECIMAL (38, 20)   NOT NULL,
    [Prepayment Line]                TINYINT            NOT NULL,
    [Prepmt_ Amount Inv_ Incl_ VAT]  DECIMAL (38, 20)   NOT NULL,
    [IC Partner Code]                VARCHAR (20)       NOT NULL,
    [Job Task No_]                   VARCHAR (20)       NOT NULL,
    [Job Contract Entry No_]         INT                NOT NULL,
    [Variant Code]                   VARCHAR (10)       NOT NULL,
    [Bin Code]                       VARCHAR (20)       NOT NULL,
    [Qty_ per Unit of Measure]       DECIMAL (38, 20)   NOT NULL,
    [Planned]                        TINYINT            NOT NULL,
    [Unit of Measure Code]           VARCHAR (10)       NOT NULL,
    [Quantity (Base)]                DECIMAL (38, 20)   NOT NULL,
    [Outstanding Qty_ (Base)]        DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Invoice (Base)]         DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Ship (Base)]            DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped Not Invd_ (Base)]  DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped (Base)]            DECIMAL (38, 20)   NOT NULL,
    [Qty_ Invoiced (Base)]           DECIMAL (38, 20)   NOT NULL,
    [FA Posting Date]                DATETIME           NOT NULL,
    [Depreciation Book Code]         VARCHAR (10)       NOT NULL,
    [Depr_ until FA Posting Date]    TINYINT            NOT NULL,
    [Duplicate in Depreciation Book] VARCHAR (10)       NOT NULL,
    [Use Duplication List]           TINYINT            NOT NULL,
    [Responsibility Center]          VARCHAR (10)       NOT NULL,
    [Out-of-Stock Substitution]      TINYINT            NOT NULL,
    [Originally Ordered No_]         VARCHAR (20)       NOT NULL,
    [Originally Ordered Var_ Code]   VARCHAR (10)       NOT NULL,
    [Cross-Reference No_]            VARCHAR (20)       NOT NULL,
    [Unit of Measure (Cross Ref_)]   VARCHAR (10)       NOT NULL,
    [Cross-Reference Type]           INT                NOT NULL,
    [Cross-Reference Type No_]       VARCHAR (30)       NOT NULL,
    [Item Category Code]             VARCHAR (10)       NOT NULL,
    [Nonstock]                       TINYINT            NOT NULL,
    [Purchasing Code]                VARCHAR (10)       NOT NULL,
    [Product Group Code]             VARCHAR (10)       NOT NULL,
    [Special Order]                  TINYINT            NOT NULL,
    [Special Order Purchase No_]     VARCHAR (20)       NOT NULL,
    [Special Order Purch_ Line No_]  INT                NOT NULL,
    [Completely Shipped]             TINYINT            NOT NULL,
    [Requested Delivery Date]        DATETIME           NOT NULL,
    [Promised Delivery Date]         DATETIME           NOT NULL,
    [Shipping Time]                  VARCHAR (32)       NOT NULL,
    [Outbound Whse_ Handling Time]   VARCHAR (32)       NOT NULL,
    [Planned Delivery Date]          DATETIME           NOT NULL,
    [Planned Shipment Date]          DATETIME           NOT NULL,
    [Shipping Agent Code]            VARCHAR (10)       NOT NULL,
    [Shipping Agent Service Code]    VARCHAR (10)       NOT NULL,
    [Allow Item Charge Assignment]   TINYINT            NOT NULL,
    [Return Qty_ to Receive]         DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ to Receive (Base)]  DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ Rcd_ Not Invd_]     DECIMAL (38, 20)   NOT NULL,
    [Ret_ Qty_ Rcd_ Not Invd_(Base)] DECIMAL (38, 20)   NOT NULL,
    [Return Rcd_ Not Invd_]          DECIMAL (38, 20)   NOT NULL,
    [Return Rcd_ Not Invd_ (LCY)]    DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ Received]           DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ Received (Base)]    DECIMAL (38, 20)   NOT NULL,
    [Appl_-from Item Entry]          INT                NOT NULL,
    [BOM Item No_]                   VARCHAR (20)       NOT NULL,
    [Return Receipt No_]             VARCHAR (20)       NOT NULL,
    [Return Receipt Line No_]        INT                NOT NULL,
    [Return Reason Code]             VARCHAR (10)       NOT NULL,
    [Allow Line Disc_]               TINYINT            NOT NULL,
    [Customer Disc_ Group]           VARCHAR (10)       NOT NULL,
    [Account Code]                   VARCHAR (30)       NOT NULL,
    [Campaign Price]                 TINYINT            NOT NULL,
    [Campaign No_]                   VARCHAR (20)       NOT NULL,
    [Expanded from Line No_]         INT                NOT NULL,
    [Next Qty_ per UoM]              DECIMAL (38, 20)   NOT NULL,
    [Order note 1]                   VARCHAR (250)      NOT NULL,
    [Order note 2]                   VARCHAR (250)      NOT NULL,
    [Seal No_]                       VARCHAR (20)       NOT NULL,
    [Container No_]                  VARCHAR (20)       NOT NULL,
    [Country_Region of Origin Code]  VARCHAR (10)       NOT NULL,
    [Intrastat Code]                 VARCHAR (10)       NOT NULL,
    [YearCode Text]                  VARCHAR (10)       NOT NULL,
    [Calculated Freight]             TINYINT            NOT NULL,
    [Unit Cost II (LCY)]             DECIMAL (38, 20)   NOT NULL,
    [Product Line Code]              VARCHAR (10)       NOT NULL,
    [Item Brand]                     VARCHAR (10)       NOT NULL,
    [Forecast Quantity]              DECIMAL (38, 20)   NOT NULL,
    [Forecast %]                     DECIMAL (38, 20)   NOT NULL,
    [Unit List Price]                DECIMAL (38, 20)   NOT NULL,
    [Normal Net Price]               DECIMAL (38, 20)   NOT NULL,
    [Quote List Price]               DECIMAL (38, 20)   NOT NULL,
    [Quote Profit %]                 DECIMAL (38, 20)   NOT NULL,
    [Quote Contribution Margin]      DECIMAL (38, 20)   NOT NULL,
    [Normal Net Amount]              DECIMAL (38, 20)   NOT NULL,
    [Minimum Quantity]               DECIMAL (38, 20)   NOT NULL,
    [Created Date]                   DATETIME           NOT NULL,
    [Created By]                     VARCHAR (20)       NOT NULL,
    [Modified Date]                  DATETIME           NOT NULL,
    [Modified By]                    VARCHAR (20)       NOT NULL,
    [Export Date]                    DATETIME           NOT NULL,
    [Export Declaration]             VARCHAR (50)       NOT NULL,
    [ABCD Category]                  VARCHAR (10)       NOT NULL,
    [N-lwi Identifier]               VARCHAR (80)       NOT NULL,
    [N-lwi Price Calc]               TINYINT            NOT NULL,
    [PipelineName]                   NVARCHAR (128)     NULL,
    [PipelineRunId]                  NVARCHAR (36)      NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) NULL,
    CONSTRAINT [PK_stg_navdb_SalesLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document Type] ASC, [Document No_] ASC, [Line No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_navdb_SalesLine_timestamp]
    ON [stg_navdb].[SalesLine]([CompanyID] ASC, [timestamp] ASC);


GO

