CREATE TABLE [stg_bc_cloud].[ChartOfAccounts] (
    [No]                             NVARCHAR (MAX)   NULL,
    [Name]                           NVARCHAR (MAX)   NULL,
    [Net_Change]                     DECIMAL (38, 18) NULL,
    [Balance]                        DECIMAL (38, 18) NULL,
    [Income_Balance]                 NVARCHAR (MAX)   NULL,
    [Account_Category]               NVARCHAR (MAX)   NULL,
    [Account_Subcategory_Descript]   NVARCHAR (MAX)   NULL,
    [Account_Type]                   NVARCHAR (MAX)   NULL,
    [Direct_Posting]                 BIT              NULL,
    [Totaling]                       NVARCHAR (MAX)   NULL,
    [Gen_Posting_Type]               NVARCHAR (MAX)   NULL,
    [Gen_Bus_Posting_Group]          NVARCHAR (MAX)   NULL,
    [Gen_Prod_Posting_Group]         NVARCHAR (MAX)   NULL,
    [VAT_Bus_Posting_Group]          NVARCHAR (MAX)   NULL,
    [VAT_Prod_Posting_Group]         NVARCHAR (MAX)   NULL,
    [Debit_Amount]                   DECIMAL (38, 18) NULL,
    [Credit_Amount]                  DECIMAL (38, 18) NULL,
    [Balance_at_Date]                DECIMAL (38, 18) NULL,
    [Additional_Currency_Net_Change] DECIMAL (38, 18) NULL,
    [Add_Currency_Balance_at_Date]   DECIMAL (38, 18) NULL,
    [Additional_Currency_Balance]    DECIMAL (38, 18) NULL,
    [Consol_Debit_Acc]               NVARCHAR (MAX)   NULL,
    [Consol_Credit_Acc]              NVARCHAR (MAX)   NULL,
    [Source_Currency_Posting]        NVARCHAR (MAX)   NULL,
    [Source_Currency_Code]           NVARCHAR (MAX)   NULL,
    [Source_Currency_Balance]        DECIMAL (38, 18) NULL,
    [Source_Curr_Balance_at_Date]    DECIMAL (38, 18) NULL,
    [Cost_Type_No]                   NVARCHAR (MAX)   NULL,
    [Consol_Translation_Method]      NVARCHAR (MAX)   NULL,
    [Default_IC_Partner_G_L_Acc_No]  NVARCHAR (MAX)   NULL,
    [Default_Deferral_Template_Code] NVARCHAR (MAX)   NULL,
    [No_2]                           NVARCHAR (MAX)   NULL,
    [Business_Unit_Filter]           NVARCHAR (MAX)   NULL,
    [Global_Dimension_1_Filter]      NVARCHAR (MAX)   NULL,
    [Global_Dimension_2_Filter]      NVARCHAR (MAX)   NULL,
    [Date_Filter]                    NVARCHAR (MAX)   NULL,
    [VAT_Reporting_Date_Filter]      NVARCHAR (MAX)   NULL,
    [Dimension_Set_ID_Filter]        NVARCHAR (MAX)   NULL,
    [CompanyID]                      NVARCHAR (MAX)   NULL
);


GO

