CREATE TABLE [fct].[testLookup] (
    [CompanyID]                     INT             NULL,
    [BK_Department]                 NVARCHAR (MAX)  NULL,
    [timestamp]                     VARBINARY (MAX) NULL,
    [BK_Customer]                   NVARCHAR (MAX)  NULL,
    [BK_PostCode]                   NVARCHAR (MAX)  NULL,
    [BK_Customer_Geography_Country] NVARCHAR (MAX)  NULL,
    [BK_Item]                       NVARCHAR (MAX)  NULL,
    [BK_SalesOrder]                 NVARCHAR (MAX)  NULL,
    [BK_Date_Intake]                DATETIME2 (7)   NULL,
    [BK_SalesPerson]                NVARCHAR (MAX)  NULL,
    [BK_Currency_Document]          NVARCHAR (MAX)  NULL,
    [BK_Currency_Company]           NVARCHAR (MAX)  NULL,
    [BK_Currency_ExchangeRate]      NVARCHAR (MAX)  NULL,
    [BK_Date_Posting]               DATE            NULL,
    [BKFinaceVoucherPostingDate]    DATE            NULL,
    [BK_Date_ExchangeRate]          DATETIME2 (7)   NULL,
    [NK_DocumentNumber]             NVARCHAR (MAX)  NULL,
    [NK_DocumentLineNumber]         INT             NULL,
    [BK_FinanceAccount]             NVARCHAR (MAX)  NULL,
    [BK_FinanceVoucherDocumentType] NVARCHAR (MAX)  NULL,
    [BK_FinanceVoucherSourceCode]   NVARCHAR (MAX)  NULL,
    [BK_DeliveryMethod]             NVARCHAR (MAX)  NULL,
    [BK_Location]                   NVARCHAR (MAX)  NULL,
    [BK_GenBusPostingGroup]         NVARCHAR (MAX)  NULL,
    [BK_GenProdPostingGroup]        NVARCHAR (MAX)  NULL,
    [BK_ReturnReasonCode]           NVARCHAR (MAX)  NULL,
    [BK_ShipmentMethodCode]         NVARCHAR (MAX)  NULL,
    [BK_ChainCode]                  NVARCHAR (MAX)  NULL,
    [M_Quantity]                    DECIMAL (18, 4) NULL,
    [M_UnitCost]                    DECIMAL (18, 4) NULL,
    [M_UnitCost_LCY]                DECIMAL (18, 4) NULL,
    [M_Amount]                      DECIMAL (18, 4) NULL,
    [M_COGS]                        DECIMAL (18, 4) NULL,
    [M_GM]                          DECIMAL (18, 4) NULL,
    [M_Amount_LCY]                  DECIMAL (18, 4) NULL,
    [M_COGS_LCY]                    DECIMAL (18, 4) NULL,
    [M_GM_LCY]                      DECIMAL (18, 4) NULL,
    [M_CurrencyFactor]              DECIMAL (18, 6) NULL,
    [ADF_FactSource]                NVARCHAR (MAX)  NULL,
    [UpdatedRow]                    INT             NULL,
    [CustomerKey]                   INT             NULL,
    [CustomerCompanyID]             INT             NULL,
    [CustomerNo]                    NVARCHAR (MAX)  NULL
);


GO

