CREATE   VIEW [pbi].[DimPostingDate]
AS
SELECT [DateKey] AS [PostingDateKey]
      ,[Date] AS [Posting Date]
      ,[Year] AS [Posting Year]
      ,[Monthnumber] AS [Posting Monthnumber]
      ,[YearMonthnumber] AS [Posting Year Monthnumber]
      ,[YearMonthShort] AS [Posting Year MonthS hort]
      ,[MonthNameShort] AS [Posting Month Name Short]
      ,[MonthNameLong] AS [Posting Month Name Long]
      ,[DayOfWeekNumber] AS [Posting Day Of Week Number]
      ,[DayOfWeek] AS [Posting Day Of Week]
      ,[DayOfWeekShort] AS [Posting Day Of Week Short]
      ,[Week] AS [Posting Week]
      ,[LastDateOfWeekUS] AS [Posting Last Date Of Week US]
      ,[Quarter] AS [Posting Quarter]
      ,[YearQuarter] AS [Posting Year Quarter]
      ,[YearWeek] AS [Posting Year Week]
      ,[WeekNo] AS [Posting Week No]
      ,[YYMM] AS [Posting YYMM]
      ,[BudgetMD] AS [Posting Budget MD]
      ,[EO-MONTH] AS [Posting EO-MONTH]
      ,[DurationYear] AS [Posting Duration Year]
      ,[DurationDays] AS [Posting Duration Days]
      ,[DurationWeek] AS [Posting Duration Week]
      ,[DurationMonth] AS [Posting Duration Month]
      ,[DurationQuarter] AS [Posting Duration Quarter]
      ,[CurrentDay] AS [Posting Current Day]
      ,[Yesterday] AS [Posting Yesterday]
      ,[CurrentYear] AS [Posting Current Year]
      ,[CurrentQuarter] AS [Posting Current Quarter]
      ,[CurrentMonth] AS [Posting Current Month]
      ,[CurrentWeek] AS [Posting Current Week]
      ,[FutureDate] AS [Posting Future Date]
FROM [dim].[Date];

GO

