CREATE TABLE [dim_v1].[Customer] (
    [CustomerKey]                        INT              NOT NULL,
    [CustomerCompanyID]                  INT              NOT NULL,
    [timestamp]                          VARBINARY (8)    NOT NULL,
    [CustomerNo]                         NVARCHAR (20)    NOT NULL,
    [CustomerName]                       NVARCHAR (100)   NOT NULL,
    [CustomerNoName]                     NVARCHAR (125)   NULL,
    [CustomerSearchName]                 NVARCHAR (100)   NOT NULL,
    [CustomerName2]                      NVARCHAR (50)    NOT NULL,
    [CustomerAddress]                    NVARCHAR (100)   NOT NULL,
    [CustomerAddress2]                   NVARCHAR (50)    NOT NULL,
    [CustomerCity]                       NVARCHAR (30)    NOT NULL,
    [CustomerContact]                    NVARCHAR (100)   NOT NULL,
    [CustomerPhoneNo]                    NVARCHAR (30)    NOT NULL,
    [CustomerTelexNo]                    NVARCHAR (20)    NOT NULL,
    [CustomerDocumentSendingProfile]     NVARCHAR (20)    NOT NULL,
    [CustomerShip-toCode]                NVARCHAR (10)    NOT NULL,
    [CustomerOurAccountNo]               NVARCHAR (20)    NOT NULL,
    [CustomerTerritoryCode]              NVARCHAR (10)    NOT NULL,
    [CustomerGlobalDimension1Code]       NVARCHAR (20)    NOT NULL,
    [CustomerGlobalDimension2Code]       NVARCHAR (20)    NOT NULL,
    [CustomerChainCode]                  NVARCHAR (20)    NOT NULL,
    [CustomerChainName]                  NVARCHAR (50)    NOT NULL,
    [CustomerChainGroupCode]             NVARCHAR (20)    NOT NULL,
    [CustomerChainGroupName]             NVARCHAR (50)    NOT NULL,
    [CustomerBudgetedAmount]             DECIMAL (38, 20) NOT NULL,
    [CustomerCreditLimit(LCY)]           DECIMAL (38, 20) NOT NULL,
    [CustomerCustomerPostingGroup]       NVARCHAR (20)    NOT NULL,
    [CustomerCurrencyCode]               NVARCHAR (10)    NOT NULL,
    [CustomerCustomerPriceGroup]         NVARCHAR (10)    NOT NULL,
    [CustomerLanguageCode]               NVARCHAR (10)    NOT NULL,
    [CustomerStatisticsGroup]            INT              NOT NULL,
    [CustomerPaymentTermsCode]           NVARCHAR (10)    NOT NULL,
    [CustomerFinChargeTermsCode]         NVARCHAR (10)    NOT NULL,
    [CustomerTeamCodeName]               NVARCHAR (125)   NOT NULL,
    [CustomerTeamPersonCodeName]         NVARCHAR (125)   NOT NULL,
    [CustomerSalespersonCode]            NVARCHAR (20)    NOT NULL,
    [CustomerShipmentMethodCode]         NVARCHAR (10)    NOT NULL,
    [CustomerShippingAgentCode]          NVARCHAR (10)    NOT NULL,
    [CustomerPlaceofExport]              NVARCHAR (20)    NOT NULL,
    [CustomerInvoiceDiscCode]            NVARCHAR (20)    NOT NULL,
    [CustomerCustomerDiscGroup]          NVARCHAR (20)    NOT NULL,
    [CustomerCountryRegionCode]          NVARCHAR (10)    NOT NULL,
    [CustomerCollectionMethod]           NVARCHAR (20)    NOT NULL,
    [CustomerAmount]                     DECIMAL (38, 20) NOT NULL,
    [CustomerBlocked]                    NVARCHAR (15)    NOT NULL,
    [CustomerInvoiceCopies]              INT              NOT NULL,
    [CustomerLastStatementNo]            INT              NOT NULL,
    [CustomerPrintStatements]            TINYINT          NOT NULL,
    [CustomerBill-toCustomerNo]          NVARCHAR (20)    NOT NULL,
    [CustomerPriority]                   INT              NOT NULL,
    [CustomerPaymentMethodCode]          NVARCHAR (10)    NOT NULL,
    [CustomerLastModifiedDateTime]       DATETIME         NOT NULL,
    [CustomerLastDateModified]           DATETIME         NOT NULL,
    [CustomerApplicationMethod]          INT              NOT NULL,
    [CustomerPricesIncludingVAT]         TINYINT          NOT NULL,
    [CustomerLocationCode]               NVARCHAR (10)    NOT NULL,
    [CustomerFaxNo]                      NVARCHAR (30)    NOT NULL,
    [CustomerTelexAnswerBack]            NVARCHAR (20)    NOT NULL,
    [CustomerVATRegistrationNo]          NVARCHAR (20)    NOT NULL,
    [CustomerCombineShipments]           TINYINT          NOT NULL,
    [CustomerGenBusPostingGroup]         NVARCHAR (20)    NOT NULL,
    [CustomerPicture]                    VARBINARY (MAX)  NULL,
    [CustomerGLN]                        NVARCHAR (13)    NOT NULL,
    [CustomerPostCode]                   NVARCHAR (20)    NOT NULL,
    [CustomerCounty]                     NVARCHAR (30)    NOT NULL,
    [CustomerEORINumber]                 NVARCHAR (40)    NOT NULL,
    [CustomerUseGLNinElectronicDocument] TINYINT          NOT NULL,
    [CustomerE-Mail]                     NVARCHAR (80)    NOT NULL,
    [CustomerHomePage]                   NVARCHAR (80)    NOT NULL,
    [CustomerReminderTermsCode]          NVARCHAR (10)    NOT NULL,
    [CustomerNoSeries]                   NVARCHAR (20)    NOT NULL,
    [CustomerTaxAreaCode]                NVARCHAR (20)    NOT NULL,
    [CustomerTaxLiable]                  TINYINT          NOT NULL,
    [CustomerVATBusPostingGroup]         NVARCHAR (20)    NOT NULL,
    [CustomerReserve]                    INT              NOT NULL,
    [CustomerBlockPaymentTolerance]      TINYINT          NOT NULL,
    [CustomerICPartnerCode]              NVARCHAR (20)    NOT NULL,
    [CustomerPrepayment]                 DECIMAL (38, 20) NOT NULL,
    [CustomerPartnerType]                INT              NOT NULL,
    [CustomerImage]                      NVARCHAR (36)    NOT NULL,
    [CustomerPrivacyBlocked]             TINYINT          NOT NULL,
    [CustomerDisableSearchbyName]        TINYINT          NOT NULL,
    [CustomerPreferredBankAccountCode]   NVARCHAR (20)    NOT NULL,
    [CustomerCashFlowPaymentTermsCode]   NVARCHAR (10)    NOT NULL,
    [CustomerPrimaryContactNo]           NVARCHAR (20)    NOT NULL,
    [CustomerContactType]                INT              NOT NULL,
    [CustomerMobilePhoneNo]              NVARCHAR (30)    NOT NULL,
    [CustomerResponsibilityCenter]       NVARCHAR (10)    NOT NULL,
    [CustomerShippingAdvice]             INT              NOT NULL,
    [CustomerShippingTime]               VARCHAR (32)     NOT NULL,
    [CustomerShippingAgentServiceCode]   NVARCHAR (10)    NOT NULL,
    [CustomerServiceZoneCode]            NVARCHAR (10)    NOT NULL,
    [CustomerPriceCalculationMethod]     INT              NOT NULL,
    [CustomerAllowLineDisc]              TINYINT          NOT NULL,
    [CustomerBaseCalendarCode]           NVARCHAR (10)    NOT NULL,
    [CustomerCopySell-toAddrtoQteFrom]   INT              NOT NULL,
    [CustomerValidateEUVatRegNo]         TINYINT          NOT NULL,
    [CustomerEANNo]                      NVARCHAR (13)    NOT NULL,
    [CustomerAccountCode]                NVARCHAR (30)    NOT NULL,
    [CustomerOIOUBLProfileCode]          NVARCHAR (10)    NOT NULL,
    [CustomerOIOUBLProfileCodeRequired]  TINYINT          NOT NULL,
    [CustomerPriorityNOTO]               INT              NULL,
    [CustomerDelSOsWithRemQtyNOTO]       TINYINT          NOT NULL,
    [CustomerUseBarcode]                 TINYINT          NOT NULL,
    [CustomerOldCustomerNo]              NVARCHAR (20)    NOT NULL,
    [CustomerCalculateFreight]           TINYINT          NOT NULL,
    [CustomerBatchPosting]               TINYINT          NOT NULL,
    [CustomerHashKey]                    NVARCHAR (200)   NULL,
    [ADF_BatchId_Insert]                 BIGINT           CONSTRAINT [DF_dim_Customer_InsertBacthId] DEFAULT ((0)) NOT NULL,
    [ADF_BatchId_Update]                 BIGINT           CONSTRAINT [DF_dim_Customer_UpdateBacthId] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dim_Customer] PRIMARY KEY CLUSTERED ([CustomerKey] ASC),
    CONSTRAINT [UQ_dim_Customer] UNIQUE NONCLUSTERED ([CustomerCompanyID] ASC, [CustomerNo] ASC)
);


GO

