/* This file was generated automatically by a T4 Template */

CREATE PROCEDURE [dim_v1].[InsertUnknownEntitiesItem]
AS
BEGIN
    SET NOCOUNT ON;
 
    BEGIN TRY
    -- Get the current transaction count
    DECLARE @TranCounter INT = @@TRANCOUNT
		,@SavePoint NVARCHAR(32) = CAST(@@PROCID AS NVARCHAR(20)) + N'_' + CAST(@@NESTLEVEL AS NVARCHAR(2));

    -- Decide to join existing transaction or start new
    IF @TranCounter > 0
      SAVE TRANSACTION @SavePoint;
    ELSE
      BEGIN TRANSACTION;

    
	 
	MERGE [dim_v1].[Item] AS d
    USING (
			SELECT -1 AS [ItemKey]
			, -1 AS [ItemCompanyID]
			, 0x AS [timestamp]
			, 'Unknown' AS [ItemNo]
			, 'Unknown' AS [ItemNo2]
			, 'Unknown' AS [ItemDescription]
			, 'Unknown' AS [ItemSearchDescription]
			, 'Unknown' AS [ItemDescription2]
			, 'Unknown' AS [ItemBaseUnitofMeasure]
			, -1 AS [ItemPriceUnitConversion]
			, -1 AS [ItemType]
			, 'Unknown' AS [ItemInventoryPostingGroup]
			, 'Unknown' AS [ItemShelfNo]
			, 'Unknown' AS [ItemItemDiscGroup]
			, 0 AS [ItemAllowInvoiceDisc]
			, -1 AS [ItemStatisticsGroup]
			, -1 AS [ItemCommissionGroup]
			, -1 AS [ItemUnitPrice]
			, -1 AS [ItemPriceProfitCalculation]
			, -1 AS [ItemProfit]
			, -1 AS [ItemCostingMethod]
			, -1 AS [ItemUnitCost]
			, -1 AS [ItemStandardCost]
			, -1 AS [ItemLastDirectCost]
			, -1 AS [ItemIndirectCost]
			, 0 AS [ItemCostisAdjusted]
			, 0 AS [ItemAllowOnlineAdjustment]
			, 'Unknown' AS [ItemVendorNo]
			, 'Unknown' AS [ItemVendorItemNo]
			, 'Unknown' AS [ItemLeadTimeCalculation]
			, -1 AS [ItemReorderPoint]
			, -1 AS [ItemMaximumInventory]
			, -1 AS [ItemReorderQuantity]
			, 'Unknown' AS [ItemAlternativeItemNo]
			, -1 AS [ItemUnitListPrice]
			, -1 AS [ItemDutyDue]
			, 'Unknown' AS [ItemDutyCode]
			, -1 AS [ItemGrossWeight]
			, -1 AS [ItemNetWeight]
			, -1 AS [ItemUnitsperParcel]
			, -1 AS [ItemUnitVolume]
			, 'Unknown' AS [ItemDurability]
			, 'Unknown' AS [ItemFreightType]
			, 'Unknown' AS [ItemTariffNo]
			, -1 AS [ItemDutyUnitConversion]
			, 'Unknown' AS [ItemCountryRegionPurchasedCode]
			, -1 AS [ItemBudgetQuantity]
			, -1 AS [ItemBudgetedAmount]
			, -1 AS [ItemBudgetProfit]
			, 0 AS [ItemBlocked]
			, 'Unknown' AS [ItemBlockReason]
			, '1900-01-01' AS [ItemLastDateTimeModified]
			, '1900-01-01' AS [ItemLastDateModified]
			, '1900-01-01' AS [ItemLastTimeModified]
			, 0 AS [ItemPriceIncludesVAT]
			, 'Unknown' AS [ItemVATBusPostingGr(Price)]
			, 'Unknown' AS [ItemGenProdPostingGroup]
			, 0x AS [ItemPicture]
			, 'Unknown' AS [ItemCountryRegionofOriginCode]
			, 0 AS [ItemAutomaticExtTexts]
			, 'Unknown' AS [ItemNoSeries]
			, 'Unknown' AS [ItemTaxGroupCode]
			, 'Unknown' AS [ItemVATProdPostingGroup]
			, -1 AS [ItemReserve]
			, 'Unknown' AS [ItemGlobalDimension1Code]
			, 'Unknown' AS [ItemGlobalDimension2Code]
			, -1 AS [ItemStockoutWarning]
			, -1 AS [ItemPreventNegativeInventory]
			, 'Unknown' AS [ItemApplicationWkshUserID]
			, -1 AS [ItemAssemblyPolicy]
			, 'Unknown' AS [ItemGTIN]
			, 'Unknown' AS [ItemDefaultDeferralTemplateCode]
			, -1 AS [ItemLow-LevelCode]
			, -1 AS [ItemLotSize]
			, 'Unknown' AS [ItemSerialNos]
			, '1900-01-01' AS [ItemLastUnitCostCalcDate]
			, -1 AS [ItemRolled-upMaterialCost]
			, -1 AS [ItemRolled-upCapacityCost]
			, -1 AS [ItemScrap]
			, 0 AS [ItemInventoryValueZero]
			, -1 AS [ItemDiscreteOrderQuantity]
			, -1 AS [ItemMinimumOrderQuantity]
			, -1 AS [ItemMaximumOrderQuantity]
			, -1 AS [ItemSafetyStockQuantity]
			, -1 AS [ItemOrderMultiple]
			, 'Unknown' AS [ItemSafetyLeadTime]
			, -1 AS [ItemFlushingMethod]
			, -1 AS [ItemReplenishmentSystem]
			, -1 AS [ItemRoundingPrecision]
			, 'Unknown' AS [ItemSalesUnitofMeasure]
			, 'Unknown' AS [ItemPurchUnitofMeasure]
			, 'Unknown' AS [ItemTimeBucket]
			, -1 AS [ItemReorderingPolicy]
			, 0 AS [ItemIncludeInventory]
			, -1 AS [ItemManufacturingPolicy]
			, 'Unknown' AS [ItemReschedulingPeriod]
			, 'Unknown' AS [ItemLotAccumulationPeriod]
			, 'Unknown' AS [ItemDampenerPeriod]
			, -1 AS [ItemDampenerQuantity]
			, -1 AS [ItemOverflowLevel]
			, 'Unknown' AS [ItemManufacturerCode]
			, 'Unknown' AS [ItemItemCategoryCode]
			, 0 AS [ItemCreatedFromNonstockItem]
			, 'Unknown' AS [ItemProductGroupCode]
			, 'Unknown' AS [ItemPurchasingCode]
			, 'Unknown' AS [ItemServiceItemGroup]
			, 'Unknown' AS [ItemItemTrackingCode]
			, 'Unknown' AS [ItemLotNos]
			, 'Unknown' AS [ItemExpirationCalculation]
			, 'Unknown' AS [ItemWarehouseClassCode]
			, 'Unknown' AS [ItemSpecialEquipmentCode]
			, 'Unknown' AS [ItemPut-awayTemplateCode]
			, 'Unknown' AS [ItemPut-awayUnitofMeasureCode]
			, 'Unknown' AS [ItemPhysInvtCountingPeriodCode]
			, '1900-01-01' AS [ItemLastCountingPeriodUpdate]
			, 0 AS [ItemUseCross-Docking]
			, '1900-01-01' AS [ItemNextCountingStartDate]
			, '1900-01-01' AS [ItemNextCountingEndDate]
			, 0 AS [ItemSalesBlocked]
			, 0 AS [ItemPurchasingBlocked]
			, 'Unknown' AS [ItemItemCategoryId]
			, 'Unknown' AS [ItemOver-ReceiptCode]
			, 'Unknown' AS [ItemRoutingNo]
			, 'Unknown' AS [ItemProductionBOMNo]
			, -1 AS [ItemSingle-LevelMaterialCost]
			, -1 AS [ItemSingle-LevelCapacityCost]
			, -1 AS [ItemSingle-LevelSubcontrdCost]
			, -1 AS [ItemSingle-LevelCapOvhdCost]
			, -1 AS [ItemSingle-LevelMfgOvhdCost]
			, -1 AS [ItemOverheadRate]
			, -1 AS [ItemRolled-upSubcontractedCost]
			, -1 AS [ItemRolled-upMfgOvhdCost]
			, -1 AS [ItemRolled-upCapOverheadCost]
			, -1 AS [ItemOrderTrackingPolicy]
			, 0 AS [ItemCritical]
			, 'Unknown' AS [ItemCommonItemNo]
			, 'Unknown' AS [ItemLabelBarcode]
			, 'Unknown' AS [ItemABCDCategory]
			, 'Unknown' AS [ItemBrand]
			, 'Unknown' AS [ItemProductLineCode]
			, 'Unknown' AS [ItemProductUsage]
			, 'Unknown' AS [ItemProdGroupCode]
			, 'Unknown' AS [ItemSize]
			, 'Unknown' AS [ItemSizeUnit]
			, 'Unknown' AS [ItemFeature]
			, 'Unknown' AS [ItemPackingMethod]
			, 'Unknown' AS [ItemCoating]
			, -1 AS [ItemQuality]
			, 0 AS [ItemWithLid]
			, -1 AS [ItemWeightClassificationNOTO]
			, -1 AS [ItemCalculatedAvailableNOTO]
			, -1 AS [ItemCalculatedAvailableExtNOTO]
			, '1900-01-01' AS [ItemCalculatedAvailableDateNOTO]
			, 'Unknown' AS [ItemBodyType]
			, -1 AS [ItemBOMQuantity]
			, 'Unknown' AS [ItemHashKey]
			, -1 AS [ADF_BatchId_Insert]
			, -1 AS [ADF_BatchId_Update]
			
			UNION ALL

			SELECT -2 AS [ItemKey]
			, -2 AS [ItemCompanyID]
			, 0x AS [timestamp]
			, 'Blank' AS [ItemNo]
			, 'Blank' AS [ItemNo2]
			, 'Blank' AS [ItemDescription]
			, 'Blank' AS [ItemSearchDescription]
			, 'Blank' AS [ItemDescription2]
			, 'Blank' AS [ItemBaseUnitofMeasure]
			, -2 AS [ItemPriceUnitConversion]
			, -2 AS [ItemType]
			, 'Blank' AS [ItemInventoryPostingGroup]
			, 'Blank' AS [ItemShelfNo]
			, 'Blank' AS [ItemItemDiscGroup]
			, 0 AS [ItemAllowInvoiceDisc]
			, -2 AS [ItemStatisticsGroup]
			, -2 AS [ItemCommissionGroup]
			, -2 AS [ItemUnitPrice]
			, -2 AS [ItemPriceProfitCalculation]
			, -2 AS [ItemProfit]
			, -2 AS [ItemCostingMethod]
			, -2 AS [ItemUnitCost]
			, -2 AS [ItemStandardCost]
			, -2 AS [ItemLastDirectCost]
			, -2 AS [ItemIndirectCost]
			, 0 AS [ItemCostisAdjusted]
			, 0 AS [ItemAllowOnlineAdjustment]
			, 'Blank' AS [ItemVendorNo]
			, 'Blank' AS [ItemVendorItemNo]
			, 'Blank' AS [ItemLeadTimeCalculation]
			, -2 AS [ItemReorderPoint]
			, -2 AS [ItemMaximumInventory]
			, -2 AS [ItemReorderQuantity]
			, 'Blank' AS [ItemAlternativeItemNo]
			, -2 AS [ItemUnitListPrice]
			, -2 AS [ItemDutyDue]
			, 'Blank' AS [ItemDutyCode]
			, -2 AS [ItemGrossWeight]
			, -2 AS [ItemNetWeight]
			, -2 AS [ItemUnitsperParcel]
			, -2 AS [ItemUnitVolume]
			, 'Blank' AS [ItemDurability]
			, 'Blank' AS [ItemFreightType]
			, 'Blank' AS [ItemTariffNo]
			, -2 AS [ItemDutyUnitConversion]
			, 'Blank' AS [ItemCountryRegionPurchasedCode]
			, -2 AS [ItemBudgetQuantity]
			, -2 AS [ItemBudgetedAmount]
			, -2 AS [ItemBudgetProfit]
			, 0 AS [ItemBlocked]
			, 'Blank' AS [ItemBlockReason]
			, '1900-01-01' AS [ItemLastDateTimeModified]
			, '1900-01-01' AS [ItemLastDateModified]
			, '1900-01-01' AS [ItemLastTimeModified]
			, 0 AS [ItemPriceIncludesVAT]
			, 'Blank' AS [ItemVATBusPostingGr(Price)]
			, 'Blank' AS [ItemGenProdPostingGroup]
			, 0x AS [ItemPicture]
			, 'Blank' AS [ItemCountryRegionofOriginCode]
			, 0 AS [ItemAutomaticExtTexts]
			, 'Blank' AS [ItemNoSeries]
			, 'Blank' AS [ItemTaxGroupCode]
			, 'Blank' AS [ItemVATProdPostingGroup]
			, -2 AS [ItemReserve]
			, 'Blank' AS [ItemGlobalDimension1Code]
			, 'Blank' AS [ItemGlobalDimension2Code]
			, -2 AS [ItemStockoutWarning]
			, -2 AS [ItemPreventNegativeInventory]
			, 'Blank' AS [ItemApplicationWkshUserID]
			, -2 AS [ItemAssemblyPolicy]
			, 'Blank' AS [ItemGTIN]
			, 'Blank' AS [ItemDefaultDeferralTemplateCode]
			, -2 AS [ItemLow-LevelCode]
			, -2 AS [ItemLotSize]
			, 'Blank' AS [ItemSerialNos]
			, '1900-01-01' AS [ItemLastUnitCostCalcDate]
			, -2 AS [ItemRolled-upMaterialCost]
			, -2 AS [ItemRolled-upCapacityCost]
			, -2 AS [ItemScrap]
			, 0 AS [ItemInventoryValueZero]
			, -2 AS [ItemDiscreteOrderQuantity]
			, -2 AS [ItemMinimumOrderQuantity]
			, -2 AS [ItemMaximumOrderQuantity]
			, -2 AS [ItemSafetyStockQuantity]
			, -2 AS [ItemOrderMultiple]
			, 'Blank' AS [ItemSafetyLeadTime]
			, -2 AS [ItemFlushingMethod]
			, -2 AS [ItemReplenishmentSystem]
			, -2 AS [ItemRoundingPrecision]
			, 'Blank' AS [ItemSalesUnitofMeasure]
			, 'Blank' AS [ItemPurchUnitofMeasure]
			, 'Blank' AS [ItemTimeBucket]
			, -2 AS [ItemReorderingPolicy]
			, 0 AS [ItemIncludeInventory]
			, -2 AS [ItemManufacturingPolicy]
			, 'Blank' AS [ItemReschedulingPeriod]
			, 'Blank' AS [ItemLotAccumulationPeriod]
			, 'Blank' AS [ItemDampenerPeriod]
			, -2 AS [ItemDampenerQuantity]
			, -2 AS [ItemOverflowLevel]
			, 'Blank' AS [ItemManufacturerCode]
			, 'Blank' AS [ItemItemCategoryCode]
			, 0 AS [ItemCreatedFromNonstockItem]
			, 'Blank' AS [ItemProductGroupCode]
			, 'Blank' AS [ItemPurchasingCode]
			, 'Blank' AS [ItemServiceItemGroup]
			, 'Blank' AS [ItemItemTrackingCode]
			, 'Blank' AS [ItemLotNos]
			, 'Blank' AS [ItemExpirationCalculation]
			, 'Blank' AS [ItemWarehouseClassCode]
			, 'Blank' AS [ItemSpecialEquipmentCode]
			, 'Blank' AS [ItemPut-awayTemplateCode]
			, 'Blank' AS [ItemPut-awayUnitofMeasureCode]
			, 'Blank' AS [ItemPhysInvtCountingPeriodCode]
			, '1900-01-01' AS [ItemLastCountingPeriodUpdate]
			, 0 AS [ItemUseCross-Docking]
			, '1900-01-01' AS [ItemNextCountingStartDate]
			, '1900-01-01' AS [ItemNextCountingEndDate]
			, 0 AS [ItemSalesBlocked]
			, 0 AS [ItemPurchasingBlocked]
			, 'Blank' AS [ItemItemCategoryId]
			, 'Blank' AS [ItemOver-ReceiptCode]
			, 'Blank' AS [ItemRoutingNo]
			, 'Blank' AS [ItemProductionBOMNo]
			, -2 AS [ItemSingle-LevelMaterialCost]
			, -2 AS [ItemSingle-LevelCapacityCost]
			, -2 AS [ItemSingle-LevelSubcontrdCost]
			, -2 AS [ItemSingle-LevelCapOvhdCost]
			, -2 AS [ItemSingle-LevelMfgOvhdCost]
			, -2 AS [ItemOverheadRate]
			, -2 AS [ItemRolled-upSubcontractedCost]
			, -2 AS [ItemRolled-upMfgOvhdCost]
			, -2 AS [ItemRolled-upCapOverheadCost]
			, -2 AS [ItemOrderTrackingPolicy]
			, 0 AS [ItemCritical]
			, 'Blank' AS [ItemCommonItemNo]
			, 'Blank' AS [ItemLabelBarcode]
			, 'Blank' AS [ItemABCDCategory]
			, 'Blank' AS [ItemBrand]
			, 'Blank' AS [ItemProductLineCode]
			, 'Blank' AS [ItemProductUsage]
			, 'Blank' AS [ItemProdGroupCode]
			, 'Blank' AS [ItemSize]
			, 'Blank' AS [ItemSizeUnit]
			, 'Blank' AS [ItemFeature]
			, 'Blank' AS [ItemPackingMethod]
			, 'Blank' AS [ItemCoating]
			, -2 AS [ItemQuality]
			, 0 AS [ItemWithLid]
			, -2 AS [ItemWeightClassificationNOTO]
			, -2 AS [ItemCalculatedAvailableNOTO]
			, -2 AS [ItemCalculatedAvailableExtNOTO]
			, '1900-01-01' AS [ItemCalculatedAvailableDateNOTO]
			, 'Blank' AS [ItemBodyType]
			, -2 AS [ItemBOMQuantity]
			, 'Blank' AS [ItemHashKey]
			, -2 AS [ADF_BatchId_Insert]
			, -2 AS [ADF_BatchId_Update]
			
		  ) s
	ON s.[ItemKey] = d.[ItemKey]
	
	WHEN NOT MATCHED THEN -- Insert new records
    INSERT ([ItemKey]
	, [ItemCompanyID]
	, [timestamp]
	, [ItemNo]
	, [ItemNo2]
	, [ItemDescription]
	, [ItemSearchDescription]
	, [ItemDescription2]
	, [ItemBaseUnitofMeasure]
	, [ItemPriceUnitConversion]
	, [ItemType]
	, [ItemInventoryPostingGroup]
	, [ItemShelfNo]
	, [ItemItemDiscGroup]
	, [ItemAllowInvoiceDisc]
	, [ItemStatisticsGroup]
	, [ItemCommissionGroup]
	, [ItemUnitPrice]
	, [ItemPriceProfitCalculation]
	, [ItemProfit]
	, [ItemCostingMethod]
	, [ItemUnitCost]
	, [ItemStandardCost]
	, [ItemLastDirectCost]
	, [ItemIndirectCost]
	, [ItemCostisAdjusted]
	, [ItemAllowOnlineAdjustment]
	, [ItemVendorNo]
	, [ItemVendorItemNo]
	, [ItemLeadTimeCalculation]
	, [ItemReorderPoint]
	, [ItemMaximumInventory]
	, [ItemReorderQuantity]
	, [ItemAlternativeItemNo]
	, [ItemUnitListPrice]
	, [ItemDutyDue]
	, [ItemDutyCode]
	, [ItemGrossWeight]
	, [ItemNetWeight]
	, [ItemUnitsperParcel]
	, [ItemUnitVolume]
	, [ItemDurability]
	, [ItemFreightType]
	, [ItemTariffNo]
	, [ItemDutyUnitConversion]
	, [ItemCountryRegionPurchasedCode]
	, [ItemBudgetQuantity]
	, [ItemBudgetedAmount]
	, [ItemBudgetProfit]
	, [ItemBlocked]
	, [ItemBlockReason]
	, [ItemLastDateTimeModified]
	, [ItemLastDateModified]
	, [ItemLastTimeModified]
	, [ItemPriceIncludesVAT]
	, [ItemVATBusPostingGr(Price)]
	, [ItemGenProdPostingGroup]
	, [ItemPicture]
	, [ItemCountryRegionofOriginCode]
	, [ItemAutomaticExtTexts]
	, [ItemNoSeries]
	, [ItemTaxGroupCode]
	, [ItemVATProdPostingGroup]
	, [ItemReserve]
	, [ItemGlobalDimension1Code]
	, [ItemGlobalDimension2Code]
	, [ItemStockoutWarning]
	, [ItemPreventNegativeInventory]
	, [ItemApplicationWkshUserID]
	, [ItemAssemblyPolicy]
	, [ItemGTIN]
	, [ItemDefaultDeferralTemplateCode]
	, [ItemLow-LevelCode]
	, [ItemLotSize]
	, [ItemSerialNos]
	, [ItemLastUnitCostCalcDate]
	, [ItemRolled-upMaterialCost]
	, [ItemRolled-upCapacityCost]
	, [ItemScrap]
	, [ItemInventoryValueZero]
	, [ItemDiscreteOrderQuantity]
	, [ItemMinimumOrderQuantity]
	, [ItemMaximumOrderQuantity]
	, [ItemSafetyStockQuantity]
	, [ItemOrderMultiple]
	, [ItemSafetyLeadTime]
	, [ItemFlushingMethod]
	, [ItemReplenishmentSystem]
	, [ItemRoundingPrecision]
	, [ItemSalesUnitofMeasure]
	, [ItemPurchUnitofMeasure]
	, [ItemTimeBucket]
	, [ItemReorderingPolicy]
	, [ItemIncludeInventory]
	, [ItemManufacturingPolicy]
	, [ItemReschedulingPeriod]
	, [ItemLotAccumulationPeriod]
	, [ItemDampenerPeriod]
	, [ItemDampenerQuantity]
	, [ItemOverflowLevel]
	, [ItemManufacturerCode]
	, [ItemItemCategoryCode]
	, [ItemCreatedFromNonstockItem]
	, [ItemProductGroupCode]
	, [ItemPurchasingCode]
	, [ItemServiceItemGroup]
	, [ItemItemTrackingCode]
	, [ItemLotNos]
	, [ItemExpirationCalculation]
	, [ItemWarehouseClassCode]
	, [ItemSpecialEquipmentCode]
	, [ItemPut-awayTemplateCode]
	, [ItemPut-awayUnitofMeasureCode]
	, [ItemPhysInvtCountingPeriodCode]
	, [ItemLastCountingPeriodUpdate]
	, [ItemUseCross-Docking]
	, [ItemNextCountingStartDate]
	, [ItemNextCountingEndDate]
	, [ItemSalesBlocked]
	, [ItemPurchasingBlocked]
	, [ItemItemCategoryId]
	, [ItemOver-ReceiptCode]
	, [ItemRoutingNo]
	, [ItemProductionBOMNo]
	, [ItemSingle-LevelMaterialCost]
	, [ItemSingle-LevelCapacityCost]
	, [ItemSingle-LevelSubcontrdCost]
	, [ItemSingle-LevelCapOvhdCost]
	, [ItemSingle-LevelMfgOvhdCost]
	, [ItemOverheadRate]
	, [ItemRolled-upSubcontractedCost]
	, [ItemRolled-upMfgOvhdCost]
	, [ItemRolled-upCapOverheadCost]
	, [ItemOrderTrackingPolicy]
	, [ItemCritical]
	, [ItemCommonItemNo]
	, [ItemLabelBarcode]
	, [ItemABCDCategory]
	, [ItemBrand]
	, [ItemProductLineCode]
	, [ItemProductUsage]
	, [ItemProdGroupCode]
	, [ItemSize]
	, [ItemSizeUnit]
	, [ItemFeature]
	, [ItemPackingMethod]
	, [ItemCoating]
	, [ItemQuality]
	, [ItemWithLid]
	, [ItemWeightClassificationNOTO]
	, [ItemCalculatedAvailableNOTO]
	, [ItemCalculatedAvailableExtNOTO]
	, [ItemCalculatedAvailableDateNOTO]
	, [ItemBodyType]
	, [ItemBOMQuantity]
	, [ItemHashKey]
	, [ADF_BatchId_Insert]
	, [ADF_BatchId_Update]
	
	)
    VALUES (s.[ItemKey]
		, s.[ItemCompanyID]
		, s.[timestamp]
		, s.[ItemNo]
		, s.[ItemNo2]
		, s.[ItemDescription]
		, s.[ItemSearchDescription]
		, s.[ItemDescription2]
		, s.[ItemBaseUnitofMeasure]
		, s.[ItemPriceUnitConversion]
		, s.[ItemType]
		, s.[ItemInventoryPostingGroup]
		, s.[ItemShelfNo]
		, s.[ItemItemDiscGroup]
		, s.[ItemAllowInvoiceDisc]
		, s.[ItemStatisticsGroup]
		, s.[ItemCommissionGroup]
		, s.[ItemUnitPrice]
		, s.[ItemPriceProfitCalculation]
		, s.[ItemProfit]
		, s.[ItemCostingMethod]
		, s.[ItemUnitCost]
		, s.[ItemStandardCost]
		, s.[ItemLastDirectCost]
		, s.[ItemIndirectCost]
		, s.[ItemCostisAdjusted]
		, s.[ItemAllowOnlineAdjustment]
		, s.[ItemVendorNo]
		, s.[ItemVendorItemNo]
		, s.[ItemLeadTimeCalculation]
		, s.[ItemReorderPoint]
		, s.[ItemMaximumInventory]
		, s.[ItemReorderQuantity]
		, s.[ItemAlternativeItemNo]
		, s.[ItemUnitListPrice]
		, s.[ItemDutyDue]
		, s.[ItemDutyCode]
		, s.[ItemGrossWeight]
		, s.[ItemNetWeight]
		, s.[ItemUnitsperParcel]
		, s.[ItemUnitVolume]
		, s.[ItemDurability]
		, s.[ItemFreightType]
		, s.[ItemTariffNo]
		, s.[ItemDutyUnitConversion]
		, s.[ItemCountryRegionPurchasedCode]
		, s.[ItemBudgetQuantity]
		, s.[ItemBudgetedAmount]
		, s.[ItemBudgetProfit]
		, s.[ItemBlocked]
		, s.[ItemBlockReason]
		, s.[ItemLastDateTimeModified]
		, s.[ItemLastDateModified]
		, s.[ItemLastTimeModified]
		, s.[ItemPriceIncludesVAT]
		, s.[ItemVATBusPostingGr(Price)]
		, s.[ItemGenProdPostingGroup]
		, s.[ItemPicture]
		, s.[ItemCountryRegionofOriginCode]
		, s.[ItemAutomaticExtTexts]
		, s.[ItemNoSeries]
		, s.[ItemTaxGroupCode]
		, s.[ItemVATProdPostingGroup]
		, s.[ItemReserve]
		, s.[ItemGlobalDimension1Code]
		, s.[ItemGlobalDimension2Code]
		, s.[ItemStockoutWarning]
		, s.[ItemPreventNegativeInventory]
		, s.[ItemApplicationWkshUserID]
		, s.[ItemAssemblyPolicy]
		, s.[ItemGTIN]
		, s.[ItemDefaultDeferralTemplateCode]
		, s.[ItemLow-LevelCode]
		, s.[ItemLotSize]
		, s.[ItemSerialNos]
		, s.[ItemLastUnitCostCalcDate]
		, s.[ItemRolled-upMaterialCost]
		, s.[ItemRolled-upCapacityCost]
		, s.[ItemScrap]
		, s.[ItemInventoryValueZero]
		, s.[ItemDiscreteOrderQuantity]
		, s.[ItemMinimumOrderQuantity]
		, s.[ItemMaximumOrderQuantity]
		, s.[ItemSafetyStockQuantity]
		, s.[ItemOrderMultiple]
		, s.[ItemSafetyLeadTime]
		, s.[ItemFlushingMethod]
		, s.[ItemReplenishmentSystem]
		, s.[ItemRoundingPrecision]
		, s.[ItemSalesUnitofMeasure]
		, s.[ItemPurchUnitofMeasure]
		, s.[ItemTimeBucket]
		, s.[ItemReorderingPolicy]
		, s.[ItemIncludeInventory]
		, s.[ItemManufacturingPolicy]
		, s.[ItemReschedulingPeriod]
		, s.[ItemLotAccumulationPeriod]
		, s.[ItemDampenerPeriod]
		, s.[ItemDampenerQuantity]
		, s.[ItemOverflowLevel]
		, s.[ItemManufacturerCode]
		, s.[ItemItemCategoryCode]
		, s.[ItemCreatedFromNonstockItem]
		, s.[ItemProductGroupCode]
		, s.[ItemPurchasingCode]
		, s.[ItemServiceItemGroup]
		, s.[ItemItemTrackingCode]
		, s.[ItemLotNos]
		, s.[ItemExpirationCalculation]
		, s.[ItemWarehouseClassCode]
		, s.[ItemSpecialEquipmentCode]
		, s.[ItemPut-awayTemplateCode]
		, s.[ItemPut-awayUnitofMeasureCode]
		, s.[ItemPhysInvtCountingPeriodCode]
		, s.[ItemLastCountingPeriodUpdate]
		, s.[ItemUseCross-Docking]
		, s.[ItemNextCountingStartDate]
		, s.[ItemNextCountingEndDate]
		, s.[ItemSalesBlocked]
		, s.[ItemPurchasingBlocked]
		, s.[ItemItemCategoryId]
		, s.[ItemOver-ReceiptCode]
		, s.[ItemRoutingNo]
		, s.[ItemProductionBOMNo]
		, s.[ItemSingle-LevelMaterialCost]
		, s.[ItemSingle-LevelCapacityCost]
		, s.[ItemSingle-LevelSubcontrdCost]
		, s.[ItemSingle-LevelCapOvhdCost]
		, s.[ItemSingle-LevelMfgOvhdCost]
		, s.[ItemOverheadRate]
		, s.[ItemRolled-upSubcontractedCost]
		, s.[ItemRolled-upMfgOvhdCost]
		, s.[ItemRolled-upCapOverheadCost]
		, s.[ItemOrderTrackingPolicy]
		, s.[ItemCritical]
		, s.[ItemCommonItemNo]
		, s.[ItemLabelBarcode]
		, s.[ItemABCDCategory]
		, s.[ItemBrand]
		, s.[ItemProductLineCode]
		, s.[ItemProductUsage]
		, s.[ItemProdGroupCode]
		, s.[ItemSize]
		, s.[ItemSizeUnit]
		, s.[ItemFeature]
		, s.[ItemPackingMethod]
		, s.[ItemCoating]
		, s.[ItemQuality]
		, s.[ItemWithLid]
		, s.[ItemWeightClassificationNOTO]
		, s.[ItemCalculatedAvailableNOTO]
		, s.[ItemCalculatedAvailableExtNOTO]
		, s.[ItemCalculatedAvailableDateNOTO]
		, s.[ItemBodyType]
		, s.[ItemBOMQuantity]
		, s.[ItemHashKey]
		, s.[ADF_BatchId_Insert]
		, s.[ADF_BatchId_Update]
		)
	WHEN MATCHED
	THEN      						  -- update record with update flag
        UPDATE SET
		d.[ItemCompanyID] = s.[ItemCompanyID]
		, d.[timestamp] = s.[timestamp]
		, d.[ItemNo] = s.[ItemNo]
		, d.[ItemNo2] = s.[ItemNo2]
		, d.[ItemDescription] = s.[ItemDescription]
		, d.[ItemSearchDescription] = s.[ItemSearchDescription]
		, d.[ItemDescription2] = s.[ItemDescription2]
		, d.[ItemBaseUnitofMeasure] = s.[ItemBaseUnitofMeasure]
		, d.[ItemPriceUnitConversion] = s.[ItemPriceUnitConversion]
		, d.[ItemType] = s.[ItemType]
		, d.[ItemInventoryPostingGroup] = s.[ItemInventoryPostingGroup]
		, d.[ItemShelfNo] = s.[ItemShelfNo]
		, d.[ItemItemDiscGroup] = s.[ItemItemDiscGroup]
		, d.[ItemAllowInvoiceDisc] = s.[ItemAllowInvoiceDisc]
		, d.[ItemStatisticsGroup] = s.[ItemStatisticsGroup]
		, d.[ItemCommissionGroup] = s.[ItemCommissionGroup]
		, d.[ItemUnitPrice] = s.[ItemUnitPrice]
		, d.[ItemPriceProfitCalculation] = s.[ItemPriceProfitCalculation]
		, d.[ItemProfit] = s.[ItemProfit]
		, d.[ItemCostingMethod] = s.[ItemCostingMethod]
		, d.[ItemUnitCost] = s.[ItemUnitCost]
		, d.[ItemStandardCost] = s.[ItemStandardCost]
		, d.[ItemLastDirectCost] = s.[ItemLastDirectCost]
		, d.[ItemIndirectCost] = s.[ItemIndirectCost]
		, d.[ItemCostisAdjusted] = s.[ItemCostisAdjusted]
		, d.[ItemAllowOnlineAdjustment] = s.[ItemAllowOnlineAdjustment]
		, d.[ItemVendorNo] = s.[ItemVendorNo]
		, d.[ItemVendorItemNo] = s.[ItemVendorItemNo]
		, d.[ItemLeadTimeCalculation] = s.[ItemLeadTimeCalculation]
		, d.[ItemReorderPoint] = s.[ItemReorderPoint]
		, d.[ItemMaximumInventory] = s.[ItemMaximumInventory]
		, d.[ItemReorderQuantity] = s.[ItemReorderQuantity]
		, d.[ItemAlternativeItemNo] = s.[ItemAlternativeItemNo]
		, d.[ItemUnitListPrice] = s.[ItemUnitListPrice]
		, d.[ItemDutyDue] = s.[ItemDutyDue]
		, d.[ItemDutyCode] = s.[ItemDutyCode]
		, d.[ItemGrossWeight] = s.[ItemGrossWeight]
		, d.[ItemNetWeight] = s.[ItemNetWeight]
		, d.[ItemUnitsperParcel] = s.[ItemUnitsperParcel]
		, d.[ItemUnitVolume] = s.[ItemUnitVolume]
		, d.[ItemDurability] = s.[ItemDurability]
		, d.[ItemFreightType] = s.[ItemFreightType]
		, d.[ItemTariffNo] = s.[ItemTariffNo]
		, d.[ItemDutyUnitConversion] = s.[ItemDutyUnitConversion]
		, d.[ItemCountryRegionPurchasedCode] = s.[ItemCountryRegionPurchasedCode]
		, d.[ItemBudgetQuantity] = s.[ItemBudgetQuantity]
		, d.[ItemBudgetedAmount] = s.[ItemBudgetedAmount]
		, d.[ItemBudgetProfit] = s.[ItemBudgetProfit]
		, d.[ItemBlocked] = s.[ItemBlocked]
		, d.[ItemBlockReason] = s.[ItemBlockReason]
		, d.[ItemLastDateTimeModified] = s.[ItemLastDateTimeModified]
		, d.[ItemLastDateModified] = s.[ItemLastDateModified]
		, d.[ItemLastTimeModified] = s.[ItemLastTimeModified]
		, d.[ItemPriceIncludesVAT] = s.[ItemPriceIncludesVAT]
		, d.[ItemVATBusPostingGr(Price)] = s.[ItemVATBusPostingGr(Price)]
		, d.[ItemGenProdPostingGroup] = s.[ItemGenProdPostingGroup]
		, d.[ItemPicture] = s.[ItemPicture]
		, d.[ItemCountryRegionofOriginCode] = s.[ItemCountryRegionofOriginCode]
		, d.[ItemAutomaticExtTexts] = s.[ItemAutomaticExtTexts]
		, d.[ItemNoSeries] = s.[ItemNoSeries]
		, d.[ItemTaxGroupCode] = s.[ItemTaxGroupCode]
		, d.[ItemVATProdPostingGroup] = s.[ItemVATProdPostingGroup]
		, d.[ItemReserve] = s.[ItemReserve]
		, d.[ItemGlobalDimension1Code] = s.[ItemGlobalDimension1Code]
		, d.[ItemGlobalDimension2Code] = s.[ItemGlobalDimension2Code]
		, d.[ItemStockoutWarning] = s.[ItemStockoutWarning]
		, d.[ItemPreventNegativeInventory] = s.[ItemPreventNegativeInventory]
		, d.[ItemApplicationWkshUserID] = s.[ItemApplicationWkshUserID]
		, d.[ItemAssemblyPolicy] = s.[ItemAssemblyPolicy]
		, d.[ItemGTIN] = s.[ItemGTIN]
		, d.[ItemDefaultDeferralTemplateCode] = s.[ItemDefaultDeferralTemplateCode]
		, d.[ItemLow-LevelCode] = s.[ItemLow-LevelCode]
		, d.[ItemLotSize] = s.[ItemLotSize]
		, d.[ItemSerialNos] = s.[ItemSerialNos]
		, d.[ItemLastUnitCostCalcDate] = s.[ItemLastUnitCostCalcDate]
		, d.[ItemRolled-upMaterialCost] = s.[ItemRolled-upMaterialCost]
		, d.[ItemRolled-upCapacityCost] = s.[ItemRolled-upCapacityCost]
		, d.[ItemScrap] = s.[ItemScrap]
		, d.[ItemInventoryValueZero] = s.[ItemInventoryValueZero]
		, d.[ItemDiscreteOrderQuantity] = s.[ItemDiscreteOrderQuantity]
		, d.[ItemMinimumOrderQuantity] = s.[ItemMinimumOrderQuantity]
		, d.[ItemMaximumOrderQuantity] = s.[ItemMaximumOrderQuantity]
		, d.[ItemSafetyStockQuantity] = s.[ItemSafetyStockQuantity]
		, d.[ItemOrderMultiple] = s.[ItemOrderMultiple]
		, d.[ItemSafetyLeadTime] = s.[ItemSafetyLeadTime]
		, d.[ItemFlushingMethod] = s.[ItemFlushingMethod]
		, d.[ItemReplenishmentSystem] = s.[ItemReplenishmentSystem]
		, d.[ItemRoundingPrecision] = s.[ItemRoundingPrecision]
		, d.[ItemSalesUnitofMeasure] = s.[ItemSalesUnitofMeasure]
		, d.[ItemPurchUnitofMeasure] = s.[ItemPurchUnitofMeasure]
		, d.[ItemTimeBucket] = s.[ItemTimeBucket]
		, d.[ItemReorderingPolicy] = s.[ItemReorderingPolicy]
		, d.[ItemIncludeInventory] = s.[ItemIncludeInventory]
		, d.[ItemManufacturingPolicy] = s.[ItemManufacturingPolicy]
		, d.[ItemReschedulingPeriod] = s.[ItemReschedulingPeriod]
		, d.[ItemLotAccumulationPeriod] = s.[ItemLotAccumulationPeriod]
		, d.[ItemDampenerPeriod] = s.[ItemDampenerPeriod]
		, d.[ItemDampenerQuantity] = s.[ItemDampenerQuantity]
		, d.[ItemOverflowLevel] = s.[ItemOverflowLevel]
		, d.[ItemManufacturerCode] = s.[ItemManufacturerCode]
		, d.[ItemItemCategoryCode] = s.[ItemItemCategoryCode]
		, d.[ItemCreatedFromNonstockItem] = s.[ItemCreatedFromNonstockItem]
		, d.[ItemProductGroupCode] = s.[ItemProductGroupCode]
		, d.[ItemPurchasingCode] = s.[ItemPurchasingCode]
		, d.[ItemServiceItemGroup] = s.[ItemServiceItemGroup]
		, d.[ItemItemTrackingCode] = s.[ItemItemTrackingCode]
		, d.[ItemLotNos] = s.[ItemLotNos]
		, d.[ItemExpirationCalculation] = s.[ItemExpirationCalculation]
		, d.[ItemWarehouseClassCode] = s.[ItemWarehouseClassCode]
		, d.[ItemSpecialEquipmentCode] = s.[ItemSpecialEquipmentCode]
		, d.[ItemPut-awayTemplateCode] = s.[ItemPut-awayTemplateCode]
		, d.[ItemPut-awayUnitofMeasureCode] = s.[ItemPut-awayUnitofMeasureCode]
		, d.[ItemPhysInvtCountingPeriodCode] = s.[ItemPhysInvtCountingPeriodCode]
		, d.[ItemLastCountingPeriodUpdate] = s.[ItemLastCountingPeriodUpdate]
		, d.[ItemUseCross-Docking] = s.[ItemUseCross-Docking]
		, d.[ItemNextCountingStartDate] = s.[ItemNextCountingStartDate]
		, d.[ItemNextCountingEndDate] = s.[ItemNextCountingEndDate]
		, d.[ItemSalesBlocked] = s.[ItemSalesBlocked]
		, d.[ItemPurchasingBlocked] = s.[ItemPurchasingBlocked]
		, d.[ItemItemCategoryId] = s.[ItemItemCategoryId]
		, d.[ItemOver-ReceiptCode] = s.[ItemOver-ReceiptCode]
		, d.[ItemRoutingNo] = s.[ItemRoutingNo]
		, d.[ItemProductionBOMNo] = s.[ItemProductionBOMNo]
		, d.[ItemSingle-LevelMaterialCost] = s.[ItemSingle-LevelMaterialCost]
		, d.[ItemSingle-LevelCapacityCost] = s.[ItemSingle-LevelCapacityCost]
		, d.[ItemSingle-LevelSubcontrdCost] = s.[ItemSingle-LevelSubcontrdCost]
		, d.[ItemSingle-LevelCapOvhdCost] = s.[ItemSingle-LevelCapOvhdCost]
		, d.[ItemSingle-LevelMfgOvhdCost] = s.[ItemSingle-LevelMfgOvhdCost]
		, d.[ItemOverheadRate] = s.[ItemOverheadRate]
		, d.[ItemRolled-upSubcontractedCost] = s.[ItemRolled-upSubcontractedCost]
		, d.[ItemRolled-upMfgOvhdCost] = s.[ItemRolled-upMfgOvhdCost]
		, d.[ItemRolled-upCapOverheadCost] = s.[ItemRolled-upCapOverheadCost]
		, d.[ItemOrderTrackingPolicy] = s.[ItemOrderTrackingPolicy]
		, d.[ItemCritical] = s.[ItemCritical]
		, d.[ItemCommonItemNo] = s.[ItemCommonItemNo]
		, d.[ItemLabelBarcode] = s.[ItemLabelBarcode]
		, d.[ItemABCDCategory] = s.[ItemABCDCategory]
		, d.[ItemBrand] = s.[ItemBrand]
		, d.[ItemProductLineCode] = s.[ItemProductLineCode]
		, d.[ItemProductUsage] = s.[ItemProductUsage]
		, d.[ItemProdGroupCode] = s.[ItemProdGroupCode]
		, d.[ItemSize] = s.[ItemSize]
		, d.[ItemSizeUnit] = s.[ItemSizeUnit]
		, d.[ItemFeature] = s.[ItemFeature]
		, d.[ItemPackingMethod] = s.[ItemPackingMethod]
		, d.[ItemCoating] = s.[ItemCoating]
		, d.[ItemQuality] = s.[ItemQuality]
		, d.[ItemWithLid] = s.[ItemWithLid]
		, d.[ItemWeightClassificationNOTO] = s.[ItemWeightClassificationNOTO]
		, d.[ItemCalculatedAvailableNOTO] = s.[ItemCalculatedAvailableNOTO]
		, d.[ItemCalculatedAvailableExtNOTO] = s.[ItemCalculatedAvailableExtNOTO]
		, d.[ItemCalculatedAvailableDateNOTO] = s.[ItemCalculatedAvailableDateNOTO]
		, d.[ItemBodyType] = s.[ItemBodyType]
		, d.[ItemBOMQuantity] = s.[ItemBOMQuantity]
		, d.[ItemHashKey] = s.[ItemHashKey]
		, d.[ADF_BatchId_Insert] = s.[ADF_BatchId_Insert]
		, d.[ADF_BatchId_Update] = s.[ADF_BatchId_Update]
		

	OPTION ( RECOMPILE );
 	
    
    -- Commit only if the transaction was started in this procedure
        IF @TranCounter = 0
            COMMIT TRANSACTION;
    END TRY
 
    BEGIN CATCH
 
    -- Only rollback if transaction was started in this procedure
        IF @TranCounter = 0
            ROLLBACK TRANSACTION;
    -- It's not our transaction but it's still OK
        ELSE
            IF XACT_STATE() = 1
                ROLLBACK TRANSACTION @SavePoint
    -- All hope is lost - rollback!
            ELSE
                IF XACT_STATE() = -1
                    ROLLBACK TRANSACTION;
 
        THROW;
        RETURN 1;
 
    END CATCH;
END

GO

