/* This file was generated automatically by a T4 Template */

CREATE PROCEDURE [dim_v1].[InsertUnknownEntitiesCustomer]
AS
BEGIN
    SET NOCOUNT ON;
 
    BEGIN TRY
    -- Get the current transaction count
    DECLARE @TranCounter INT = @@TRANCOUNT
		,@SavePoint NVARCHAR(32) = CAST(@@PROCID AS NVARCHAR(20)) + N'_' + CAST(@@NESTLEVEL AS NVARCHAR(2));

    -- Decide to join existing transaction or start new
    IF @TranCounter > 0
      SAVE TRANSACTION @SavePoint;
    ELSE
      BEGIN TRANSACTION;

    
	 
	MERGE [dim_v1].[Customer] AS d
    USING (
			SELECT -1 AS [CustomerKey]
			, -1 AS [CustomerCompanyID]
			, 0x AS [timestamp]
			, 'Unknown' AS [CustomerNo]
			, 'Unknown' AS [CustomerName]
			, 'Unknown' AS [CustomerNoName]
			, 'Unknown' AS [CustomerSearchName]
			, 'Unknown' AS [CustomerName2]
			, 'Unknown' AS [CustomerAddress]
			, 'Unknown' AS [CustomerAddress2]
			, 'Unknown' AS [CustomerCity]
			, 'Unknown' AS [CustomerContact]
			, 'Unknown' AS [CustomerPhoneNo]
			, 'Unknown' AS [CustomerTelexNo]
			, 'Unknown' AS [CustomerDocumentSendingProfile]
			, 'Unknown' AS [CustomerShip-toCode]
			, 'Unknown' AS [CustomerOurAccountNo]
			, 'Unknown' AS [CustomerTerritoryCode]
			, 'Unknown' AS [CustomerGlobalDimension1Code]
			, 'Unknown' AS [CustomerGlobalDimension2Code]
			, 'Unknown' AS [CustomerChainCode]
            , 'Unknown' AS [CustomerChainName]
			, 'Unknown' AS [CustomerChainGroupCode]
            , 'Unknown' AS [CustomerChainGroupName]
			, -1 AS [CustomerBudgetedAmount]
			, -1 AS [CustomerCreditLimit(LCY)]
			, 'Unknown' AS [CustomerCustomerPostingGroup]
			, 'Unknown' AS [CustomerCurrencyCode]
			, 'Unknown' AS [CustomerCustomerPriceGroup]
			, 'Unknown' AS [CustomerLanguageCode]
			, -1 AS [CustomerStatisticsGroup]
			, 'Unknown' AS [CustomerPaymentTermsCode]
			, 'Unknown' AS [CustomerFinChargeTermsCode]
			, 'Unknown' AS [CustomerTeamCodeName]
			, 'Unknown' AS [CustomerTeamPersonCodeName]
			, 'Unknown' AS [CustomerSalespersonCode]
			, 'Unknown' AS [CustomerShipmentMethodCode]
			, 'Unknown' AS [CustomerShippingAgentCode]
			, 'Unknown' AS [CustomerPlaceofExport]
			, 'Unknown' AS [CustomerInvoiceDiscCode]
			, 'Unknown' AS [CustomerCustomerDiscGroup]
			, 'Unknown' AS [CustomerCountryRegionCode]
			, 'Unknown' AS [CustomerCollectionMethod]
			, -1 AS [CustomerAmount]
			, 'Unknown' AS [CustomerBlocked]
			, -1 AS [CustomerInvoiceCopies]
			, -1 AS [CustomerLastStatementNo]
			, 0 AS [CustomerPrintStatements]
			, 'Unknown' AS [CustomerBill-toCustomerNo]
			, -1 AS [CustomerPriority]
			, 'Unknown' AS [CustomerPaymentMethodCode]
			, '1900-01-01' AS [CustomerLastModifiedDateTime]
			, '1900-01-01' AS [CustomerLastDateModified]
			, -1 AS [CustomerApplicationMethod]
			, 0 AS [CustomerPricesIncludingVAT]
			, 'Unknown' AS [CustomerLocationCode]
			, 'Unknown' AS [CustomerFaxNo]
			, 'Unknown' AS [CustomerTelexAnswerBack]
			, 'Unknown' AS [CustomerVATRegistrationNo]
			, 0 AS [CustomerCombineShipments]
			, 'Unknown' AS [CustomerGenBusPostingGroup]
			, 0x AS [CustomerPicture]
			, 'Unknown' AS [CustomerGLN]
			, 'Unknown' AS [CustomerPostCode]
			, 'Unknown' AS [CustomerCounty]
			, 'Unknown' AS [CustomerEORINumber]
			, 0 AS [CustomerUseGLNinElectronicDocument]
			, 'Unknown' AS [CustomerE-Mail]
			, 'Unknown' AS [CustomerHomePage]
			, 'Unknown' AS [CustomerReminderTermsCode]
			, 'Unknown' AS [CustomerNoSeries]
			, 'Unknown' AS [CustomerTaxAreaCode]
			, 0 AS [CustomerTaxLiable]
			, 'Unknown' AS [CustomerVATBusPostingGroup]
			, -1 AS [CustomerReserve]
			, 0 AS [CustomerBlockPaymentTolerance]
			, 'Unknown' AS [CustomerICPartnerCode]
			, -1 AS [CustomerPrepayment]
			, -1 AS [CustomerPartnerType]
			, 'Unknown' AS [CustomerImage]
			, 0 AS [CustomerPrivacyBlocked]
			, 0 AS [CustomerDisableSearchbyName]
			, 'Unknown' AS [CustomerPreferredBankAccountCode]
			, 'Unknown' AS [CustomerCashFlowPaymentTermsCode]
			, 'Unknown' AS [CustomerPrimaryContactNo]
			, -1 AS [CustomerContactType]
			, 'Unknown' AS [CustomerMobilePhoneNo]
			, 'Unknown' AS [CustomerResponsibilityCenter]
			, -1 AS [CustomerShippingAdvice]
			, 'Unknown' AS [CustomerShippingTime]
			, 'Unknown' AS [CustomerShippingAgentServiceCode]
			, 'Unknown' AS [CustomerServiceZoneCode]
			, -1 AS [CustomerPriceCalculationMethod]
			, 0 AS [CustomerAllowLineDisc]
			, 'Unknown' AS [CustomerBaseCalendarCode]
			, -1 AS [CustomerCopySell-toAddrtoQteFrom]
			, 0 AS [CustomerValidateEUVatRegNo]
			, 'Unknown' AS [CustomerEANNo]
			, 'Unknown' AS [CustomerAccountCode]
			, 'Unknown' AS [CustomerOIOUBLProfileCode]
			, 0 AS [CustomerOIOUBLProfileCodeRequired]
			, -1 AS [CustomerPriorityNOTO]
			, 0 AS [CustomerDelSOsWithRemQtyNOTO]
			, 0 AS [CustomerUseBarcode]
			, 'Unknown' AS [CustomerOldCustomerNo]
			, 0 AS [CustomerCalculateFreight]
			, 0 AS [CustomerBatchPosting]
			, 'Unknown' AS [CustomerHashKey]
			, -1 AS [ADF_BatchId_Insert]
			, -1 AS [ADF_BatchId_Update]
			
			UNION ALL

			SELECT -2 AS [CustomerKey]
			, -2 AS [CustomerCompanyID]
			, 0x AS [timestamp]
			, 'Blank' AS [CustomerNo]
			, 'Blank' AS [CustomerName]
			, 'Blank' AS [CustomerNoName]
			, 'Blank' AS [CustomerSearchName]
			, 'Blank' AS [CustomerName2]
			, 'Blank' AS [CustomerAddress]
			, 'Blank' AS [CustomerAddress2]
			, 'Blank' AS [CustomerCity]
			, 'Blank' AS [CustomerContact]
			, 'Blank' AS [CustomerPhoneNo]
			, 'Blank' AS [CustomerTelexNo]
			, 'Blank' AS [CustomerDocumentSendingProfile]
			, 'Blank' AS [CustomerShip-toCode]
			, 'Blank' AS [CustomerOurAccountNo]
			, 'Blank' AS [CustomerTerritoryCode]
			, 'Blank' AS [CustomerGlobalDimension1Code]
			, 'Blank' AS [CustomerGlobalDimension2Code]
			, 'Blank' AS [CustomerChainCode]
            , 'Blank' AS [CustomerChainName]
			, 'Blank' AS [CustomerChainGroupCode]
            , 'Blank' AS [CustomerChainGroupName]
			, -2 AS [CustomerBudgetedAmount]
			, -2 AS [CustomerCreditLimit(LCY)]
			, 'Blank' AS [CustomerCustomerPostingGroup]
			, 'Blank' AS [CustomerCurrencyCode]
			, 'Blank' AS [CustomerCustomerPriceGroup]
			, 'Blank' AS [CustomerLanguageCode]
			, -2 AS [CustomerStatisticsGroup]
			, 'Blank' AS [CustomerPaymentTermsCode]
			, 'Blank' AS [CustomerFinChargeTermsCode]
			, 'Blank' AS [CustomerTeamCodeName]
			, 'Blank' AS [CustomerTeamPersonCodeName]
			, 'Blank' AS [CustomerSalespersonCode]
			, 'Blank' AS [CustomerShipmentMethodCode]
			, 'Blank' AS [CustomerShippingAgentCode]
			, 'Blank' AS [CustomerPlaceofExport]
			, 'Blank' AS [CustomerInvoiceDiscCode]
			, 'Blank' AS [CustomerCustomerDiscGroup]
			, 'Blank' AS [CustomerCountryRegionCode]
			, 'Blank' AS [CustomerCollectionMethod]
			, -2 AS [CustomerAmount]
			, 'Blank' AS [CustomerBlocked]
			, -2 AS [CustomerInvoiceCopies]
			, -2 AS [CustomerLastStatementNo]
			, 0 AS [CustomerPrintStatements]
			, 'Blank' AS [CustomerBill-toCustomerNo]
			, -2 AS [CustomerPriority]
			, 'Blank' AS [CustomerPaymentMethodCode]
			, '1900-01-01' AS [CustomerLastModifiedDateTime]
			, '1900-01-01' AS [CustomerLastDateModified]
			, -2 AS [CustomerApplicationMethod]
			, 0 AS [CustomerPricesIncludingVAT]
			, 'Blank' AS [CustomerLocationCode]
			, 'Blank' AS [CustomerFaxNo]
			, 'Blank' AS [CustomerTelexAnswerBack]
			, 'Blank' AS [CustomerVATRegistrationNo]
			, 0 AS [CustomerCombineShipments]
			, 'Blank' AS [CustomerGenBusPostingGroup]
			, 0x AS [CustomerPicture]
			, 'Blank' AS [CustomerGLN]
			, 'Blank' AS [CustomerPostCode]
			, 'Blank' AS [CustomerCounty]
			, 'Blank' AS [CustomerEORINumber]
			, 0 AS [CustomerUseGLNinElectronicDocument]
			, 'Blank' AS [CustomerE-Mail]
			, 'Blank' AS [CustomerHomePage]
			, 'Blank' AS [CustomerReminderTermsCode]
			, 'Blank' AS [CustomerNoSeries]
			, 'Blank' AS [CustomerTaxAreaCode]
			, 0 AS [CustomerTaxLiable]
			, 'Blank' AS [CustomerVATBusPostingGroup]
			, -2 AS [CustomerReserve]
			, 0 AS [CustomerBlockPaymentTolerance]
			, 'Blank' AS [CustomerICPartnerCode]
			, -2 AS [CustomerPrepayment]
			, -2 AS [CustomerPartnerType]
			, 'Blank' AS [CustomerImage]
			, 0 AS [CustomerPrivacyBlocked]
			, 0 AS [CustomerDisableSearchbyName]
			, 'Blank' AS [CustomerPreferredBankAccountCode]
			, 'Blank' AS [CustomerCashFlowPaymentTermsCode]
			, 'Blank' AS [CustomerPrimaryContactNo]
			, -2 AS [CustomerContactType]
			, 'Blank' AS [CustomerMobilePhoneNo]
			, 'Blank' AS [CustomerResponsibilityCenter]
			, -2 AS [CustomerShippingAdvice]
			, 'Blank' AS [CustomerShippingTime]
			, 'Blank' AS [CustomerShippingAgentServiceCode]
			, 'Blank' AS [CustomerServiceZoneCode]
			, -2 AS [CustomerPriceCalculationMethod]
			, 0 AS [CustomerAllowLineDisc]
			, 'Blank' AS [CustomerBaseCalendarCode]
			, -2 AS [CustomerCopySell-toAddrtoQteFrom]
			, 0 AS [CustomerValidateEUVatRegNo]
			, 'Blank' AS [CustomerEANNo]
			, 'Blank' AS [CustomerAccountCode]
			, 'Blank' AS [CustomerOIOUBLProfileCode]
			, 0 AS [CustomerOIOUBLProfileCodeRequired]
			, -2 AS [CustomerPriorityNOTO]
			, 0 AS [CustomerDelSOsWithRemQtyNOTO]
			, 0 AS [CustomerUseBarcode]
			, 'Blank' AS [CustomerOldCustomerNo]
			, 0 AS [CustomerCalculateFreight]
			, 0 AS [CustomerBatchPosting]
			, 'Blank' AS [CustomerHashKey]
			, -2 AS [ADF_BatchId_Insert]
			, -2 AS [ADF_BatchId_Update]
			
		  ) s
	ON s.[CustomerKey] = d.[CustomerKey]
	
	WHEN NOT MATCHED THEN -- Insert new records
    INSERT ([CustomerKey]
	, [CustomerCompanyID]
	, [timestamp]
	, [CustomerNo]
	, [CustomerName]
	, [CustomerNoName]
	, [CustomerSearchName]
	, [CustomerName2]
	, [CustomerAddress]
	, [CustomerAddress2]
	, [CustomerCity]
	, [CustomerContact]
	, [CustomerPhoneNo]
	, [CustomerTelexNo]
	, [CustomerDocumentSendingProfile]
	, [CustomerShip-toCode]
	, [CustomerOurAccountNo]
	, [CustomerTerritoryCode]
	, [CustomerGlobalDimension1Code]
	, [CustomerGlobalDimension2Code]
    , [CustomerChainCode]
	, [CustomerChainName]
	, [CustomerChainGroupCode]
    , [CustomerChainGroupName]
	, [CustomerBudgetedAmount]
	, [CustomerCreditLimit(LCY)]
	, [CustomerCustomerPostingGroup]
	, [CustomerCurrencyCode]
	, [CustomerCustomerPriceGroup]
	, [CustomerLanguageCode]
	, [CustomerStatisticsGroup]
	, [CustomerPaymentTermsCode]
	, [CustomerFinChargeTermsCode]
	, [CustomerTeamCodeName]
	, [CustomerTeamPersonCodeName]
	, [CustomerSalespersonCode]
	, [CustomerShipmentMethodCode]
	, [CustomerShippingAgentCode]
	, [CustomerPlaceofExport]
	, [CustomerInvoiceDiscCode]
	, [CustomerCustomerDiscGroup]
	, [CustomerCountryRegionCode]
	, [CustomerCollectionMethod]
	, [CustomerAmount]
	, [CustomerBlocked]
	, [CustomerInvoiceCopies]
	, [CustomerLastStatementNo]
	, [CustomerPrintStatements]
	, [CustomerBill-toCustomerNo]
	, [CustomerPriority]
	, [CustomerPaymentMethodCode]
	, [CustomerLastModifiedDateTime]
	, [CustomerLastDateModified]
	, [CustomerApplicationMethod]
	, [CustomerPricesIncludingVAT]
	, [CustomerLocationCode]
	, [CustomerFaxNo]
	, [CustomerTelexAnswerBack]
	, [CustomerVATRegistrationNo]
	, [CustomerCombineShipments]
	, [CustomerGenBusPostingGroup]
	, [CustomerPicture]
	, [CustomerGLN]
	, [CustomerPostCode]
	, [CustomerCounty]
	, [CustomerEORINumber]
	, [CustomerUseGLNinElectronicDocument]
	, [CustomerE-Mail]
	, [CustomerHomePage]
	, [CustomerReminderTermsCode]
	, [CustomerNoSeries]
	, [CustomerTaxAreaCode]
	, [CustomerTaxLiable]
	, [CustomerVATBusPostingGroup]
	, [CustomerReserve]
	, [CustomerBlockPaymentTolerance]
	, [CustomerICPartnerCode]
	, [CustomerPrepayment]
	, [CustomerPartnerType]
	, [CustomerImage]
	, [CustomerPrivacyBlocked]
	, [CustomerDisableSearchbyName]
	, [CustomerPreferredBankAccountCode]
	, [CustomerCashFlowPaymentTermsCode]
	, [CustomerPrimaryContactNo]
	, [CustomerContactType]
	, [CustomerMobilePhoneNo]
	, [CustomerResponsibilityCenter]
	, [CustomerShippingAdvice]
	, [CustomerShippingTime]
	, [CustomerShippingAgentServiceCode]
	, [CustomerServiceZoneCode]
	, [CustomerPriceCalculationMethod]
	, [CustomerAllowLineDisc]
	, [CustomerBaseCalendarCode]
	, [CustomerCopySell-toAddrtoQteFrom]
	, [CustomerValidateEUVatRegNo]
	, [CustomerEANNo]
	, [CustomerAccountCode]
	, [CustomerOIOUBLProfileCode]
	, [CustomerOIOUBLProfileCodeRequired]
	, [CustomerPriorityNOTO]
	, [CustomerDelSOsWithRemQtyNOTO]
	, [CustomerUseBarcode]
	, [CustomerOldCustomerNo]
	, [CustomerCalculateFreight]
	, [CustomerBatchPosting]
	, [CustomerHashKey]
	, [ADF_BatchId_Insert]
	, [ADF_BatchId_Update]
	
	)
    VALUES (s.[CustomerKey]
		, s.[CustomerCompanyID]
		, s.[timestamp]
		, s.[CustomerNo]
		, s.[CustomerName]
		, s.[CustomerNoName]
		, s.[CustomerSearchName]
		, s.[CustomerName2]
		, s.[CustomerAddress]
		, s.[CustomerAddress2]
		, s.[CustomerCity]
		, s.[CustomerContact]
		, s.[CustomerPhoneNo]
		, s.[CustomerTelexNo]
		, s.[CustomerDocumentSendingProfile]
		, s.[CustomerShip-toCode]
		, s.[CustomerOurAccountNo]
		, s.[CustomerTerritoryCode]
		, s.[CustomerGlobalDimension1Code]
		, s.[CustomerGlobalDimension2Code]
        , s.[CustomerChainCode]
		, s.[CustomerChainName]
		, s.[CustomerChainGroupCode]
        , s.[CustomerChainGroupName]
		, s.[CustomerBudgetedAmount]
		, s.[CustomerCreditLimit(LCY)]
		, s.[CustomerCustomerPostingGroup]
		, s.[CustomerCurrencyCode]
		, s.[CustomerCustomerPriceGroup]
		, s.[CustomerLanguageCode]
		, s.[CustomerStatisticsGroup]
		, s.[CustomerPaymentTermsCode]
		, s.[CustomerFinChargeTermsCode]
		, s.[CustomerTeamCodeName]
		, s.[CustomerTeamPersonCodeName]
		, s.[CustomerSalespersonCode]
		, s.[CustomerShipmentMethodCode]
		, s.[CustomerShippingAgentCode]
		, s.[CustomerPlaceofExport]
		, s.[CustomerInvoiceDiscCode]
		, s.[CustomerCustomerDiscGroup]
		, s.[CustomerCountryRegionCode]
		, s.[CustomerCollectionMethod]
		, s.[CustomerAmount]
		, s.[CustomerBlocked]
		, s.[CustomerInvoiceCopies]
		, s.[CustomerLastStatementNo]
		, s.[CustomerPrintStatements]
		, s.[CustomerBill-toCustomerNo]
		, s.[CustomerPriority]
		, s.[CustomerPaymentMethodCode]
		, s.[CustomerLastModifiedDateTime]
		, s.[CustomerLastDateModified]
		, s.[CustomerApplicationMethod]
		, s.[CustomerPricesIncludingVAT]
		, s.[CustomerLocationCode]
		, s.[CustomerFaxNo]
		, s.[CustomerTelexAnswerBack]
		, s.[CustomerVATRegistrationNo]
		, s.[CustomerCombineShipments]
		, s.[CustomerGenBusPostingGroup]
		, s.[CustomerPicture]
		, s.[CustomerGLN]
		, s.[CustomerPostCode]
		, s.[CustomerCounty]
		, s.[CustomerEORINumber]
		, s.[CustomerUseGLNinElectronicDocument]
		, s.[CustomerE-Mail]
		, s.[CustomerHomePage]
		, s.[CustomerReminderTermsCode]
		, s.[CustomerNoSeries]
		, s.[CustomerTaxAreaCode]
		, s.[CustomerTaxLiable]
		, s.[CustomerVATBusPostingGroup]
		, s.[CustomerReserve]
		, s.[CustomerBlockPaymentTolerance]
		, s.[CustomerICPartnerCode]
		, s.[CustomerPrepayment]
		, s.[CustomerPartnerType]
		, s.[CustomerImage]
		, s.[CustomerPrivacyBlocked]
		, s.[CustomerDisableSearchbyName]
		, s.[CustomerPreferredBankAccountCode]
		, s.[CustomerCashFlowPaymentTermsCode]
		, s.[CustomerPrimaryContactNo]
		, s.[CustomerContactType]
		, s.[CustomerMobilePhoneNo]
		, s.[CustomerResponsibilityCenter]
		, s.[CustomerShippingAdvice]
		, s.[CustomerShippingTime]
		, s.[CustomerShippingAgentServiceCode]
		, s.[CustomerServiceZoneCode]
		, s.[CustomerPriceCalculationMethod]
		, s.[CustomerAllowLineDisc]
		, s.[CustomerBaseCalendarCode]
		, s.[CustomerCopySell-toAddrtoQteFrom]
		, s.[CustomerValidateEUVatRegNo]
		, s.[CustomerEANNo]
		, s.[CustomerAccountCode]
		, s.[CustomerOIOUBLProfileCode]
		, s.[CustomerOIOUBLProfileCodeRequired]
		, s.[CustomerPriorityNOTO]
		, s.[CustomerDelSOsWithRemQtyNOTO]
		, s.[CustomerUseBarcode]
		, s.[CustomerOldCustomerNo]
		, s.[CustomerCalculateFreight]
		, s.[CustomerBatchPosting]
		, s.[CustomerHashKey]
		, s.[ADF_BatchId_Insert]
		, s.[ADF_BatchId_Update]
		)
	WHEN MATCHED
	THEN      						  -- update record with update flag
        UPDATE SET
		d.[CustomerCompanyID] = s.[CustomerCompanyID]
		, d.[timestamp] = s.[timestamp]
		, d.[CustomerNo] = s.[CustomerNo]
		, d.[CustomerName] = s.[CustomerName]
		, d.[CustomerNoName] = s.[CustomerNoName]
		, d.[CustomerSearchName] = s.[CustomerSearchName]
		, d.[CustomerName2] = s.[CustomerName2]
		, d.[CustomerAddress] = s.[CustomerAddress]
		, d.[CustomerAddress2] = s.[CustomerAddress2]
		, d.[CustomerCity] = s.[CustomerCity]
		, d.[CustomerContact] = s.[CustomerContact]
		, d.[CustomerPhoneNo] = s.[CustomerPhoneNo]
		, d.[CustomerTelexNo] = s.[CustomerTelexNo]
		, d.[CustomerDocumentSendingProfile] = s.[CustomerDocumentSendingProfile]
		, d.[CustomerShip-toCode] = s.[CustomerShip-toCode]
		, d.[CustomerOurAccountNo] = s.[CustomerOurAccountNo]
		, d.[CustomerTerritoryCode] = s.[CustomerTerritoryCode]
		, d.[CustomerGlobalDimension1Code] = s.[CustomerGlobalDimension1Code]
		, d.[CustomerGlobalDimension2Code] = s.[CustomerGlobalDimension2Code]
        , d.[CustomerChainCode] = s.[CustomerChainCode]
		, d.[CustomerChainName] = s.[CustomerChainName]
		, d.[CustomerChainGroupCode] = s.[CustomerChainGroupCode]
        , d.[CustomerChainGroupName] = s.[CustomerChainGroupName]
		, d.[CustomerBudgetedAmount] = s.[CustomerBudgetedAmount]
		, d.[CustomerCreditLimit(LCY)] = s.[CustomerCreditLimit(LCY)]
		, d.[CustomerCustomerPostingGroup] = s.[CustomerCustomerPostingGroup]
		, d.[CustomerCurrencyCode] = s.[CustomerCurrencyCode]
		, d.[CustomerCustomerPriceGroup] = s.[CustomerCustomerPriceGroup]
		, d.[CustomerLanguageCode] = s.[CustomerLanguageCode]
		, d.[CustomerStatisticsGroup] = s.[CustomerStatisticsGroup]
		, d.[CustomerPaymentTermsCode] = s.[CustomerPaymentTermsCode]
		, d.[CustomerFinChargeTermsCode] = s.[CustomerFinChargeTermsCode]
		, d.[CustomerTeamCodeName] = s.[CustomerTeamCodeName]
		, d.[CustomerTeamPersonCodeName] = s.[CustomerTeamPersonCodeName]
		, d.[CustomerSalespersonCode] = s.[CustomerSalespersonCode]
		, d.[CustomerShipmentMethodCode] = s.[CustomerShipmentMethodCode]
		, d.[CustomerShippingAgentCode] = s.[CustomerShippingAgentCode]
		, d.[CustomerPlaceofExport] = s.[CustomerPlaceofExport]
		, d.[CustomerInvoiceDiscCode] = s.[CustomerInvoiceDiscCode]
		, d.[CustomerCustomerDiscGroup] = s.[CustomerCustomerDiscGroup]
		, d.[CustomerCountryRegionCode] = s.[CustomerCountryRegionCode]
		, d.[CustomerCollectionMethod] = s.[CustomerCollectionMethod]
		, d.[CustomerAmount] = s.[CustomerAmount]
		, d.[CustomerBlocked] = s.[CustomerBlocked]
		, d.[CustomerInvoiceCopies] = s.[CustomerInvoiceCopies]
		, d.[CustomerLastStatementNo] = s.[CustomerLastStatementNo]
		, d.[CustomerPrintStatements] = s.[CustomerPrintStatements]
		, d.[CustomerBill-toCustomerNo] = s.[CustomerBill-toCustomerNo]
		, d.[CustomerPriority] = s.[CustomerPriority]
		, d.[CustomerPaymentMethodCode] = s.[CustomerPaymentMethodCode]
		, d.[CustomerLastModifiedDateTime] = s.[CustomerLastModifiedDateTime]
		, d.[CustomerLastDateModified] = s.[CustomerLastDateModified]
		, d.[CustomerApplicationMethod] = s.[CustomerApplicationMethod]
		, d.[CustomerPricesIncludingVAT] = s.[CustomerPricesIncludingVAT]
		, d.[CustomerLocationCode] = s.[CustomerLocationCode]
		, d.[CustomerFaxNo] = s.[CustomerFaxNo]
		, d.[CustomerTelexAnswerBack] = s.[CustomerTelexAnswerBack]
		, d.[CustomerVATRegistrationNo] = s.[CustomerVATRegistrationNo]
		, d.[CustomerCombineShipments] = s.[CustomerCombineShipments]
		, d.[CustomerGenBusPostingGroup] = s.[CustomerGenBusPostingGroup]
		, d.[CustomerPicture] = s.[CustomerPicture]
		, d.[CustomerGLN] = s.[CustomerGLN]
		, d.[CustomerPostCode] = s.[CustomerPostCode]
		, d.[CustomerCounty] = s.[CustomerCounty]
		, d.[CustomerEORINumber] = s.[CustomerEORINumber]
		, d.[CustomerUseGLNinElectronicDocument] = s.[CustomerUseGLNinElectronicDocument]
		, d.[CustomerE-Mail] = s.[CustomerE-Mail]
		, d.[CustomerHomePage] = s.[CustomerHomePage]
		, d.[CustomerReminderTermsCode] = s.[CustomerReminderTermsCode]
		, d.[CustomerNoSeries] = s.[CustomerNoSeries]
		, d.[CustomerTaxAreaCode] = s.[CustomerTaxAreaCode]
		, d.[CustomerTaxLiable] = s.[CustomerTaxLiable]
		, d.[CustomerVATBusPostingGroup] = s.[CustomerVATBusPostingGroup]
		, d.[CustomerReserve] = s.[CustomerReserve]
		, d.[CustomerBlockPaymentTolerance] = s.[CustomerBlockPaymentTolerance]
		, d.[CustomerICPartnerCode] = s.[CustomerICPartnerCode]
		, d.[CustomerPrepayment] = s.[CustomerPrepayment]
		, d.[CustomerPartnerType] = s.[CustomerPartnerType]
		, d.[CustomerImage] = s.[CustomerImage]
		, d.[CustomerPrivacyBlocked] = s.[CustomerPrivacyBlocked]
		, d.[CustomerDisableSearchbyName] = s.[CustomerDisableSearchbyName]
		, d.[CustomerPreferredBankAccountCode] = s.[CustomerPreferredBankAccountCode]
		, d.[CustomerCashFlowPaymentTermsCode] = s.[CustomerCashFlowPaymentTermsCode]
		, d.[CustomerPrimaryContactNo] = s.[CustomerPrimaryContactNo]
		, d.[CustomerContactType] = s.[CustomerContactType]
		, d.[CustomerMobilePhoneNo] = s.[CustomerMobilePhoneNo]
		, d.[CustomerResponsibilityCenter] = s.[CustomerResponsibilityCenter]
		, d.[CustomerShippingAdvice] = s.[CustomerShippingAdvice]
		, d.[CustomerShippingTime] = s.[CustomerShippingTime]
		, d.[CustomerShippingAgentServiceCode] = s.[CustomerShippingAgentServiceCode]
		, d.[CustomerServiceZoneCode] = s.[CustomerServiceZoneCode]
		, d.[CustomerPriceCalculationMethod] = s.[CustomerPriceCalculationMethod]
		, d.[CustomerAllowLineDisc] = s.[CustomerAllowLineDisc]
		, d.[CustomerBaseCalendarCode] = s.[CustomerBaseCalendarCode]
		, d.[CustomerCopySell-toAddrtoQteFrom] = s.[CustomerCopySell-toAddrtoQteFrom]
		, d.[CustomerValidateEUVatRegNo] = s.[CustomerValidateEUVatRegNo]
		, d.[CustomerEANNo] = s.[CustomerEANNo]
		, d.[CustomerAccountCode] = s.[CustomerAccountCode]
		, d.[CustomerOIOUBLProfileCode] = s.[CustomerOIOUBLProfileCode]
		, d.[CustomerOIOUBLProfileCodeRequired] = s.[CustomerOIOUBLProfileCodeRequired]
		, d.[CustomerPriorityNOTO] = s.[CustomerPriorityNOTO]
		, d.[CustomerDelSOsWithRemQtyNOTO] = s.[CustomerDelSOsWithRemQtyNOTO]
		, d.[CustomerUseBarcode] = s.[CustomerUseBarcode]
		, d.[CustomerOldCustomerNo] = s.[CustomerOldCustomerNo]
		, d.[CustomerCalculateFreight] = s.[CustomerCalculateFreight]
		, d.[CustomerBatchPosting] = s.[CustomerBatchPosting]
		, d.[CustomerHashKey] = s.[CustomerHashKey]
		, d.[ADF_BatchId_Insert] = s.[ADF_BatchId_Insert]
		, d.[ADF_BatchId_Update] = s.[ADF_BatchId_Update]
		

	OPTION ( RECOMPILE );
 	
    
    -- Commit only if the transaction was started in this procedure
        IF @TranCounter = 0
            COMMIT TRANSACTION;
    END TRY
 
    BEGIN CATCH
 
    -- Only rollback if transaction was started in this procedure
        IF @TranCounter = 0
            ROLLBACK TRANSACTION;
    -- It's not our transaction but it's still OK
        ELSE
            IF XACT_STATE() = 1
                ROLLBACK TRANSACTION @SavePoint
    -- All hope is lost - rollback!
            ELSE
                IF XACT_STATE() = -1
                    ROLLBACK TRANSACTION;
 
        THROW;
        RETURN 1;
 
    END CATCH;
END

GO

