CREATE TABLE [dim_v1].[Item] (
    [ItemKey]                         INT              NOT NULL,
    [ItemCompanyID]                   INT              NOT NULL,
    [timestamp]                       VARBINARY (8)    NOT NULL,
    [ItemNo]                          NVARCHAR (20)    NOT NULL,
    [ItemNo2]                         NVARCHAR (20)    NOT NULL,
    [ItemDescription]                 NVARCHAR (100)   NOT NULL,
    [ItemSearchDescription]           NVARCHAR (100)   NOT NULL,
    [ItemDescription2]                NVARCHAR (50)    NOT NULL,
    [ItemBaseUnitofMeasure]           NVARCHAR (10)    NOT NULL,
    [ItemPriceUnitConversion]         INT              NOT NULL,
    [ItemType]                        INT              NOT NULL,
    [ItemInventoryPostingGroup]       NVARCHAR (20)    NOT NULL,
    [ItemShelfNo]                     NVARCHAR (10)    NOT NULL,
    [ItemItemDiscGroup]               NVARCHAR (20)    NOT NULL,
    [ItemAllowInvoiceDisc]            SMALLINT         NOT NULL,
    [ItemStatisticsGroup]             INT              NOT NULL,
    [ItemCommissionGroup]             INT              NOT NULL,
    [ItemUnitPrice]                   DECIMAL (38, 20) NOT NULL,
    [ItemPriceProfitCalculation]      INT              NOT NULL,
    [ItemProfit]                      DECIMAL (38, 20) NOT NULL,
    [ItemCostingMethod]               INT              NOT NULL,
    [ItemUnitCost]                    DECIMAL (38, 20) NOT NULL,
    [ItemStandardCost]                DECIMAL (38, 20) NOT NULL,
    [ItemLastDirectCost]              DECIMAL (38, 20) NOT NULL,
    [ItemIndirectCost]                DECIMAL (38, 20) NOT NULL,
    [ItemCostisAdjusted]              SMALLINT         NOT NULL,
    [ItemAllowOnlineAdjustment]       SMALLINT         NOT NULL,
    [ItemVendorNo]                    NVARCHAR (20)    NOT NULL,
    [ItemVendorItemNo]                NVARCHAR (50)    NOT NULL,
    [ItemLeadTimeCalculation]         VARCHAR (32)     NOT NULL,
    [ItemReorderPoint]                DECIMAL (38, 20) NOT NULL,
    [ItemMaximumInventory]            DECIMAL (38, 20) NOT NULL,
    [ItemReorderQuantity]             DECIMAL (38, 20) NOT NULL,
    [ItemAlternativeItemNo]           NVARCHAR (20)    NOT NULL,
    [ItemUnitListPrice]               DECIMAL (38, 20) NOT NULL,
    [ItemDutyDue]                     DECIMAL (38, 20) NOT NULL,
    [ItemDutyCode]                    NVARCHAR (10)    NOT NULL,
    [ItemGrossWeight]                 DECIMAL (38, 20) NOT NULL,
    [ItemNetWeight]                   DECIMAL (38, 20) NOT NULL,
    [ItemUnitsperParcel]              DECIMAL (38, 20) NOT NULL,
    [ItemUnitVolume]                  DECIMAL (38, 20) NOT NULL,
    [ItemDurability]                  NVARCHAR (10)    NOT NULL,
    [ItemFreightType]                 NVARCHAR (10)    NOT NULL,
    [ItemTariffNo]                    NVARCHAR (20)    NOT NULL,
    [ItemDutyUnitConversion]          DECIMAL (38, 20) NOT NULL,
    [ItemCountryRegionPurchasedCode]  NVARCHAR (10)    NOT NULL,
    [ItemBudgetQuantity]              DECIMAL (38, 20) NOT NULL,
    [ItemBudgetedAmount]              DECIMAL (38, 20) NOT NULL,
    [ItemBudgetProfit]                DECIMAL (38, 20) NOT NULL,
    [ItemBlocked]                     SMALLINT         NOT NULL,
    [ItemBlockReason]                 NVARCHAR (250)   NOT NULL,
    [ItemLastDateTimeModified]        DATETIME2 (7)    NULL,
    [ItemLastDateModified]            DATETIME2 (7)    NULL,
    [ItemLastTimeModified]            DATETIME2 (7)    NULL,
    [ItemPriceIncludesVAT]            SMALLINT         NOT NULL,
    [ItemVATBusPostingGr(Price)]      NVARCHAR (20)    NOT NULL,
    [ItemGenProdPostingGroup]         NVARCHAR (20)    NOT NULL,
    [ItemPicture]                     VARBINARY (MAX)  NOT NULL,
    [ItemCountryRegionofOriginCode]   NVARCHAR (10)    NOT NULL,
    [ItemAutomaticExtTexts]           SMALLINT         NOT NULL,
    [ItemNoSeries]                    NVARCHAR (20)    NOT NULL,
    [ItemTaxGroupCode]                NVARCHAR (20)    NOT NULL,
    [ItemVATProdPostingGroup]         NVARCHAR (20)    NOT NULL,
    [ItemReserve]                     INT              NOT NULL,
    [ItemGlobalDimension1Code]        NVARCHAR (20)    NOT NULL,
    [ItemGlobalDimension2Code]        NVARCHAR (20)    NOT NULL,
    [ItemStockoutWarning]             INT              NOT NULL,
    [ItemPreventNegativeInventory]    INT              NOT NULL,
    [ItemApplicationWkshUserID]       NVARCHAR (128)   NOT NULL,
    [ItemAssemblyPolicy]              INT              NOT NULL,
    [ItemGTIN]                        NVARCHAR (14)    NOT NULL,
    [ItemDefaultDeferralTemplateCode] NVARCHAR (10)    NOT NULL,
    [ItemLow-LevelCode]               INT              NOT NULL,
    [ItemLotSize]                     DECIMAL (38, 20) NOT NULL,
    [ItemSerialNos]                   NVARCHAR (20)    NOT NULL,
    [ItemLastUnitCostCalcDate]        DATETIME2 (7)    NULL,
    [ItemRolled-upMaterialCost]       DECIMAL (38, 20) NOT NULL,
    [ItemRolled-upCapacityCost]       DECIMAL (38, 20) NOT NULL,
    [ItemScrap]                       DECIMAL (38, 20) NOT NULL,
    [ItemInventoryValueZero]          SMALLINT         NOT NULL,
    [ItemDiscreteOrderQuantity]       INT              NOT NULL,
    [ItemMinimumOrderQuantity]        DECIMAL (38, 20) NOT NULL,
    [ItemMaximumOrderQuantity]        DECIMAL (38, 20) NOT NULL,
    [ItemSafetyStockQuantity]         DECIMAL (38, 20) NOT NULL,
    [ItemOrderMultiple]               DECIMAL (38, 20) NOT NULL,
    [ItemSafetyLeadTime]              VARCHAR (32)     NOT NULL,
    [ItemFlushingMethod]              INT              NOT NULL,
    [ItemReplenishmentSystem]         INT              NOT NULL,
    [ItemRoundingPrecision]           DECIMAL (38, 20) NOT NULL,
    [ItemSalesUnitofMeasure]          NVARCHAR (10)    NOT NULL,
    [ItemPurchUnitofMeasure]          NVARCHAR (10)    NOT NULL,
    [ItemTimeBucket]                  VARCHAR (32)     NOT NULL,
    [ItemReorderingPolicy]            INT              NOT NULL,
    [ItemIncludeInventory]            SMALLINT         NOT NULL,
    [ItemManufacturingPolicy]         INT              NOT NULL,
    [ItemReschedulingPeriod]          VARCHAR (32)     NOT NULL,
    [ItemLotAccumulationPeriod]       VARCHAR (32)     NOT NULL,
    [ItemDampenerPeriod]              VARCHAR (32)     NOT NULL,
    [ItemDampenerQuantity]            DECIMAL (38, 20) NOT NULL,
    [ItemOverflowLevel]               DECIMAL (38, 20) NOT NULL,
    [ItemManufacturerCode]            NVARCHAR (10)    NOT NULL,
    [ItemItemCategoryCode]            NVARCHAR (20)    NOT NULL,
    [ItemCreatedFromNonstockItem]     SMALLINT         NOT NULL,
    [ItemProductGroupCode]            NVARCHAR (16)    NULL,
    [ItemPurchasingCode]              NVARCHAR (10)    NOT NULL,
    [ItemServiceItemGroup]            NVARCHAR (10)    NOT NULL,
    [ItemItemTrackingCode]            NVARCHAR (10)    NOT NULL,
    [ItemLotNos]                      NVARCHAR (20)    NOT NULL,
    [ItemExpirationCalculation]       VARCHAR (32)     NOT NULL,
    [ItemWarehouseClassCode]          NVARCHAR (10)    NOT NULL,
    [ItemSpecialEquipmentCode]        NVARCHAR (10)    NOT NULL,
    [ItemPut-awayTemplateCode]        NVARCHAR (10)    NOT NULL,
    [ItemPut-awayUnitofMeasureCode]   NVARCHAR (10)    NOT NULL,
    [ItemPhysInvtCountingPeriodCode]  NVARCHAR (10)    NOT NULL,
    [ItemLastCountingPeriodUpdate]    DATETIME2 (7)    NULL,
    [ItemUseCross-Docking]            SMALLINT         NOT NULL,
    [ItemNextCountingStartDate]       DATETIME2 (7)    NULL,
    [ItemNextCountingEndDate]         DATETIME2 (7)    NULL,
    [ItemSalesBlocked]                SMALLINT         NOT NULL,
    [ItemPurchasingBlocked]           SMALLINT         NOT NULL,
    [ItemItemCategoryId]              NVARCHAR (36)    NOT NULL,
    [ItemOver-ReceiptCode]            NVARCHAR (20)    NOT NULL,
    [ItemRoutingNo]                   NVARCHAR (20)    NOT NULL,
    [ItemProductionBOMNo]             NVARCHAR (20)    NOT NULL,
    [ItemSingle-LevelMaterialCost]    DECIMAL (38, 20) NOT NULL,
    [ItemSingle-LevelCapacityCost]    DECIMAL (38, 20) NOT NULL,
    [ItemSingle-LevelSubcontrdCost]   DECIMAL (38, 20) NOT NULL,
    [ItemSingle-LevelCapOvhdCost]     DECIMAL (38, 20) NOT NULL,
    [ItemSingle-LevelMfgOvhdCost]     DECIMAL (38, 20) NOT NULL,
    [ItemOverheadRate]                DECIMAL (38, 20) NOT NULL,
    [ItemRolled-upSubcontractedCost]  DECIMAL (38, 20) NOT NULL,
    [ItemRolled-upMfgOvhdCost]        DECIMAL (38, 20) NOT NULL,
    [ItemRolled-upCapOverheadCost]    DECIMAL (38, 20) NOT NULL,
    [ItemOrderTrackingPolicy]         INT              NOT NULL,
    [ItemCritical]                    SMALLINT         NOT NULL,
    [ItemCommonItemNo]                NVARCHAR (20)    NOT NULL,
    [ItemLabelBarcode]                NVARCHAR (20)    NOT NULL,
    [ItemABCDCategory]                NVARCHAR (20)    NOT NULL,
    [ItemBrand]                       NVARCHAR (50)    NOT NULL,
    [ItemProductLineCode]             NVARCHAR (50)    NOT NULL,
    [ItemProductUsage]                NVARCHAR (50)    NOT NULL,
    [ItemProdGroupCode]               NVARCHAR (50)    NOT NULL,
    [ItemSize]                        NVARCHAR (50)    NOT NULL,
    [ItemSizeUnit]                    NVARCHAR (10)    NOT NULL,
    [ItemFeature]                     NVARCHAR (50)    NOT NULL,
    [ItemPackingMethod]               NVARCHAR (50)    NOT NULL,
    [ItemCoating]                     NVARCHAR (50)    NOT NULL,
    [ItemQuality]                     INT              NOT NULL,
    [ItemWithLid]                     SMALLINT         NOT NULL,
    [ItemWeightClassificationNOTO]    INT              NOT NULL,
    [ItemCalculatedAvailableNOTO]     DECIMAL (38, 20) NOT NULL,
    [ItemCalculatedAvailableExtNOTO]  DECIMAL (38, 20) NOT NULL,
    [ItemCalculatedAvailableDateNOTO] DATETIME2 (7)    NULL,
    [ItemBodyType]                    NVARCHAR (20)    NOT NULL,
    [ItemBOMQuantity]                 DECIMAL (38, 20) NOT NULL,
    [ItemHashKey]                     NVARCHAR (200)   NOT NULL,
    [ADF_BatchId_Insert]              BIGINT           CONSTRAINT [DF_dim_Item_InsertBacthId] DEFAULT ((0)) NOT NULL,
    [ADF_BatchId_Update]              BIGINT           CONSTRAINT [DF_dim_Item_UpdateBacthId] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dim_Item] PRIMARY KEY CLUSTERED ([ItemKey] ASC),
    CONSTRAINT [UQ_dim_Item] UNIQUE NONCLUSTERED ([ItemCompanyID] ASC, [ItemNo] ASC)
);


GO

