CREATE view GlTest as
SELECT TOP (1000) [CompanyID]
      ,[timestamp]
      ,[Entry No_]
      ,[G_L Account No_]
      ,[Posting Date]
      ,[Document Type]
      ,[Document No_]
      ,[Description]
      ,[Bal_ Account No_]
      ,[Amount]
      ,[Global Dimension 1 Code]
      ,[Global Dimension 2 Code]
      ,[User ID]
      ,[Source Code]
      ,[System-Created Entry]
      ,[Prior-Year Entry]
      ,[Job No_]
      ,[Quantity]
      ,[VAT Amount]
      ,[Business Unit Code]
      ,[Journal Batch Name]
      ,[Reason Code]
      ,[Gen_ Posting Type]
      ,[Gen_ Bus_ Posting Group]
      ,[Gen_ Prod_ Posting Group]
      ,[Bal_ Account Type]
      ,[Transaction No_]
      ,[Debit Amount]
      ,[Credit Amount]
      ,[Document Date]
      ,[External Document No_]
      ,[Source Type]
      ,[Source No_]
      ,[No_ Series]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[Tax Group Code]
      ,[Use Tax]
      ,[VAT Bus_ Posting Group]
      ,[VAT Prod_ Posting Group]
      ,[Additional-Currency Amount]
      ,[Add_-Currency Debit Amount]
      ,[Add_-Currency Credit Amount]
      ,[Close Income Statement Dim_ ID]
      ,[IC Partner Code]
      ,[Reversed]
      ,[Reversed by Entry No_]
      ,[Reversed Entry No_]
      ,[Prod_ Order No_]
      ,[FA Entry Type]
      ,[FA Entry No_]
      ,[Marketing %]
      ,[Administration Cost %]
      ,[Annual Bonus %]
      ,[Pmt_ Discount %]
      ,[Shop Bonus %]
      ,[PipelineName]
      ,[PipelineRunId]
      ,[PipelineTriggerTime]
  FROM [stg_navdb].[GLEntry]
  WHERE [Posting Date]>='01-01-2023' and [CompanyID]=1

GO

