CREATE VIEW [dbo].[PL_ValueEntry]
AS
SELECT DISTINCT [ve].[CompanyID]
               ,[ve].[timestamp]
               ,[ve].[Entry No_]
               ,[ve].[Item No_]
               ,[ve].[Posting Date]
               ,[ve].[Item Ledger Entry Type]
               ,[ve].[Source No_] AS [Cust No]
               ,[ve].[Document No_]
               ,[ve].[Description]
               ,[ve].[Location Code]
               ,[ve].[Inventory Posting Group]
               ,[ve].[Source Posting Group]
               ,[ve].[Item Ledger Entry No_]
               ,[ve].[Valued Quantity]
               ,[ve].[Item Ledger Entry Quantity]
               ,[ve].[Invoiced Quantity]
               ,[ve].[Cost per Unit]
               ,[ve].[Sales Amount (Actual)]
               ,[ve].[Salespers__Purch_ Code]
               ,[ve].[Discount Amount]
               ,[ve].[User ID]
               ,[ve].[Source Code]
               ,[ve].[Applies-to Entry]
               ,[ve].[Global Dimension 1 Code]
               ,[ve].[Global Dimension 2 Code]
               ,[ve].[Source Type]
               ,[ve].[Cost Amount (Actual)]
               ,[ve].[Cost Posted to G_L]
               ,[ve].[Reason Code]
               ,[ve].[Drop Shipment]
               ,[ve].[Journal Batch Name]
               ,[ve].[Gen_ Bus_ Posting Group]
               ,[ve].[Gen_ Prod_ Posting Group]
               ,[ve].[Document Date]
               ,[ve].[External Document No_]
               ,[ve].[Cost Amount (Actual) (ACY)]
               ,[ve].[Cost Posted to G_L (ACY)]
               ,[ve].[Cost per Unit (ACY)]
               ,[ve].[Document Type]
               ,[ve].[Document Line No_]
               ,[ve].[Expected Cost]
               ,[ve].[Item Charge No_]
               ,[ve].[Valued By Average Cost]
               ,[ve].[Partial Revaluation]
               ,[ve].[Inventoriable]
               ,[ve].[Valuation Date]
               ,[ve].[Entry Type]
               ,[ve].[Variance Type]
               ,[ve].[Purchase Amount (Actual)]
               ,[ve].[Purchase Amount (Expected)]
               ,[ve].[Sales Amount (Expected)]
               ,[ve].[Cost Amount (Expected)]
               ,[ve].[Cost Amount (Non-Invtbl_)]
               ,[ve].[Cost Amount (Expected) (ACY)]
               ,[ve].[Cost Amount (Non-Invtbl_)(ACY)]
               ,[ve].[Expected Cost Posted to G_L]
               ,[ve].[Exp_ Cost Posted to G_L (ACY)]
               ,[ve].[Job No_]
               ,[ve].[Job Task No_]
               ,[ve].[Prod_ Order No_]
               ,[ve].[Variant Code]
               ,[ve].[Adjustment]
               ,[ve].[Average Cost Exception]
               ,[ve].[Capacity Ledger Entry No_]
               ,[ve].[Type]
               ,[ve].[No_]
               ,[ve].[Prod_ Order Line No_]
               ,[ve].[Return Reason Code]
               ,[ve].[YearCode Text]
               ,[ve].[Item Category Code]
               ,[ve].[Product Group Code]
               ,[ve].[Unit Cost II (LCY)]
               ,[ve].[Product Line Code]
               ,[ve].[Item Brand]
               ,[ve].[Campaign No_]
               ,[ve].[Normal Net Price]
               ,[ve].[Normal Net Amount]
               ,[ve].[PipelineName]
               ,[ve].[PipelineRunId]
               ,[ve].[PipelineTriggerTime]
               ,[old].[Old Customer No_]
               ,[old].[No_] AS [BC Cust NO]
FROM [stg_navdb].[ValueEntry] AS [ve]
LEFT JOIN [stg_bc].[CustomerNotora] AS [old]
ON  [ve].[Source No_] = [old].[Old Customer No_]
AND [ve].[CompanyID] = [old].[CompanyID]
WHERE [ve].[Posting Date] >= '01-01-2022'
AND   [ve].[Item Ledger Entry Type] = 1
AND   [ve].[CompanyID] = 1;

GO

