CREATE VIEW [PLPurchase Orders]
AS
SELECT [ph].[No_] AS [Orderno]
      ,[ph].[Buy-from Vendor No_]
      ,[ph].[Buy-from Vendor Name]
      ,[plline].[Type]
      ,[plline].[No_]
      ,[plline].[Location Code]
      ,[plline].[Expected Receipt Date]
      ,[plline].[Description]
      ,[plline].[Quantity]
      ,[plline].[Outstanding Quantity]
      ,[plline].[Direct Unit Cost]
      ,[plline].[Unit Cost (LCY)]
      ,[plline].[Unit Price (LCY)]
      ,[plline].[Outstanding Amount]
      ,[plline].[Currency Code]
      ,[plline].[Outstanding Amount (LCY)]
      ,[plline].[Unit Cost]
      ,[plline].[Requested Receipt Date]
      ,[plline].[Promised Receipt Date]
      ,[plline].[Order Date]
      ,[plline].[Planned Receipt Date]
      ,[plline].[Completely Received]
      ,[plline].[Drop Shipment]
      ,[plline].[Sales Order No_]
      ,[plline].[Qty_ to Receive]
      ,[ph].[Order Date] AS [H_OrderDate]
FROM [stg_bc].[PurchaseHeader] AS [ph]
INNER JOIN [stg_bc].[PurchaseLine] AS [plline]
ON [ph].[No_] = [plline].[Document No_];

GO

