CREATE TABLE [stg_bc].[CapacityLedgerEntry] (
    [timestamp]                     VARBINARY (8)      NOT NULL,
    [Entry No_]                     INT                NOT NULL,
    [No_]                           NVARCHAR (20)      NOT NULL,
    [Posting Date]                  DATETIME           NOT NULL,
    [Type]                          INT                NOT NULL,
    [Document No_]                  NVARCHAR (20)      NOT NULL,
    [Description]                   NVARCHAR (100)     NOT NULL,
    [Operation No_]                 NVARCHAR (10)      NOT NULL,
    [Work Center No_]               NVARCHAR (20)      NOT NULL,
    [Quantity]                      DECIMAL (38, 20)   NOT NULL,
    [Setup Time]                    DECIMAL (38, 20)   NOT NULL,
    [Run Time]                      DECIMAL (38, 20)   NOT NULL,
    [Stop Time]                     DECIMAL (38, 20)   NOT NULL,
    [Invoiced Quantity]             DECIMAL (38, 20)   NOT NULL,
    [Output Quantity]               DECIMAL (38, 20)   NOT NULL,
    [Scrap Quantity]                DECIMAL (38, 20)   NOT NULL,
    [Concurrent Capacity]           DECIMAL (38, 20)   NOT NULL,
    [Cap_ Unit of Measure Code]     NVARCHAR (10)      NOT NULL,
    [Qty_ per Cap_ Unit of Measure] DECIMAL (38, 20)   NOT NULL,
    [Global Dimension 1 Code]       NVARCHAR (20)      NOT NULL,
    [Global Dimension 2 Code]       NVARCHAR (20)      NOT NULL,
    [Last Output Line]              TINYINT            NOT NULL,
    [Completely Invoiced]           TINYINT            NOT NULL,
    [Starting Time]                 DATETIME           NOT NULL,
    [Ending Time]                   DATETIME           NOT NULL,
    [Routing No_]                   NVARCHAR (20)      NOT NULL,
    [Routing Reference No_]         INT                NOT NULL,
    [Item No_]                      NVARCHAR (20)      NOT NULL,
    [Variant Code]                  NVARCHAR (10)      NOT NULL,
    [Unit of Measure Code]          NVARCHAR (10)      NOT NULL,
    [Qty_ per Unit of Measure]      DECIMAL (38, 20)   NOT NULL,
    [Document Date]                 DATETIME           NOT NULL,
    [External Document No_]         NVARCHAR (35)      NOT NULL,
    [Stop Code]                     NVARCHAR (10)      NOT NULL,
    [Scrap Code]                    NVARCHAR (10)      NOT NULL,
    [Work Center Group Code]        NVARCHAR (10)      NOT NULL,
    [Work Shift Code]               NVARCHAR (10)      NOT NULL,
    [Subcontracting]                TINYINT            NOT NULL,
    [Order Type]                    INT                NOT NULL,
    [Order No_]                     NVARCHAR (20)      NOT NULL,
    [Order Line No_]                INT                NOT NULL,
    [Dimension Set ID]              INT                NOT NULL,
    [$systemId]                     NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]              DATETIME           NOT NULL,
    [$systemCreatedBy]              NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]             DATETIME           NOT NULL,
    [$systemModifiedBy]             NVARCHAR (36)      NOT NULL,
    [PipelineName]                  NVARCHAR (200)     CONSTRAINT [DF_CapacityLedgerEntry_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                 NVARCHAR (36)      CONSTRAINT [DF_CapacityLedgerEntry_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]           DATETIMEOFFSET (0) CONSTRAINT [DF_CapacityLedgerEntry_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                     INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_CapacityLedgerEntry] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Entry No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

