CREATE TABLE [stg_bc].[CompanyInformation] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Primary Key]                    NVARCHAR (10)      NOT NULL,
    [Name]                           NVARCHAR (100)     NOT NULL,
    [Name 2]                         NVARCHAR (50)      NOT NULL,
    [Address]                        NVARCHAR (100)     NOT NULL,
    [Address 2]                      NVARCHAR (50)      NOT NULL,
    [City]                           NVARCHAR (30)      NOT NULL,
    [Phone No_]                      NVARCHAR (30)      NOT NULL,
    [Phone No_ 2]                    NVARCHAR (30)      NOT NULL,
    [Telex No_]                      NVARCHAR (30)      NOT NULL,
    [Fax No_]                        NVARCHAR (30)      NOT NULL,
    [Giro No_]                       NVARCHAR (20)      NOT NULL,
    [Bank Name]                      NVARCHAR (100)     NOT NULL,
    [Bank Branch No_]                NVARCHAR (20)      NOT NULL,
    [Bank Account No_]               NVARCHAR (30)      NOT NULL,
    [Payment Routing No_]            NVARCHAR (20)      NOT NULL,
    [Customs Permit No_]             NVARCHAR (10)      NOT NULL,
    [Customs Permit Date]            DATETIME           NOT NULL,
    [VAT Registration No_]           NVARCHAR (20)      NOT NULL,
    [Registration No_]               NVARCHAR (20)      NOT NULL,
    [Telex Answer Back]              NVARCHAR (20)      NOT NULL,
    [Ship-to Name]                   NVARCHAR (100)     NOT NULL,
    [Ship-to Name 2]                 NVARCHAR (50)      NOT NULL,
    [Ship-to Address]                NVARCHAR (100)     NOT NULL,
    [Ship-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Ship-to City]                   NVARCHAR (30)      NOT NULL,
    [Ship-to Contact]                NVARCHAR (100)     NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Picture]                        VARBINARY (MAX)    NULL,
    [Post Code]                      NVARCHAR (20)      NOT NULL,
    [County]                         NVARCHAR (30)      NOT NULL,
    [Ship-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Ship-to County]                 NVARCHAR (30)      NOT NULL,
    [E-Mail]                         NVARCHAR (80)      NOT NULL,
    [Home Page]                      NVARCHAR (80)      NOT NULL,
    [Country_Region Code]            NVARCHAR (10)      NOT NULL,
    [Ship-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [IBAN]                           NVARCHAR (50)      NOT NULL,
    [SWIFT Code]                     NVARCHAR (20)      NOT NULL,
    [Industrial Classification]      NVARCHAR (30)      NOT NULL,
    [IC Partner Code]                NVARCHAR (20)      NOT NULL,
    [IC Inbox Type]                  INT                NOT NULL,
    [IC Inbox Details]               NVARCHAR (250)     NOT NULL,
    [Auto_ Send Transactions]        TINYINT            NOT NULL,
    [System Indicator]               INT                NOT NULL,
    [Custom System Indicator Text]   NVARCHAR (250)     NOT NULL,
    [System Indicator Style]         INT                NOT NULL,
    [Allow Blank Payment Info_]      TINYINT            NOT NULL,
    [Contact Person]                 NVARCHAR (50)      NOT NULL,
    [GLN]                            NVARCHAR (13)      NOT NULL,
    [EORI Number]                    NVARCHAR (40)      NOT NULL,
    [Use GLN in Electronic Document] TINYINT            NOT NULL,
    [Picture - Last Mod_ Date Time]  DATETIME           NOT NULL,
    [Last Modified Date Time]        DATETIME           NOT NULL,
    [Created DateTime]               DATETIME           NOT NULL,
    [Demo Company]                   TINYINT            NOT NULL,
    [Alternative Language Code]      NVARCHAR (10)      NOT NULL,
    [Brand Color Value]              NVARCHAR (10)      NOT NULL,
    [Brand Color Code]               NVARCHAR (20)      NOT NULL,
    [Responsibility Center]          NVARCHAR (10)      NOT NULL,
    [Check-Avail_ Period Calc_]      VARCHAR (32)       NOT NULL,
    [Check-Avail_ Time Bucket]       INT                NOT NULL,
    [Base Calendar Code]             NVARCHAR (10)      NOT NULL,
    [Cal_ Convergence Time Frame]    VARCHAR (32)       NOT NULL,
    [Show Chart On RoleCenter]       TINYINT            NOT NULL,
    [Sync with O365 Bus_ profile]    TINYINT            NOT NULL,
    [Id]                             NVARCHAR (36)      NOT NULL,
    [Bank Creditor No_]              NVARCHAR (8)       NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_CompanyInformation_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_CompanyInformation_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_CompanyInformation_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_CompanyInformation] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Primary Key] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

