CREATE TABLE [stg_bc].[Currency] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Code]                           NVARCHAR (10)      NOT NULL,
    [Last Date Modified]             DATETIME           NOT NULL,
    [Last Date Adjusted]             DATETIME           NOT NULL,
    [ISO Code]                       NVARCHAR (3)       NOT NULL,
    [ISO Numeric Code]               NVARCHAR (3)       NOT NULL,
    [Unrealized Gains Acc_]          NVARCHAR (20)      NOT NULL,
    [Realized Gains Acc_]            NVARCHAR (20)      NOT NULL,
    [Unrealized Losses Acc_]         NVARCHAR (20)      NOT NULL,
    [Realized Losses Acc_]           NVARCHAR (20)      NOT NULL,
    [Invoice Rounding Precision]     DECIMAL (38, 20)   NOT NULL,
    [Invoice Rounding Type]          INT                NOT NULL,
    [Amount Rounding Precision]      DECIMAL (38, 20)   NOT NULL,
    [Unit-Amount Rounding Precision] DECIMAL (38, 20)   NOT NULL,
    [Description]                    NVARCHAR (30)      NOT NULL,
    [Amount Decimal Places]          NVARCHAR (5)       NOT NULL,
    [Unit-Amount Decimal Places]     NVARCHAR (5)       NOT NULL,
    [Realized G_L Gains Account]     NVARCHAR (20)      NOT NULL,
    [Realized G_L Losses Account]    NVARCHAR (20)      NOT NULL,
    [Appln_ Rounding Precision]      DECIMAL (38, 20)   NOT NULL,
    [EMU Currency]                   TINYINT            NOT NULL,
    [Currency Factor]                DECIMAL (38, 20)   NOT NULL,
    [Residual Gains Account]         NVARCHAR (20)      NOT NULL,
    [Residual Losses Account]        NVARCHAR (20)      NOT NULL,
    [Conv_ LCY Rndg_ Debit Acc_]     NVARCHAR (20)      NOT NULL,
    [Conv_ LCY Rndg_ Credit Acc_]    NVARCHAR (20)      NOT NULL,
    [Max_ VAT Difference Allowed]    DECIMAL (38, 20)   NOT NULL,
    [VAT Rounding Type]              INT                NOT NULL,
    [Payment Tolerance _]            DECIMAL (38, 20)   NOT NULL,
    [Max_ Payment Tolerance Amount]  DECIMAL (38, 20)   NOT NULL,
    [Symbol]                         NVARCHAR (10)      NOT NULL,
    [Last Modified Date Time]        DATETIME           NOT NULL,
    [Id]                             NVARCHAR (36)      NOT NULL,
    [OIOUBL Currency Code]           NVARCHAR (10)      NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_Currency_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_Currency_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_Currency_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_Currency] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Code] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

