CREATE TABLE [stg_bc].[Customer] (
    [timestamp]                      VARBINARY (8)    NOT NULL,
    [No_]                            NVARCHAR (20)    NOT NULL,
    [Name]                           NVARCHAR (100)   NULL,
    [Search Name]                    NVARCHAR (100)   NULL,
    [Name 2]                         NVARCHAR (50)    NULL,
    [Address]                        NVARCHAR (100)   NULL,
    [Address 2]                      NVARCHAR (50)    NULL,
    [City]                           NVARCHAR (30)    NULL,
    [Contact]                        NVARCHAR (100)   NULL,
    [Phone No_]                      NVARCHAR (30)    NULL,
    [Telex No_]                      NVARCHAR (20)    NULL,
    [Document Sending Profile]       NVARCHAR (20)    NULL,
    [Ship-to Code]                   NVARCHAR (10)    NULL,
    [Our Account No_]                NVARCHAR (20)    NULL,
    [Territory Code]                 NVARCHAR (10)    NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)    NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)    NULL,
    [Chain Name]                     NVARCHAR (10)    NULL,
    [Budgeted Amount]                DECIMAL (38, 20) NULL,
    [Credit Limit (LCY)]             DECIMAL (38, 20) NULL,
    [Customer Posting Group]         NVARCHAR (20)    NULL,
    [Currency Code]                  NVARCHAR (10)    NULL,
    [Customer Price Group]           NVARCHAR (10)    NULL,
    [Language Code]                  NVARCHAR (10)    NULL,
    [Statistics Group]               INT              NULL,
    [Payment Terms Code]             NVARCHAR (10)    NULL,
    [Fin_ Charge Terms Code]         NVARCHAR (10)    NULL,
    [Salesperson Code]               NVARCHAR (20)    NULL,
    [Shipment Method Code]           NVARCHAR (10)    NULL,
    [Shipping Agent Code]            NVARCHAR (10)    NULL,
    [Place of Export]                NVARCHAR (20)    NULL,
    [Invoice Disc_ Code]             NVARCHAR (20)    NULL,
    [Customer Disc_ Group]           NVARCHAR (20)    NULL,
    [Country_Region Code]            NVARCHAR (10)    NULL,
    [Collection Method]              NVARCHAR (20)    NULL,
    [Amount]                         DECIMAL (38, 20) NULL,
    [Blocked]                        INT              NULL,
    [Invoice Copies]                 INT              NULL,
    [Last Statement No_]             INT              NULL,
    [Print Statements]               TINYINT          NULL,
    [Bill-to Customer No_]           NVARCHAR (20)    NULL,
    [Priority]                       INT              NULL,
    [Payment Method Code]            NVARCHAR (10)    NULL,
    [Last Modified Date Time]        DATETIME         NULL,
    [Last Date Modified]             DATETIME         NULL,
    [Application Method]             INT              NULL,
    [Prices Including VAT]           TINYINT          NULL,
    [Location Code]                  NVARCHAR (10)    NULL,
    [Fax No_]                        NVARCHAR (30)    NULL,
    [Telex Answer Back]              NVARCHAR (20)    NULL,
    [VAT Registration No_]           NVARCHAR (20)    NULL,
    [Combine Shipments]              TINYINT          NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)    NULL,
    [Picture]                        VARBINARY (MAX)  NULL,
    [GLN]                            NVARCHAR (13)    NULL,
    [Post Code]                      NVARCHAR (20)    NULL,
    [County]                         NVARCHAR (30)    NULL,
    [EORI Number]                    NVARCHAR (40)    NULL,
    [Use GLN in Electronic Document] TINYINT          NULL,
    [E-Mail]                         NVARCHAR (80)    NULL,
    [Home Page]                      NVARCHAR (80)    NULL,
    [Reminder Terms Code]            NVARCHAR (10)    NULL,
    [No_ Series]                     NVARCHAR (20)    NULL,
    [Tax Area Code]                  NVARCHAR (20)    NULL,
    [Tax Liable]                     TINYINT          NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)    NULL,
    [Reserve]                        INT              NULL,
    [Block Payment Tolerance]        TINYINT          NULL,
    [IC Partner Code]                NVARCHAR (20)    NULL,
    [Prepayment _]                   DECIMAL (38, 20) NULL,
    [Partner Type]                   INT              NULL,
    [Image]                          UNIQUEIDENTIFIER NULL,
    [Privacy Blocked]                TINYINT          NULL,
    [Disable Search by Name]         TINYINT          NULL,
    [Preferred Bank Account Code]    NVARCHAR (20)    NULL,
    [Cash Flow Payment Terms Code]   NVARCHAR (10)    NULL,
    [Primary Contact No_]            NVARCHAR (20)    NULL,
    [Contact Type]                   INT              NULL,
    [Mobile Phone No_]               NVARCHAR (30)    NULL,
    [Responsibility Center]          NVARCHAR (10)    NULL,
    [Shipping Advice]                INT              NULL,
    [Shipping Time]                  VARCHAR (32)     NULL,
    [Shipping Agent Service Code]    NVARCHAR (10)    NULL,
    [Service Zone Code]              NVARCHAR (10)    NULL,
    [Price Calculation Method]       INT              NULL,
    [Allow Line Disc_]               TINYINT          NULL,
    [Base Calendar Code]             NVARCHAR (10)    NULL,
    [Copy Sell-to Addr_ to Qte From] INT              NULL,
    [Validate EU Vat Reg_ No_]       TINYINT          NULL,
    [Id]                             UNIQUEIDENTIFIER NULL,
    [Currency Id]                    UNIQUEIDENTIFIER NULL,
    [Payment Terms Id]               UNIQUEIDENTIFIER NULL,
    [Shipment Method Id]             UNIQUEIDENTIFIER NULL,
    [Payment Method Id]              UNIQUEIDENTIFIER NULL,
    [Tax Area ID]                    UNIQUEIDENTIFIER NULL,
    [Contact ID]                     UNIQUEIDENTIFIER NULL,
    [Contact Graph Id]               NVARCHAR (250)   NULL,
    [EAN No_]                        NVARCHAR (13)    NULL,
    [Account Code]                   NVARCHAR (30)    NULL,
    [OIOUBL Profile Code]            NVARCHAR (10)    NULL,
    [OIOUBL Profile Code Required]   TINYINT          NULL,
    [PipelineName]                   NVARCHAR (MAX)   NULL,
    [PipelineRunId]                  NVARCHAR (MAX)   NULL,
    [PipelineTriggerTime]            NVARCHAR (MAX)   NULL,
    [CompanyID]                      INT              NOT NULL,
    CONSTRAINT [PK_stg_bc_Customer] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_bc_Customer_timestamp]
    ON [stg_bc].[Customer]([CompanyID] ASC, [timestamp] ASC);


GO

