CREATE TABLE [stg_bc].[Employee] (
    [timestamp]                VARBINARY (8)      NOT NULL,
    [No_]                      NVARCHAR (20)      NOT NULL,
    [First Name]               NVARCHAR (30)      NOT NULL,
    [Middle Name]              NVARCHAR (30)      NOT NULL,
    [Last Name]                NVARCHAR (30)      NOT NULL,
    [Initials]                 NVARCHAR (30)      NOT NULL,
    [Job Title]                NVARCHAR (30)      NOT NULL,
    [Search Name]              NVARCHAR (250)     NOT NULL,
    [Address]                  NVARCHAR (100)     NOT NULL,
    [Address 2]                NVARCHAR (50)      NOT NULL,
    [City]                     NVARCHAR (30)      NOT NULL,
    [Post Code]                NVARCHAR (20)      NOT NULL,
    [County]                   NVARCHAR (30)      NOT NULL,
    [Phone No_]                NVARCHAR (30)      NOT NULL,
    [Mobile Phone No_]         NVARCHAR (30)      NOT NULL,
    [E-Mail]                   NVARCHAR (80)      NOT NULL,
    [Alt_ Address Code]        NVARCHAR (10)      NOT NULL,
    [Alt_ Address Start Date]  DATETIME           NOT NULL,
    [Alt_ Address End Date]    DATETIME           NOT NULL,
    [Picture]                  VARBINARY (MAX)    NULL,
    [Birth Date]               DATETIME           NOT NULL,
    [Social Security No_]      NVARCHAR (30)      NOT NULL,
    [Union Code]               NVARCHAR (10)      NOT NULL,
    [Union Membership No_]     NVARCHAR (30)      NOT NULL,
    [Gender]                   INT                NOT NULL,
    [Country_Region Code]      NVARCHAR (10)      NOT NULL,
    [Manager No_]              NVARCHAR (20)      NOT NULL,
    [Emplymt_ Contract Code]   NVARCHAR (10)      NOT NULL,
    [Statistics Group Code]    NVARCHAR (10)      NOT NULL,
    [Employment Date]          DATETIME           NOT NULL,
    [Status]                   INT                NOT NULL,
    [Inactive Date]            DATETIME           NOT NULL,
    [Cause of Inactivity Code] NVARCHAR (10)      NOT NULL,
    [Termination Date]         DATETIME           NOT NULL,
    [Grounds for Term_ Code]   NVARCHAR (10)      NOT NULL,
    [Global Dimension 1 Code]  NVARCHAR (20)      NOT NULL,
    [Global Dimension 2 Code]  NVARCHAR (20)      NOT NULL,
    [Resource No_]             NVARCHAR (20)      NOT NULL,
    [Last Date Modified]       DATETIME           NOT NULL,
    [Extension]                NVARCHAR (30)      NOT NULL,
    [Pager]                    NVARCHAR (30)      NOT NULL,
    [Fax No_]                  NVARCHAR (30)      NOT NULL,
    [Company E-Mail]           NVARCHAR (80)      NOT NULL,
    [Title]                    NVARCHAR (30)      NOT NULL,
    [Salespers__Purch_ Code]   NVARCHAR (20)      NOT NULL,
    [No_ Series]               NVARCHAR (20)      NOT NULL,
    [Last Modified Date Time]  DATETIME           NOT NULL,
    [Employee Posting Group]   NVARCHAR (20)      NOT NULL,
    [Bank Branch No_]          NVARCHAR (20)      NOT NULL,
    [Bank Account No_]         NVARCHAR (30)      NOT NULL,
    [IBAN]                     NVARCHAR (50)      NOT NULL,
    [SWIFT Code]               NVARCHAR (20)      NOT NULL,
    [Application Method]       INT                NOT NULL,
    [Image]                    NVARCHAR (36)      NOT NULL,
    [Privacy Blocked]          TINYINT            NOT NULL,
    [Cost Center Code]         NVARCHAR (20)      NOT NULL,
    [Cost Object Code]         NVARCHAR (20)      NOT NULL,
    [Id]                       NVARCHAR (36)      NOT NULL,
    [$systemId]                NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]         DATETIME           NOT NULL,
    [$systemCreatedBy]         NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]        DATETIME           NOT NULL,
    [$systemModifiedBy]        NVARCHAR (36)      NOT NULL,
    [PipelineName]             NVARCHAR (200)     CONSTRAINT [DF_Employee_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]            NVARCHAR (36)      CONSTRAINT [DF_Employee_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]      DATETIMEOFFSET (0) CONSTRAINT [DF_Employee_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_Employee] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

