CREATE TABLE [stg_bc].[FALedgerEntry] (
    [timestamp]                      VARBINARY (8)    NOT NULL,
    [Entry No_]                      INT              NOT NULL,
    [G_L Entry No_]                  INT              NULL,
    [FA No_]                         NVARCHAR (20)    NULL,
    [FA Posting Date]                DATETIME         NULL,
    [Posting Date]                   DATETIME         NOT NULL,
    [Document Type]                  INT              NULL,
    [Document Date]                  DATETIME         NULL,
    [Document No_]                   NVARCHAR (20)    NULL,
    [External Document No_]          NVARCHAR (35)    NULL,
    [Description]                    NVARCHAR (100)   NULL,
    [Depreciation Book Code]         NVARCHAR (10)    NULL,
    [FA Posting Category]            INT              NULL,
    [FA Posting Type]                INT              NULL,
    [Amount]                         DECIMAL (38, 20) NULL,
    [Debit Amount]                   DECIMAL (38, 20) NULL,
    [Credit Amount]                  DECIMAL (38, 20) NULL,
    [Reclassification Entry]         TINYINT          NULL,
    [Part of Book Value]             TINYINT          NULL,
    [Part of Depreciable Basis]      TINYINT          NULL,
    [Disposal Calculation Method]    INT              NULL,
    [Disposal Entry No_]             INT              NULL,
    [No_ of Depreciation Days]       INT              NULL,
    [Quantity]                       DECIMAL (38, 20) NULL,
    [FA No__Budgeted FA No_]         NVARCHAR (20)    NULL,
    [FA Subclass Code]               NVARCHAR (10)    NULL,
    [FA Location Code]               NVARCHAR (10)    NULL,
    [FA Posting Group]               NVARCHAR (20)    NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)    NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)    NULL,
    [Location Code]                  NVARCHAR (10)    NULL,
    [User ID]                        NVARCHAR (50)    NULL,
    [Depreciation Method]            INT              NULL,
    [Depreciation Starting Date]     DATETIME         NULL,
    [Straight-Line _]                DECIMAL (38, 20) NULL,
    [No_ of Depreciation Years]      DECIMAL (38, 20) NULL,
    [Fixed Depr_ Amount]             DECIMAL (38, 20) NULL,
    [Declining-Balance _]            DECIMAL (38, 20) NULL,
    [Depreciation Table Code]        NVARCHAR (10)    NULL,
    [Journal Batch Name]             NVARCHAR (10)    NULL,
    [Source Code]                    NVARCHAR (10)    NULL,
    [Reason Code]                    NVARCHAR (10)    NULL,
    [Transaction No_]                INT              NULL,
    [Bal_ Account Type]              INT              NULL,
    [Bal_ Account No_]               NVARCHAR (20)    NULL,
    [VAT Amount]                     DECIMAL (38, 20) NULL,
    [Gen_ Posting Type]              INT              NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)    NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (20)    NULL,
    [FA Class Code]                  NVARCHAR (10)    NULL,
    [FA Exchange Rate]               DECIMAL (38, 20) NULL,
    [Amount (LCY)]                   DECIMAL (38, 20) NULL,
    [Result on Disposal]             INT              NULL,
    [Correction]                     TINYINT          NULL,
    [Index Entry]                    TINYINT          NULL,
    [Canceled from FA No_]           NVARCHAR (20)    NULL,
    [Depreciation Ending Date]       DATETIME         NULL,
    [Use FA Ledger Check]            TINYINT          NULL,
    [Automatic Entry]                TINYINT          NULL,
    [Depr_ Starting Date (Custom 1)] DATETIME         NULL,
    [Depr_ Ending Date (Custom 1)]   DATETIME         NULL,
    [Accum_ Depr_ _ (Custom 1)]      DECIMAL (38, 20) NULL,
    [Depr_ _ this year (Custom 1)]   DECIMAL (38, 20) NULL,
    [Property Class (Custom 1)]      INT              NULL,
    [No_ Series]                     NVARCHAR (20)    NULL,
    [Tax Area Code]                  NVARCHAR (20)    NULL,
    [Tax Liable]                     TINYINT          NULL,
    [Tax Group Code]                 NVARCHAR (20)    NULL,
    [Use Tax]                        TINYINT          NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)    NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (20)    NULL,
    [Reversed]                       TINYINT          NULL,
    [Reversed by Entry No_]          INT              NULL,
    [Reversed Entry No_]             INT              NULL,
    [Dimension Set ID]               INT              NULL,
    [$systemId]                      UNIQUEIDENTIFIER NULL,
    [$systemCreatedAt]               DATETIME         NULL,
    [$systemCreatedBy]               UNIQUEIDENTIFIER NULL,
    [$systemModifiedAt]              DATETIME         NULL,
    [$systemModifiedBy]              UNIQUEIDENTIFIER NULL,
    [PipelineName]                   NVARCHAR (MAX)   NULL,
    [PipelineRunId]                  NVARCHAR (MAX)   NULL,
    [PipelineTriggerTime]            NVARCHAR (MAX)   NULL,
    [CompanyID]                      INT              NOT NULL,
    CONSTRAINT [PK_stg_bc_FALedgerEntry] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Posting Date] ASC, [Entry No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_bc_FALedgerEntry_timestamp]
    ON [stg_bc].[FALedgerEntry]([CompanyID] ASC, [timestamp] ASC);


GO

