CREATE TABLE [stg_bc].[GeneralLedgerSetup] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Primary Key]                    NVARCHAR (10)      NOT NULL,
    [Allow Posting From]             DATETIME           NOT NULL,
    [Allow Posting To]               DATETIME           NOT NULL,
    [Register Time]                  TINYINT            NOT NULL,
    [Pmt_ Disc_ Excl_ VAT]           TINYINT            NOT NULL,
    [Unrealized VAT]                 TINYINT            NOT NULL,
    [Adjust for Payment Disc_]       TINYINT            NOT NULL,
    [Post with Job Queue]            TINYINT            NOT NULL,
    [Job Queue Category Code]        NVARCHAR (10)      NOT NULL,
    [Job Queue Priority for Post]    INT                NOT NULL,
    [Post & Print with Job Queue]    TINYINT            NOT NULL,
    [Job Q_ Prio_ for Post & Print]  INT                NOT NULL,
    [Notify On Success]              TINYINT            NOT NULL,
    [Mark Cr_ Memos as Corrections]  TINYINT            NOT NULL,
    [Local Address Format]           INT                NOT NULL,
    [Inv_ Rounding Precision (LCY)]  DECIMAL (18)       NOT NULL,
    [Inv_ Rounding Type (LCY)]       INT                NOT NULL,
    [Local Cont_ Addr_ Format]       INT                NOT NULL,
    [Report Output Type]             INT                NOT NULL,
    [Bank Account Nos_]              NVARCHAR (20)      NOT NULL,
    [Summarize G_L Entries]          TINYINT            NOT NULL,
    [Amount Decimal Places]          NVARCHAR (5)       NOT NULL,
    [Unit-Amount Decimal Places]     NVARCHAR (5)       NOT NULL,
    [Additional Reporting Currency]  NVARCHAR (10)      NOT NULL,
    [VAT Tolerance _]                DECIMAL (18)       NOT NULL,
    [EMU Currency]                   TINYINT            NOT NULL,
    [LCY Code]                       NVARCHAR (10)      NOT NULL,
    [VAT Exchange Rate Adjustment]   INT                NOT NULL,
    [Amount Rounding Precision]      DECIMAL (18)       NOT NULL,
    [Unit-Amount Rounding Precision] DECIMAL (18)       NOT NULL,
    [Appln_ Rounding Precision]      DECIMAL (18)       NOT NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)      NOT NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 3 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 4 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 5 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 6 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 7 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 8 Code]      NVARCHAR (20)      NOT NULL,
    [Max_ VAT Difference Allowed]    DECIMAL (18)       NOT NULL,
    [VAT Rounding Type]              INT                NOT NULL,
    [Pmt_ Disc_ Tolerance Posting]   INT                NOT NULL,
    [Payment Discount Grace Period]  VARCHAR (32)       NOT NULL,
    [Payment Tolerance _]            DECIMAL (18)       NOT NULL,
    [Max_ Payment Tolerance Amount]  DECIMAL (18)       NOT NULL,
    [Adapt Main Menu to Permissions] TINYINT            NOT NULL,
    [Allow G_L Acc_ Deletion Before] DATETIME           NOT NULL,
    [Check G_L Account Usage]        TINYINT            NOT NULL,
    [Payment Tolerance Posting]      INT                NOT NULL,
    [Pmt_ Disc_ Tolerance Warning]   TINYINT            NOT NULL,
    [Payment Tolerance Warning]      TINYINT            NOT NULL,
    [Last IC Transaction No_]        INT                NOT NULL,
    [Bill-to_Sell-to VAT Calc_]      INT                NOT NULL,
    [Acc_ Sched_ for Balance Sheet]  NVARCHAR (10)      NOT NULL,
    [Acc_ Sched_ for Income Stmt_]   NVARCHAR (10)      NOT NULL,
    [Acc_ Sched_ for Cash Flow Stmt] NVARCHAR (10)      NOT NULL,
    [Acc_ Sched_ for Retained Earn_] NVARCHAR (10)      NOT NULL,
    [Tax Invoice Renaming Threshold] DECIMAL (18)       NOT NULL,
    [Print VAT specification in LCY] TINYINT            NOT NULL,
    [Prepayment Unrealized VAT]      TINYINT            NOT NULL,
    [Use Legacy G_L Entry Locking]   TINYINT            NOT NULL,
    [Payroll Trans_ Import Format]   NVARCHAR (20)      NOT NULL,
    [VAT Reg_ No_ Validation URL]    NVARCHAR (250)     NOT NULL,
    [Local Currency Symbol]          NVARCHAR (10)      NOT NULL,
    [Local Currency Description]     NVARCHAR (60)      NOT NULL,
    [Show Amounts]                   INT                NOT NULL,
    [SEPA Non-Euro Export]           TINYINT            NOT NULL,
    [SEPA Export w_o Bank Acc_ Data] TINYINT            NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_GeneralLedgerSetup_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_GeneralLedgerSetup_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_GeneralLedgerSetup_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_GeneralLedgerSetup] PRIMARY KEY CLUSTERED ([CompanyID] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

