CREATE TABLE [stg_bc].[GeneralPostingSetup] (
    [timestamp]                     VARBINARY (8)      NOT NULL,
    [Gen_ Bus_ Posting Group]       NVARCHAR (20)      NOT NULL,
    [Gen_ Prod_ Posting Group]      NVARCHAR (20)      NOT NULL,
    [Sales Account]                 NVARCHAR (20)      NOT NULL,
    [Sales Line Disc_ Account]      NVARCHAR (20)      NOT NULL,
    [Sales Inv_ Disc_ Account]      NVARCHAR (20)      NOT NULL,
    [Sales Pmt_ Disc_ Debit Acc_]   NVARCHAR (20)      NOT NULL,
    [Purch_ Account]                NVARCHAR (20)      NOT NULL,
    [Purch_ Line Disc_ Account]     NVARCHAR (20)      NOT NULL,
    [Purch_ Inv_ Disc_ Account]     NVARCHAR (20)      NOT NULL,
    [Purch_ Pmt_ Disc_ Credit Acc_] NVARCHAR (20)      NOT NULL,
    [COGS Account]                  NVARCHAR (20)      NOT NULL,
    [Inventory Adjmt_ Account]      NVARCHAR (20)      NOT NULL,
    [Sales Credit Memo Account]     NVARCHAR (20)      NOT NULL,
    [Purch_ Credit Memo Account]    NVARCHAR (20)      NOT NULL,
    [Sales Pmt_ Disc_ Credit Acc_]  NVARCHAR (20)      NOT NULL,
    [Purch_ Pmt_ Disc_ Debit Acc_]  NVARCHAR (20)      NOT NULL,
    [Sales Pmt_ Tol_ Debit Acc_]    NVARCHAR (20)      NOT NULL,
    [Sales Pmt_ Tol_ Credit Acc_]   NVARCHAR (20)      NOT NULL,
    [Purch_ Pmt_ Tol_ Debit Acc_]   NVARCHAR (20)      NOT NULL,
    [Purch_ Pmt_ Tol_ Credit Acc_]  NVARCHAR (20)      NOT NULL,
    [Sales Prepayments Account]     NVARCHAR (20)      NOT NULL,
    [Purch_ Prepayments Account]    NVARCHAR (20)      NOT NULL,
    [Description]                   NVARCHAR (100)     NOT NULL,
    [View All Accounts on Lookup]   TINYINT            NOT NULL,
    [Purch_ FA Disc_ Account]       NVARCHAR (20)      NOT NULL,
    [Invt_ Accrual Acc_ (Interim)]  NVARCHAR (20)      NOT NULL,
    [COGS Account (Interim)]        NVARCHAR (20)      NOT NULL,
    [Direct Cost Applied Account]   NVARCHAR (20)      NOT NULL,
    [Overhead Applied Account]      NVARCHAR (20)      NOT NULL,
    [Purchase Variance Account]     NVARCHAR (20)      NOT NULL,
    [$systemId]                     NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]              DATETIME           NOT NULL,
    [$systemCreatedBy]              NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]             DATETIME           NOT NULL,
    [$systemModifiedBy]             NVARCHAR (36)      NOT NULL,
    [PipelineName]                  NVARCHAR (200)     CONSTRAINT [DF_GeneralPostingSetup_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                 NVARCHAR (36)      CONSTRAINT [DF_GeneralPostingSetup_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]           DATETIMEOFFSET (0) CONSTRAINT [DF_GeneralPostingSetup_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                     INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_GeneralPostingSetup] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Gen_ Bus_ Posting Group] ASC, [Gen_ Prod_ Posting Group] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

