CREATE TABLE [stg_bc].[InterimTable_fe5622ff-dd0a-4453-887d-a6ef417cc830] (
    [timestamp]                      VARBINARY (8)    NULL,
    [Entry No_]                      INT              NULL,
    [G_L Account No_]                NVARCHAR (20)    NULL,
    [Posting Date]                   DATETIME         NULL,
    [Document Type]                  INT              NULL,
    [Document No_]                   NVARCHAR (20)    NULL,
    [Description]                    NVARCHAR (100)   NULL,
    [Bal_ Account No_]               NVARCHAR (20)    NULL,
    [Amount]                         DECIMAL (38, 20) NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)    NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)    NULL,
    [User ID]                        NVARCHAR (50)    NULL,
    [Source Code]                    NVARCHAR (10)    NULL,
    [System-Created Entry]           TINYINT          NULL,
    [Prior-Year Entry]               TINYINT          NULL,
    [Job No_]                        NVARCHAR (20)    NULL,
    [Quantity]                       DECIMAL (38, 20) NULL,
    [VAT Amount]                     DECIMAL (38, 20) NULL,
    [Business Unit Code]             NVARCHAR (20)    NULL,
    [Journal Batch Name]             NVARCHAR (10)    NULL,
    [Reason Code]                    NVARCHAR (10)    NULL,
    [Gen_ Posting Type]              INT              NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)    NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (20)    NULL,
    [Bal_ Account Type]              INT              NULL,
    [Transaction No_]                INT              NULL,
    [Debit Amount]                   DECIMAL (38, 20) NULL,
    [Credit Amount]                  DECIMAL (38, 20) NULL,
    [Document Date]                  DATETIME         NULL,
    [External Document No_]          NVARCHAR (35)    NULL,
    [Source Type]                    INT              NULL,
    [Source No_]                     NVARCHAR (20)    NULL,
    [No_ Series]                     NVARCHAR (20)    NULL,
    [Tax Area Code]                  NVARCHAR (20)    NULL,
    [Tax Liable]                     TINYINT          NULL,
    [Tax Group Code]                 NVARCHAR (20)    NULL,
    [Use Tax]                        TINYINT          NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)    NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (20)    NULL,
    [Additional-Currency Amount]     DECIMAL (38, 20) NULL,
    [Add_-Currency Debit Amount]     DECIMAL (38, 20) NULL,
    [Add_-Currency Credit Amount]    DECIMAL (38, 20) NULL,
    [Close Income Statement Dim_ ID] INT              NULL,
    [IC Partner Code]                NVARCHAR (20)    NULL,
    [Reversed]                       TINYINT          NULL,
    [Reversed by Entry No_]          INT              NULL,
    [Reversed Entry No_]             INT              NULL,
    [Dimension Set ID]               INT              NULL,
    [Last Dim_ Correction Entry No_] INT              NULL,
    [Last Dim_ Correction Node]      INT              NULL,
    [Dimension Changes Count]        INT              NULL,
    [Prod_ Order No_]                NVARCHAR (20)    NULL,
    [FA Entry Type]                  INT              NULL,
    [FA Entry No_]                   INT              NULL,
    [Last Modified DateTime]         DATETIME         NULL,
    [$systemId]                      UNIQUEIDENTIFIER NULL,
    [$systemCreatedAt]               DATETIME         NULL,
    [$systemCreatedBy]               UNIQUEIDENTIFIER NULL,
    [$systemModifiedAt]              DATETIME         NULL,
    [$systemModifiedBy]              UNIQUEIDENTIFIER NULL,
    [PipelineName]                   NVARCHAR (MAX)   NULL,
    [PipelineRunId]                  NVARCHAR (MAX)   NULL,
    [PipelineTriggerTime]            NVARCHAR (MAX)   NULL,
    [CompanyID]                      INT              NULL,
    [BatchIdentifier]                BIGINT           IDENTITY (1, 1) NOT NULL
);


GO

