CREATE TABLE [stg_bc].[Item] (
    [timestamp]                      VARBINARY (8)    NOT NULL,
    [No_]                            NVARCHAR (20)    NOT NULL,
    [No_ 2]                          NVARCHAR (20)    NULL,
    [Description]                    NVARCHAR (100)   NULL,
    [Search Description]             NVARCHAR (100)   NULL,
    [Description 2]                  NVARCHAR (50)    NULL,
    [Base Unit of Measure]           NVARCHAR (10)    NULL,
    [Price Unit Conversion]          INT              NULL,
    [Type]                           INT              NULL,
    [Inventory Posting Group]        NVARCHAR (20)    NULL,
    [Shelf No_]                      NVARCHAR (10)    NULL,
    [Item Disc_ Group]               NVARCHAR (20)    NULL,
    [Allow Invoice Disc_]            TINYINT          NULL,
    [Statistics Group]               INT              NULL,
    [Commission Group]               INT              NULL,
    [Unit Price]                     DECIMAL (38, 20) NULL,
    [Price_Profit Calculation]       INT              NULL,
    [Profit _]                       DECIMAL (38, 20) NULL,
    [Costing Method]                 INT              NULL,
    [Unit Cost]                      DECIMAL (38, 20) NULL,
    [Standard Cost]                  DECIMAL (38, 20) NULL,
    [Last Direct Cost]               DECIMAL (38, 20) NULL,
    [Indirect Cost _]                DECIMAL (38, 20) NULL,
    [Cost is Adjusted]               TINYINT          NULL,
    [Allow Online Adjustment]        TINYINT          NULL,
    [Vendor No_]                     NVARCHAR (20)    NULL,
    [Vendor Item No_]                NVARCHAR (50)    NULL,
    [Lead Time Calculation]          VARCHAR (32)     NULL,
    [Reorder Point]                  DECIMAL (38, 20) NULL,
    [Maximum Inventory]              DECIMAL (38, 20) NULL,
    [Reorder Quantity]               DECIMAL (38, 20) NULL,
    [Alternative Item No_]           NVARCHAR (20)    NULL,
    [Unit List Price]                DECIMAL (38, 20) NULL,
    [Duty Due _]                     DECIMAL (38, 20) NULL,
    [Duty Code]                      NVARCHAR (10)    NULL,
    [Gross Weight]                   DECIMAL (38, 20) NULL,
    [Net Weight]                     DECIMAL (38, 20) NULL,
    [Units per Parcel]               DECIMAL (38, 20) NULL,
    [Unit Volume]                    DECIMAL (38, 20) NULL,
    [Durability]                     NVARCHAR (10)    NULL,
    [Freight Type]                   NVARCHAR (10)    NULL,
    [Tariff No_]                     NVARCHAR (20)    NULL,
    [Duty Unit Conversion]           DECIMAL (38, 20) NULL,
    [Country_Region Purchased Code]  NVARCHAR (10)    NULL,
    [Budget Quantity]                DECIMAL (38, 20) NULL,
    [Budgeted Amount]                DECIMAL (38, 20) NULL,
    [Budget Profit]                  DECIMAL (38, 20) NULL,
    [Blocked]                        TINYINT          NULL,
    [Block Reason]                   NVARCHAR (250)   NULL,
    [Last DateTime Modified]         DATETIME         NULL,
    [Last Date Modified]             DATETIME         NULL,
    [Last Time Modified]             DATETIME         NULL,
    [Price Includes VAT]             TINYINT          NULL,
    [VAT Bus_ Posting Gr_ (Price)]   NVARCHAR (20)    NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (20)    NULL,
    [Picture]                        VARBINARY (MAX)  NULL,
    [Country_Region of Origin Code]  NVARCHAR (10)    NULL,
    [Automatic Ext_ Texts]           TINYINT          NULL,
    [No_ Series]                     NVARCHAR (20)    NULL,
    [Tax Group Code]                 NVARCHAR (20)    NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (20)    NULL,
    [Reserve]                        INT              NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)    NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)    NULL,
    [Stockout Warning]               INT              NULL,
    [Prevent Negative Inventory]     INT              NULL,
    [Application Wksh_ User ID]      NVARCHAR (128)   NULL,
    [Assembly Policy]                INT              NULL,
    [GTIN]                           NVARCHAR (14)    NULL,
    [Default Deferral Template Code] NVARCHAR (10)    NULL,
    [Low-Level Code]                 INT              NULL,
    [Lot Size]                       DECIMAL (38, 20) NULL,
    [Serial Nos_]                    NVARCHAR (20)    NULL,
    [Last Unit Cost Calc_ Date]      DATETIME         NULL,
    [Rolled-up Material Cost]        DECIMAL (38, 20) NULL,
    [Rolled-up Capacity Cost]        DECIMAL (38, 20) NULL,
    [Scrap _]                        DECIMAL (38, 20) NULL,
    [Inventory Value Zero]           TINYINT          NULL,
    [Discrete Order Quantity]        INT              NULL,
    [Minimum Order Quantity]         DECIMAL (38, 20) NULL,
    [Maximum Order Quantity]         DECIMAL (38, 20) NULL,
    [Safety Stock Quantity]          DECIMAL (38, 20) NULL,
    [Order Multiple]                 DECIMAL (38, 20) NULL,
    [Safety Lead Time]               VARCHAR (32)     NULL,
    [Flushing Method]                INT              NULL,
    [Replenishment System]           INT              NULL,
    [Rounding Precision]             DECIMAL (38, 20) NULL,
    [Sales Unit of Measure]          NVARCHAR (10)    NULL,
    [Purch_ Unit of Measure]         NVARCHAR (10)    NULL,
    [Time Bucket]                    VARCHAR (32)     NULL,
    [Reordering Policy]              INT              NULL,
    [Include Inventory]              TINYINT          NULL,
    [Manufacturing Policy]           INT              NULL,
    [Rescheduling Period]            VARCHAR (32)     NULL,
    [Lot Accumulation Period]        VARCHAR (32)     NULL,
    [Dampener Period]                VARCHAR (32)     NULL,
    [Dampener Quantity]              DECIMAL (38, 20) NULL,
    [Overflow Level]                 DECIMAL (38, 20) NULL,
    [Manufacturer Code]              NVARCHAR (10)    NULL,
    [Item Category Code]             NVARCHAR (20)    NULL,
    [Created From Nonstock Item]     TINYINT          NULL,
    [Product Group Code]             NVARCHAR (10)    NULL,
    [Purchasing Code]                NVARCHAR (10)    NULL,
    [Service Item Group]             NVARCHAR (10)    NULL,
    [Item Tracking Code]             NVARCHAR (10)    NULL,
    [Lot Nos_]                       NVARCHAR (20)    NULL,
    [Expiration Calculation]         VARCHAR (32)     NULL,
    [Warehouse Class Code]           NVARCHAR (10)    NULL,
    [Special Equipment Code]         NVARCHAR (10)    NULL,
    [Put-away Template Code]         NVARCHAR (10)    NULL,
    [Put-away Unit of Measure Code]  NVARCHAR (10)    NULL,
    [Phys Invt Counting Period Code] NVARCHAR (10)    NULL,
    [Last Counting Period Update]    DATETIME         NULL,
    [Use Cross-Docking]              TINYINT          NULL,
    [Next Counting Start Date]       DATETIME         NULL,
    [Next Counting End Date]         DATETIME         NULL,
    [Id]                             UNIQUEIDENTIFIER NULL,
    [Unit of Measure Id]             UNIQUEIDENTIFIER NULL,
    [Tax Group Id]                   UNIQUEIDENTIFIER NULL,
    [Sales Blocked]                  TINYINT          NULL,
    [Purchasing Blocked]             TINYINT          NULL,
    [Item Category Id]               UNIQUEIDENTIFIER NULL,
    [Over-Receipt Code]              NVARCHAR (20)    NULL,
    [Routing No_]                    NVARCHAR (20)    NULL,
    [Production BOM No_]             NVARCHAR (20)    NULL,
    [Single-Level Material Cost]     DECIMAL (38, 20) NULL,
    [Single-Level Capacity Cost]     DECIMAL (38, 20) NULL,
    [Single-Level Subcontrd_ Cost]   DECIMAL (38, 20) NULL,
    [Single-Level Cap_ Ovhd Cost]    DECIMAL (38, 20) NULL,
    [Single-Level Mfg_ Ovhd Cost]    DECIMAL (38, 20) NULL,
    [Overhead Rate]                  DECIMAL (38, 20) NULL,
    [Rolled-up Subcontracted Cost]   DECIMAL (38, 20) NULL,
    [Rolled-up Mfg_ Ovhd Cost]       DECIMAL (38, 20) NULL,
    [Rolled-up Cap_ Overhead Cost]   DECIMAL (38, 20) NULL,
    [Order Tracking Policy]          INT              NULL,
    [Critical]                       TINYINT          NULL,
    [Common Item No_]                NVARCHAR (20)    NULL,
    [$systemId]                      UNIQUEIDENTIFIER NULL,
    [$systemCreatedAt]               DATETIME         NULL,
    [$systemCreatedBy]               UNIQUEIDENTIFIER NULL,
    [$systemModifiedAt]              DATETIME         NULL,
    [$systemModifiedBy]              UNIQUEIDENTIFIER NULL,
    [PipelineName]                   NVARCHAR (MAX)   NULL,
    [PipelineRunId]                  NVARCHAR (MAX)   NULL,
    [PipelineTriggerTime]            NVARCHAR (MAX)   NULL,
    [CompanyID]                      INT              NOT NULL,
    [ItemBodyType]                   INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_stg_bc_Item] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ix_stg_bc_Item_timestamp]
    ON [stg_bc].[Item]([CompanyID] ASC, [timestamp] ASC);


GO

