CREATE TABLE [stg_bc].[ItemLedgerEntry] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [Entry No_]                    INT                NOT NULL,
    [Item No_]                     NVARCHAR (20)      NULL,
    [Posting Date]                 DATETIME           NULL,
    [Entry Type]                   INT                NULL,
    [Source No_]                   NVARCHAR (20)      NULL,
    [Document No_]                 NVARCHAR (20)      NULL,
    [Description]                  NVARCHAR (100)     NULL,
    [Location Code]                NVARCHAR (10)      NULL,
    [Quantity]                     DECIMAL (38, 20)   NULL,
    [Remaining Quantity]           DECIMAL (38, 20)   NULL,
    [Invoiced Quantity]            DECIMAL (38, 20)   NULL,
    [Applies-to Entry]             INT                NULL,
    [Open]                         TINYINT            NULL,
    [Global Dimension 1 Code]      NVARCHAR (20)      NULL,
    [Global Dimension 2 Code]      NVARCHAR (20)      NULL,
    [Positive]                     TINYINT            NULL,
    [Shpt_ Method Code]            NVARCHAR (10)      NULL,
    [Source Type]                  INT                NULL,
    [Drop Shipment]                TINYINT            NULL,
    [Transaction Type]             NVARCHAR (10)      NULL,
    [Transport Method]             NVARCHAR (10)      NULL,
    [Country_Region Code]          NVARCHAR (10)      NULL,
    [Entry_Exit Point]             NVARCHAR (10)      NULL,
    [Document Date]                DATETIME           NULL,
    [External Document No_]        NVARCHAR (35)      NULL,
    [Area]                         NVARCHAR (10)      NULL,
    [Transaction Specification]    NVARCHAR (10)      NULL,
    [No_ Series]                   NVARCHAR (20)      NULL,
    [Document Type]                INT                NULL,
    [Document Line No_]            INT                NULL,
    [Order Type]                   INT                NULL,
    [Order No_]                    NVARCHAR (20)      NULL,
    [Order Line No_]               INT                NULL,
    [Dimension Set ID]             INT                NULL,
    [Assemble to Order]            TINYINT            NULL,
    [Job No_]                      NVARCHAR (20)      NULL,
    [Job Task No_]                 NVARCHAR (20)      NULL,
    [Job Purchase]                 TINYINT            NULL,
    [Variant Code]                 NVARCHAR (10)      NULL,
    [Qty_ per Unit of Measure]     DECIMAL (38, 20)   NULL,
    [Unit of Measure Code]         NVARCHAR (10)      NULL,
    [Derived from Blanket Order]   TINYINT            NULL,
    [Cross-Reference No_]          NVARCHAR (20)      NULL,
    [Originally Ordered No_]       NVARCHAR (20)      NULL,
    [Originally Ordered Var_ Code] NVARCHAR (10)      NULL,
    [Out-of-Stock Substitution]    TINYINT            NULL,
    [Item Category Code]           NVARCHAR (20)      NULL,
    [Nonstock]                     TINYINT            NULL,
    [Purchasing Code]              NVARCHAR (10)      NULL,
    [Product Group Code]           NVARCHAR (10)      NULL,
    [Item Reference No_]           NVARCHAR (50)      NULL,
    [Completely Invoiced]          TINYINT            NULL,
    [Last Invoice Date]            DATETIME           NULL,
    [Applied Entry to Adjust]      TINYINT            NULL,
    [Correction]                   TINYINT            NULL,
    [Shipped Qty_ Not Returned]    DECIMAL (38, 20)   NULL,
    [Prod_ Order Comp_ Line No_]   INT                NULL,
    [Serial No_]                   NVARCHAR (50)      NULL,
    [Lot No_]                      NVARCHAR (50)      NULL,
    [Warranty Date]                DATETIME           NULL,
    [Expiration Date]              DATETIME           NULL,
    [Item Tracking]                INT                NULL,
    [Package No_]                  NVARCHAR (50)      NULL,
    [Return Reason Code]           NVARCHAR (10)      NULL,
    [$systemId]                    NVARCHAR (36)      NULL,
    [$systemCreatedAt]             DATETIME           NULL,
    [$systemCreatedBy]             NVARCHAR (36)      NULL,
    [$systemModifiedAt]            DATETIME           NULL,
    [$systemModifiedBy]            NVARCHAR (36)      NULL,
    [PipelineName]                 NVARCHAR (200)     NULL,
    [PipelineRunId]                NVARCHAR (36)      NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_ItemLedgerEntry] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Entry No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

