CREATE TABLE [stg_bc].[Location] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [Code]                         NVARCHAR (10)      NOT NULL,
    [Name]                         NVARCHAR (100)     NOT NULL,
    [Default Bin Code]             NVARCHAR (20)      NOT NULL,
    [Name 2]                       NVARCHAR (50)      NOT NULL,
    [Address]                      NVARCHAR (100)     NOT NULL,
    [Address 2]                    NVARCHAR (50)      NOT NULL,
    [City]                         NVARCHAR (30)      NOT NULL,
    [Phone No_]                    NVARCHAR (30)      NOT NULL,
    [Phone No_ 2]                  NVARCHAR (30)      NOT NULL,
    [Telex No_]                    NVARCHAR (30)      NOT NULL,
    [Fax No_]                      NVARCHAR (30)      NOT NULL,
    [Contact]                      NVARCHAR (100)     NOT NULL,
    [Post Code]                    NVARCHAR (20)      NOT NULL,
    [County]                       NVARCHAR (30)      NOT NULL,
    [E-Mail]                       NVARCHAR (80)      NOT NULL,
    [Home Page]                    NVARCHAR (90)      NOT NULL,
    [Country_Region Code]          NVARCHAR (10)      NOT NULL,
    [Use As In-Transit]            TINYINT            NOT NULL,
    [Require Put-away]             TINYINT            NOT NULL,
    [Require Pick]                 TINYINT            NOT NULL,
    [Cross-Dock Due Date Calc_]    VARCHAR (32)       NOT NULL,
    [Use Cross-Docking]            TINYINT            NOT NULL,
    [Require Receive]              TINYINT            NOT NULL,
    [Require Shipment]             TINYINT            NOT NULL,
    [Bin Mandatory]                TINYINT            NOT NULL,
    [Directed Put-away and Pick]   TINYINT            NOT NULL,
    [Default Bin Selection]        INT                NOT NULL,
    [Outbound Whse_ Handling Time] VARCHAR (32)       NOT NULL,
    [Inbound Whse_ Handling Time]  VARCHAR (32)       NOT NULL,
    [Put-away Template Code]       NVARCHAR (10)      NOT NULL,
    [Use Put-away Worksheet]       TINYINT            NOT NULL,
    [Pick According to FEFO]       TINYINT            NOT NULL,
    [Allow Breakbulk]              TINYINT            NOT NULL,
    [Bin Capacity Policy]          INT                NOT NULL,
    [Open Shop Floor Bin Code]     NVARCHAR (20)      NOT NULL,
    [To-Production Bin Code]       NVARCHAR (20)      NOT NULL,
    [From-Production Bin Code]     NVARCHAR (20)      NOT NULL,
    [Adjustment Bin Code]          NVARCHAR (20)      NOT NULL,
    [Always Create Put-away Line]  TINYINT            NOT NULL,
    [Always Create Pick Line]      TINYINT            NOT NULL,
    [Special Equipment]            INT                NOT NULL,
    [Receipt Bin Code]             NVARCHAR (20)      NOT NULL,
    [Shipment Bin Code]            NVARCHAR (20)      NOT NULL,
    [Cross-Dock Bin Code]          NVARCHAR (20)      NOT NULL,
    [To-Assembly Bin Code]         NVARCHAR (20)      NOT NULL,
    [From-Assembly Bin Code]       NVARCHAR (20)      NOT NULL,
    [Asm_-to-Order Shpt_ Bin Code] NVARCHAR (20)      NOT NULL,
    [Base Calendar Code]           NVARCHAR (10)      NOT NULL,
    [Use ADCS]                     TINYINT            NOT NULL,
    [$systemId]                    NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]             DATETIME           NOT NULL,
    [$systemCreatedBy]             NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]            DATETIME           NOT NULL,
    [$systemModifiedBy]            NVARCHAR (36)      NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_Location_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_Location_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_Location_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_Location] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Code] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

