CREATE TABLE [stg_bc].[MachineCenter] (
    [timestamp]                     VARBINARY (8)      NOT NULL,
    [No_]                           NVARCHAR (20)      NOT NULL,
    [Name]                          NVARCHAR (50)      NOT NULL,
    [Search Name]                   NVARCHAR (50)      NOT NULL,
    [Name 2]                        NVARCHAR (50)      NOT NULL,
    [Address]                       NVARCHAR (100)     NOT NULL,
    [Address 2]                     NVARCHAR (50)      NOT NULL,
    [City]                          NVARCHAR (30)      NOT NULL,
    [Post Code]                     NVARCHAR (20)      NOT NULL,
    [Work Center No_]               NVARCHAR (20)      NOT NULL,
    [Direct Unit Cost]              DECIMAL (38, 20)   NOT NULL,
    [Indirect Cost _]               DECIMAL (38, 20)   NOT NULL,
    [Unit Cost]                     DECIMAL (38, 20)   NOT NULL,
    [Queue Time]                    DECIMAL (38, 20)   NOT NULL,
    [Queue Time Unit of Meas_ Code] NVARCHAR (10)      NOT NULL,
    [Last Date Modified]            DATETIME           NOT NULL,
    [Capacity]                      DECIMAL (38, 20)   NOT NULL,
    [Efficiency]                    DECIMAL (38, 20)   NOT NULL,
    [Maximum Efficiency]            DECIMAL (38, 20)   NOT NULL,
    [Minimum Efficiency]            DECIMAL (38, 20)   NOT NULL,
    [Blocked]                       TINYINT            NOT NULL,
    [Setup Time]                    DECIMAL (38, 20)   NOT NULL,
    [Wait Time]                     DECIMAL (38, 20)   NOT NULL,
    [Move Time]                     DECIMAL (38, 20)   NOT NULL,
    [Fixed Scrap Quantity]          DECIMAL (38, 20)   NOT NULL,
    [Scrap _]                       DECIMAL (38, 20)   NOT NULL,
    [Setup Time Unit of Meas_ Code] NVARCHAR (10)      NOT NULL,
    [Wait Time Unit of Meas_ Code]  NVARCHAR (10)      NOT NULL,
    [Send-Ahead Quantity]           DECIMAL (38, 20)   NOT NULL,
    [Move Time Unit of Meas_ Code]  NVARCHAR (10)      NOT NULL,
    [Flushing Method]               INT                NOT NULL,
    [Minimum Process Time]          DECIMAL (38, 20)   NOT NULL,
    [Maximum Process Time]          DECIMAL (38, 20)   NOT NULL,
    [Concurrent Capacities]         DECIMAL (38, 20)   NOT NULL,
    [No_ Series]                    NVARCHAR (20)      NOT NULL,
    [Overhead Rate]                 DECIMAL (38, 20)   NOT NULL,
    [Gen_ Prod_ Posting Group]      NVARCHAR (20)      NOT NULL,
    [County]                        NVARCHAR (30)      NOT NULL,
    [Country_Region Code]           NVARCHAR (10)      NOT NULL,
    [Location Code]                 NVARCHAR (10)      NOT NULL,
    [Open Shop Floor Bin Code]      NVARCHAR (20)      NOT NULL,
    [To-Production Bin Code]        NVARCHAR (20)      NOT NULL,
    [From-Production Bin Code]      NVARCHAR (20)      NOT NULL,
    [$systemId]                     NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]              DATETIME           NOT NULL,
    [$systemCreatedBy]              NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]             DATETIME           NOT NULL,
    [$systemModifiedBy]             NVARCHAR (36)      NOT NULL,
    [PipelineName]                  NVARCHAR (200)     CONSTRAINT [DF_MachineCenter_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                 NVARCHAR (36)      CONSTRAINT [DF_MachineCenter_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]           DATETIMEOFFSET (0) CONSTRAINT [DF_MachineCenter_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                     INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_MachineCenter] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

