CREATE TABLE [stg_bc].[ProductionBOMLine] (
    [timestamp]            VARBINARY (8)      NOT NULL,
    [Production BOM No_]   NVARCHAR (20)      NOT NULL,
    [Version Code]         NVARCHAR (20)      NOT NULL,
    [Line No_]             INT                NOT NULL,
    [Type]                 INT                NOT NULL,
    [No_]                  NVARCHAR (20)      NOT NULL,
    [Description]          NVARCHAR (100)     NOT NULL,
    [Unit of Measure Code] NVARCHAR (10)      NOT NULL,
    [Quantity]             DECIMAL (38, 20)   NOT NULL,
    [Position]             NVARCHAR (10)      NOT NULL,
    [Position 2]           NVARCHAR (10)      NOT NULL,
    [Position 3]           NVARCHAR (10)      NOT NULL,
    [Lead-Time Offset]     VARCHAR (32)       NOT NULL,
    [Routing Link Code]    NVARCHAR (10)      NOT NULL,
    [Scrap _]              DECIMAL (38, 20)   NOT NULL,
    [Variant Code]         NVARCHAR (10)      NOT NULL,
    [Starting Date]        DATETIME           NOT NULL,
    [Ending Date]          DATETIME           NOT NULL,
    [Length]               DECIMAL (38, 20)   NOT NULL,
    [Width]                DECIMAL (38, 20)   NOT NULL,
    [Weight]               DECIMAL (38, 20)   NOT NULL,
    [Depth]                DECIMAL (38, 20)   NOT NULL,
    [Calculation Formula]  INT                NOT NULL,
    [Quantity per]         DECIMAL (38, 20)   NOT NULL,
    [$systemId]            NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]     DATETIME           NOT NULL,
    [$systemCreatedBy]     NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]    DATETIME           NOT NULL,
    [$systemModifiedBy]    NVARCHAR (36)      NOT NULL,
    [PipelineName]         NVARCHAR (200)     CONSTRAINT [DF_ProductionBOMLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]        NVARCHAR (36)      CONSTRAINT [DF_ProductionBOMLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]  DATETIMEOFFSET (0) CONSTRAINT [DF_ProductionBOMLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]            INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_ProductionBOMLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Production BOM No_] ASC, [Version Code] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

