CREATE TABLE [stg_bc].[ProdOrderRoutingLine] (
    [timestamp]                     VARBINARY (8)      NOT NULL,
    [Status]                        INT                NOT NULL,
    [Prod_ Order No_]               NVARCHAR (20)      NOT NULL,
    [Routing Reference No_]         INT                NOT NULL,
    [Routing No_]                   NVARCHAR (20)      NOT NULL,
    [Operation No_]                 NVARCHAR (10)      NOT NULL,
    [Next Operation No_]            NVARCHAR (30)      NOT NULL,
    [Previous Operation No_]        NVARCHAR (30)      NOT NULL,
    [Type]                          INT                NOT NULL,
    [No_]                           NVARCHAR (20)      NOT NULL,
    [Work Center No_]               NVARCHAR (20)      NOT NULL,
    [Work Center Group Code]        NVARCHAR (10)      NOT NULL,
    [Description]                   NVARCHAR (100)     NOT NULL,
    [Setup Time]                    DECIMAL (38, 20)   NOT NULL,
    [Run Time]                      DECIMAL (38, 20)   NOT NULL,
    [Wait Time]                     DECIMAL (38, 20)   NOT NULL,
    [Move Time]                     DECIMAL (38, 20)   NOT NULL,
    [Fixed Scrap Quantity]          DECIMAL (38, 20)   NOT NULL,
    [Lot Size]                      DECIMAL (38, 20)   NOT NULL,
    [Scrap Factor _]                DECIMAL (38, 20)   NOT NULL,
    [Setup Time Unit of Meas_ Code] NVARCHAR (10)      NOT NULL,
    [Run Time Unit of Meas_ Code]   NVARCHAR (10)      NOT NULL,
    [Wait Time Unit of Meas_ Code]  NVARCHAR (10)      NOT NULL,
    [Move Time Unit of Meas_ Code]  NVARCHAR (10)      NOT NULL,
    [Minimum Process Time]          DECIMAL (38, 20)   NOT NULL,
    [Maximum Process Time]          DECIMAL (38, 20)   NOT NULL,
    [Concurrent Capacities]         DECIMAL (38, 20)   NOT NULL,
    [Send-Ahead Quantity]           DECIMAL (38, 20)   NOT NULL,
    [Routing Link Code]             NVARCHAR (10)      NOT NULL,
    [Standard Task Code]            NVARCHAR (10)      NOT NULL,
    [Unit Cost per]                 DECIMAL (38, 20)   NOT NULL,
    [Recalculate]                   TINYINT            NOT NULL,
    [Sequence No_ (Forward)]        INT                NOT NULL,
    [Sequence No_ (Backward)]       INT                NOT NULL,
    [Fixed Scrap Qty_ (Accum_)]     DECIMAL (38, 20)   NOT NULL,
    [Scrap Factor _ (Accumulated)]  DECIMAL (38, 20)   NOT NULL,
    [Sequence No_ (Actual)]         INT                NOT NULL,
    [Direct Unit Cost]              DECIMAL (38, 20)   NOT NULL,
    [Indirect Cost _]               DECIMAL (38, 20)   NOT NULL,
    [Overhead Rate]                 DECIMAL (38, 20)   NOT NULL,
    [Starting Time]                 DATETIME           NOT NULL,
    [Starting Date]                 DATETIME           NOT NULL,
    [Ending Time]                   DATETIME           NOT NULL,
    [Ending Date]                   DATETIME           NOT NULL,
    [Unit Cost Calculation]         INT                NOT NULL,
    [Input Quantity]                DECIMAL (38, 20)   NOT NULL,
    [Critical Path]                 TINYINT            NOT NULL,
    [Routing Status]                INT                NOT NULL,
    [Flushing Method]               INT                NOT NULL,
    [Expected Operation Cost Amt_]  DECIMAL (38, 20)   NOT NULL,
    [Expected Capacity Need]        DECIMAL (38, 20)   NOT NULL,
    [Expected Capacity Ovhd_ Cost]  DECIMAL (38, 20)   NOT NULL,
    [Starting Date-Time]            DATETIME           NOT NULL,
    [Ending Date-Time]              DATETIME           NOT NULL,
    [Schedule Manually]             TINYINT            NOT NULL,
    [Location Code]                 NVARCHAR (10)      NOT NULL,
    [Open Shop Floor Bin Code]      NVARCHAR (20)      NOT NULL,
    [To-Production Bin Code]        NVARCHAR (20)      NOT NULL,
    [From-Production Bin Code]      NVARCHAR (20)      NOT NULL,
    [$systemId]                     NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]              DATETIME           NOT NULL,
    [$systemCreatedBy]              NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]             DATETIME           NOT NULL,
    [$systemModifiedBy]             NVARCHAR (36)      NOT NULL,
    [PipelineName]                  NVARCHAR (200)     CONSTRAINT [DF_ProdOrderRoutingLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                 NVARCHAR (36)      CONSTRAINT [DF_ProdOrderRoutingLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]           DATETIMEOFFSET (0) CONSTRAINT [DF_ProdOrderRoutingLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                     INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_ProdOrderRoutingLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Status] ASC, [Prod_ Order No_] ASC, [Routing Reference No_] ASC, [Routing No_] ASC, [Operation No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

