CREATE TABLE [stg_bc].[ProductionOrder] (
    [timestamp]                 VARBINARY (8)      NOT NULL,
    [Status]                    INT                NOT NULL,
    [No_]                       NVARCHAR (20)      NOT NULL,
    [Description]               NVARCHAR (100)     NOT NULL,
    [Search Description]        NVARCHAR (100)     NOT NULL,
    [Description 2]             NVARCHAR (50)      NOT NULL,
    [Creation Date]             DATETIME           NOT NULL,
    [Last Date Modified]        DATETIME           NOT NULL,
    [Source Type]               INT                NOT NULL,
    [Source No_]                NVARCHAR (20)      NOT NULL,
    [Routing No_]               NVARCHAR (20)      NOT NULL,
    [Variant Code]              NVARCHAR (10)      NOT NULL,
    [Inventory Posting Group]   NVARCHAR (20)      NOT NULL,
    [Gen_ Prod_ Posting Group]  NVARCHAR (20)      NOT NULL,
    [Gen_ Bus_ Posting Group]   NVARCHAR (20)      NOT NULL,
    [Starting Time]             DATETIME           NOT NULL,
    [Starting Date]             DATETIME           NOT NULL,
    [Ending Time]               DATETIME           NOT NULL,
    [Ending Date]               DATETIME           NOT NULL,
    [Due Date]                  DATETIME           NOT NULL,
    [Finished Date]             DATETIME           NOT NULL,
    [Blocked]                   TINYINT            NOT NULL,
    [Shortcut Dimension 1 Code] NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code] NVARCHAR (20)      NOT NULL,
    [Location Code]             NVARCHAR (10)      NOT NULL,
    [Bin Code]                  NVARCHAR (20)      NOT NULL,
    [Replan Ref_ No_]           NVARCHAR (20)      NOT NULL,
    [Replan Ref_ Status]        INT                NOT NULL,
    [Low-Level Code]            INT                NOT NULL,
    [Quantity]                  DECIMAL (38, 20)   NOT NULL,
    [Unit Cost]                 DECIMAL (38, 20)   NOT NULL,
    [Cost Amount]               DECIMAL (38, 20)   NOT NULL,
    [No_ Series]                NVARCHAR (20)      NOT NULL,
    [Planned Order No_]         NVARCHAR (20)      NOT NULL,
    [Firm Planned Order No_]    NVARCHAR (20)      NOT NULL,
    [Simulated Order No_]       NVARCHAR (20)      NOT NULL,
    [Starting Date-Time]        DATETIME           NOT NULL,
    [Ending Date-Time]          DATETIME           NOT NULL,
    [Dimension Set ID]          INT                NOT NULL,
    [Assigned User ID]          NVARCHAR (50)      NOT NULL,
    [$systemId]                 NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]          DATETIME           NOT NULL,
    [$systemCreatedBy]          NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]         DATETIME           NOT NULL,
    [$systemModifiedBy]         NVARCHAR (36)      NOT NULL,
    [PipelineName]              NVARCHAR (200)     CONSTRAINT [DF_ProductionOrder_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]             NVARCHAR (36)      CONSTRAINT [DF_ProductionOrder_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]       DATETIMEOFFSET (0) CONSTRAINT [DF_ProductionOrder_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                 INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_ProductionOrder] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Status] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

