CREATE TABLE [stg_bc].[ProdOrderComponent] (
    [timestamp]                 VARBINARY (8)      NOT NULL,
    [Status]                    INT                NOT NULL,
    [Prod_ Order No_]           NVARCHAR (20)      NOT NULL,
    [Prod_ Order Line No_]      INT                NOT NULL,
    [Line No_]                  INT                NOT NULL,
    [Item No_]                  NVARCHAR (20)      NOT NULL,
    [Description]               NVARCHAR (100)     NOT NULL,
    [Unit of Measure Code]      NVARCHAR (10)      NOT NULL,
    [Quantity]                  DECIMAL (38, 20)   NOT NULL,
    [Position]                  NVARCHAR (10)      NOT NULL,
    [Position 2]                NVARCHAR (10)      NOT NULL,
    [Position 3]                NVARCHAR (10)      NOT NULL,
    [Lead-Time Offset]          VARCHAR (32)       NOT NULL,
    [Routing Link Code]         NVARCHAR (10)      NOT NULL,
    [Scrap _]                   DECIMAL (38, 20)   NOT NULL,
    [Variant Code]              NVARCHAR (10)      NOT NULL,
    [Expected Quantity]         DECIMAL (38, 20)   NOT NULL,
    [Remaining Quantity]        DECIMAL (38, 20)   NOT NULL,
    [Flushing Method]           INT                NOT NULL,
    [Location Code]             NVARCHAR (10)      NOT NULL,
    [Shortcut Dimension 1 Code] NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code] NVARCHAR (20)      NOT NULL,
    [Bin Code]                  NVARCHAR (20)      NOT NULL,
    [Supplied-by Line No_]      INT                NOT NULL,
    [Planning Level Code]       INT                NOT NULL,
    [Item Low-Level Code]       INT                NOT NULL,
    [Length]                    DECIMAL (38, 20)   NOT NULL,
    [Width]                     DECIMAL (38, 20)   NOT NULL,
    [Weight]                    DECIMAL (38, 20)   NOT NULL,
    [Depth]                     DECIMAL (38, 20)   NOT NULL,
    [Calculation Formula]       INT                NOT NULL,
    [Quantity per]              DECIMAL (38, 20)   NOT NULL,
    [Unit Cost]                 DECIMAL (38, 20)   NOT NULL,
    [Cost Amount]               DECIMAL (38, 20)   NOT NULL,
    [Due Date]                  DATETIME           NOT NULL,
    [Due Time]                  DATETIME           NOT NULL,
    [Qty_ per Unit of Measure]  DECIMAL (38, 20)   NOT NULL,
    [Remaining Qty_ (Base)]     DECIMAL (38, 20)   NOT NULL,
    [Quantity (Base)]           DECIMAL (38, 20)   NOT NULL,
    [Expected Qty_ (Base)]      DECIMAL (38, 20)   NOT NULL,
    [Due Date-Time]             DATETIME           NOT NULL,
    [Dimension Set ID]          INT                NOT NULL,
    [Original Item No_]         NVARCHAR (20)      NOT NULL,
    [Original Variant Code]     NVARCHAR (10)      NOT NULL,
    [Qty_ Picked]               DECIMAL (38, 20)   NOT NULL,
    [Qty_ Picked (Base)]        DECIMAL (38, 20)   NOT NULL,
    [Completely Picked]         TINYINT            NOT NULL,
    [Direct Unit Cost]          DECIMAL (38, 20)   NOT NULL,
    [Indirect Cost _]           DECIMAL (38, 20)   NOT NULL,
    [Overhead Rate]             DECIMAL (38, 20)   NOT NULL,
    [Direct Cost Amount]        DECIMAL (38, 20)   NOT NULL,
    [Overhead Amount]           DECIMAL (38, 20)   NOT NULL,
    [$systemId]                 NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]          DATETIME           NOT NULL,
    [$systemCreatedBy]          NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]         DATETIME           NOT NULL,
    [$systemModifiedBy]         NVARCHAR (36)      NOT NULL,
    [PipelineName]              NVARCHAR (200)     CONSTRAINT [DF_ProdOrderComponent_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]             NVARCHAR (36)      CONSTRAINT [DF_ProdOrderComponent_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]       DATETIMEOFFSET (0) CONSTRAINT [DF_ProdOrderComponent_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                 INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_ProdOrderComponent] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Status] ASC, [Prod_ Order No_] ASC, [Prod_ Order Line No_] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

