CREATE TABLE [stg_bc].[ProdOrderLine] (
    [timestamp]                   VARBINARY (8)      NOT NULL,
    [Status]                      INT                NOT NULL,
    [Prod_ Order No_]             NVARCHAR (20)      NOT NULL,
    [Line No_]                    INT                NOT NULL,
    [Item No_]                    NVARCHAR (20)      NOT NULL,
    [Variant Code]                NVARCHAR (10)      NOT NULL,
    [Description]                 NVARCHAR (100)     NOT NULL,
    [Description 2]               NVARCHAR (50)      NOT NULL,
    [Location Code]               NVARCHAR (10)      NOT NULL,
    [Shortcut Dimension 1 Code]   NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]   NVARCHAR (20)      NOT NULL,
    [Bin Code]                    NVARCHAR (20)      NOT NULL,
    [Quantity]                    DECIMAL (38, 20)   NOT NULL,
    [Finished Quantity]           DECIMAL (38, 20)   NOT NULL,
    [Remaining Quantity]          DECIMAL (38, 20)   NOT NULL,
    [Scrap _]                     DECIMAL (38, 20)   NOT NULL,
    [Due Date]                    DATETIME           NOT NULL,
    [Starting Date]               DATETIME           NOT NULL,
    [Starting Time]               DATETIME           NOT NULL,
    [Ending Date]                 DATETIME           NOT NULL,
    [Ending Time]                 DATETIME           NOT NULL,
    [Planning Level Code]         INT                NOT NULL,
    [Priority]                    INT                NOT NULL,
    [Production BOM No_]          NVARCHAR (20)      NOT NULL,
    [Routing No_]                 NVARCHAR (20)      NOT NULL,
    [Inventory Posting Group]     NVARCHAR (20)      NOT NULL,
    [Routing Reference No_]       INT                NOT NULL,
    [Unit Cost]                   DECIMAL (38, 20)   NOT NULL,
    [Cost Amount]                 DECIMAL (38, 20)   NOT NULL,
    [Unit of Measure Code]        NVARCHAR (10)      NOT NULL,
    [Quantity (Base)]             DECIMAL (38, 20)   NOT NULL,
    [Finished Qty_ (Base)]        DECIMAL (38, 20)   NOT NULL,
    [Remaining Qty_ (Base)]       DECIMAL (38, 20)   NOT NULL,
    [Starting Date-Time]          DATETIME           NOT NULL,
    [Ending Date-Time]            DATETIME           NOT NULL,
    [Dimension Set ID]            INT                NOT NULL,
    [Cost Amount (ACY)]           DECIMAL (38, 20)   NOT NULL,
    [Unit Cost (ACY)]             DECIMAL (38, 20)   NOT NULL,
    [Production BOM Version Code] NVARCHAR (20)      NOT NULL,
    [Routing Version Code]        NVARCHAR (20)      NOT NULL,
    [Routing Type]                INT                NOT NULL,
    [Qty_ per Unit of Measure]    DECIMAL (38, 20)   NOT NULL,
    [MPS Order]                   TINYINT            NOT NULL,
    [Planning Flexibility]        INT                NOT NULL,
    [Indirect Cost _]             DECIMAL (38, 20)   NOT NULL,
    [Overhead Rate]               DECIMAL (38, 20)   NOT NULL,
    [$systemId]                   NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]            DATETIME           NOT NULL,
    [$systemCreatedBy]            NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]           DATETIME           NOT NULL,
    [$systemModifiedBy]           NVARCHAR (36)      NOT NULL,
    [PipelineName]                NVARCHAR (200)     CONSTRAINT [DF_ProdOrderLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]               NVARCHAR (36)      CONSTRAINT [DF_ProdOrderLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]         DATETIMEOFFSET (0) CONSTRAINT [DF_ProdOrderLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                   INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_ProdOrderLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Prod_ Order No_] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

