CREATE TABLE [stg_bc].[PurchCrMemoHdr] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [No_]                          NVARCHAR (20)      NOT NULL,
    [Buy-from Vendor No_]          NVARCHAR (20)      NOT NULL,
    [Pay-to Vendor No_]            NVARCHAR (20)      NOT NULL,
    [Pay-to Name]                  NVARCHAR (100)     NOT NULL,
    [Pay-to Name 2]                NVARCHAR (50)      NOT NULL,
    [Pay-to Address]               NVARCHAR (100)     NOT NULL,
    [Pay-to Address 2]             NVARCHAR (50)      NOT NULL,
    [Pay-to City]                  NVARCHAR (30)      NOT NULL,
    [Pay-to Contact]               NVARCHAR (100)     NOT NULL,
    [Your Reference]               NVARCHAR (35)      NOT NULL,
    [Ship-to Code]                 NVARCHAR (10)      NOT NULL,
    [Ship-to Name]                 NVARCHAR (100)     NOT NULL,
    [Ship-to Name 2]               NVARCHAR (50)      NOT NULL,
    [Ship-to Address]              NVARCHAR (100)     NOT NULL,
    [Ship-to Address 2]            NVARCHAR (50)      NOT NULL,
    [Ship-to City]                 NVARCHAR (30)      NOT NULL,
    [Ship-to Contact]              NVARCHAR (100)     NOT NULL,
    [Posting Date]                 DATETIME           NOT NULL,
    [Expected Receipt Date]        DATETIME           NOT NULL,
    [Posting Description]          NVARCHAR (100)     NOT NULL,
    [Payment Terms Code]           NVARCHAR (10)      NOT NULL,
    [Due Date]                     DATETIME           NOT NULL,
    [Payment Discount _]           DECIMAL (18)       NOT NULL,
    [Pmt_ Discount Date]           DATETIME           NOT NULL,
    [Shipment Method Code]         NVARCHAR (10)      NOT NULL,
    [Location Code]                NVARCHAR (10)      NOT NULL,
    [Shortcut Dimension 1 Code]    NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]    NVARCHAR (20)      NOT NULL,
    [Vendor Posting Group]         NVARCHAR (20)      NOT NULL,
    [Currency Code]                NVARCHAR (10)      NOT NULL,
    [Currency Factor]              DECIMAL (18)       NOT NULL,
    [Prices Including VAT]         TINYINT            NOT NULL,
    [Invoice Disc_ Code]           NVARCHAR (20)      NOT NULL,
    [Language Code]                NVARCHAR (10)      NOT NULL,
    [Purchaser Code]               NVARCHAR (20)      NOT NULL,
    [No_ Printed]                  INT                NOT NULL,
    [On Hold]                      NVARCHAR (3)       NOT NULL,
    [Applies-to Doc_ Type]         INT                NOT NULL,
    [Applies-to Doc_ No_]          NVARCHAR (20)      NOT NULL,
    [Bal_ Account No_]             NVARCHAR (20)      NOT NULL,
    [Vendor Cr_ Memo No_]          NVARCHAR (35)      NOT NULL,
    [VAT Registration No_]         NVARCHAR (20)      NOT NULL,
    [Sell-to Customer No_]         NVARCHAR (20)      NOT NULL,
    [Reason Code]                  NVARCHAR (10)      NOT NULL,
    [Gen_ Bus_ Posting Group]      NVARCHAR (20)      NOT NULL,
    [Transaction Type]             NVARCHAR (10)      NOT NULL,
    [Transport Method]             NVARCHAR (10)      NOT NULL,
    [VAT Country_Region Code]      NVARCHAR (10)      NOT NULL,
    [Buy-from Vendor Name]         NVARCHAR (100)     NOT NULL,
    [Buy-from Vendor Name 2]       NVARCHAR (50)      NOT NULL,
    [Buy-from Address]             NVARCHAR (100)     NOT NULL,
    [Buy-from Address 2]           NVARCHAR (50)      NOT NULL,
    [Buy-from City]                NVARCHAR (30)      NOT NULL,
    [Buy-from Contact]             NVARCHAR (100)     NOT NULL,
    [Pay-to Post Code]             NVARCHAR (20)      NOT NULL,
    [Pay-to County]                NVARCHAR (30)      NOT NULL,
    [Pay-to Country_Region Code]   NVARCHAR (10)      NOT NULL,
    [Buy-from Post Code]           NVARCHAR (20)      NOT NULL,
    [Buy-from County]              NVARCHAR (30)      NOT NULL,
    [Buy-from Country_Region Code] NVARCHAR (10)      NOT NULL,
    [Ship-to Post Code]            NVARCHAR (20)      NOT NULL,
    [Ship-to County]               NVARCHAR (30)      NOT NULL,
    [Ship-to Country_Region Code]  NVARCHAR (10)      NOT NULL,
    [Bal_ Account Type]            INT                NOT NULL,
    [Order Address Code]           NVARCHAR (10)      NOT NULL,
    [Entry Point]                  NVARCHAR (10)      NOT NULL,
    [Correction]                   TINYINT            NOT NULL,
    [Document Date]                DATETIME           NOT NULL,
    [Area]                         NVARCHAR (10)      NOT NULL,
    [Transaction Specification]    NVARCHAR (10)      NOT NULL,
    [Payment Method Code]          NVARCHAR (10)      NOT NULL,
    [Pre-Assigned No_ Series]      NVARCHAR (20)      NOT NULL,
    [No_ Series]                   NVARCHAR (20)      NOT NULL,
    [Pre-Assigned No_]             NVARCHAR (20)      NOT NULL,
    [User ID]                      NVARCHAR (50)      NOT NULL,
    [Source Code]                  NVARCHAR (10)      NOT NULL,
    [Tax Area Code]                NVARCHAR (20)      NOT NULL,
    [Tax Liable]                   TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]       NVARCHAR (20)      NOT NULL,
    [VAT Base Discount _]          DECIMAL (18)       NOT NULL,
    [Prepmt_ Cr_ Memo No_ Series]  NVARCHAR (20)      NOT NULL,
    [Prepayment Credit Memo]       TINYINT            NOT NULL,
    [Prepayment Order No_]         NVARCHAR (20)      NOT NULL,
    [Dimension Set ID]             INT                NOT NULL,
    [Vendor Ledger Entry No_]      INT                NOT NULL,
    [Campaign No_]                 NVARCHAR (20)      NOT NULL,
    [Buy-from Contact No_]         NVARCHAR (20)      NOT NULL,
    [Pay-to Contact No_]           NVARCHAR (20)      NOT NULL,
    [Responsibility Center]        NVARCHAR (10)      NOT NULL,
    [Return Order No_]             NVARCHAR (20)      NOT NULL,
    [Return Order No_ Series]      NVARCHAR (20)      NOT NULL,
    [Price Calculation Method]     INT                NOT NULL,
    [$systemId]                    NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]             DATETIME           NOT NULL,
    [$systemCreatedBy]             NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]            DATETIME           NOT NULL,
    [$systemModifiedBy]            NVARCHAR (36)      NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_PurchCrMemoHdr_PipeHdrName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_PurchCrMemoHdr_PipeHdrRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_PurchCrMemoHdr_PipeHdrTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_PurchCrMemoHdr] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

