CREATE TABLE [stg_bc].[PurchCrMemoLine] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Document No_]                   NVARCHAR (20)      NOT NULL,
    [Line No_]                       INT                NOT NULL,
    [Buy-from Vendor No_]            NVARCHAR (20)      NOT NULL,
    [Type]                           INT                NOT NULL,
    [No_]                            NVARCHAR (20)      NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Posting Group]                  NVARCHAR (20)      NOT NULL,
    [Expected Receipt Date]          DATETIME           NOT NULL,
    [Description]                    NVARCHAR (100)     NOT NULL,
    [Description 2]                  NVARCHAR (50)      NOT NULL,
    [Unit of Measure]                NVARCHAR (50)      NOT NULL,
    [Quantity]                       DECIMAL (18)       NOT NULL,
    [Direct Unit Cost]               DECIMAL (18)       NOT NULL,
    [Unit Cost (LCY)]                DECIMAL (18)       NOT NULL,
    [VAT _]                          DECIMAL (18)       NOT NULL,
    [Line Discount _]                DECIMAL (18)       NOT NULL,
    [Line Discount Amount]           DECIMAL (18)       NOT NULL,
    [Amount]                         DECIMAL (18)       NOT NULL,
    [Amount Including VAT]           DECIMAL (18)       NOT NULL,
    [Unit Price (LCY)]               DECIMAL (18)       NOT NULL,
    [Allow Invoice Disc_]            TINYINT            NOT NULL,
    [Gross Weight]                   DECIMAL (18)       NOT NULL,
    [Net Weight]                     DECIMAL (18)       NOT NULL,
    [Units per Parcel]               DECIMAL (18)       NOT NULL,
    [Unit Volume]                    DECIMAL (18)       NOT NULL,
    [Appl_-to Item Entry]            INT                NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Job No_]                        NVARCHAR (20)      NOT NULL,
    [Indirect Cost _]                DECIMAL (18)       NOT NULL,
    [Order No_]                      NVARCHAR (20)      NOT NULL,
    [Order Line No_]                 INT                NOT NULL,
    [Pay-to Vendor No_]              NVARCHAR (20)      NOT NULL,
    [Inv_ Discount Amount]           DECIMAL (18)       NOT NULL,
    [Vendor Item No_]                NVARCHAR (50)      NOT NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)      NOT NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (20)      NOT NULL,
    [VAT Calculation Type]           INT                NOT NULL,
    [Transaction Type]               NVARCHAR (10)      NOT NULL,
    [Transport Method]               NVARCHAR (10)      NOT NULL,
    [Attached to Line No_]           INT                NOT NULL,
    [Entry Point]                    NVARCHAR (10)      NOT NULL,
    [Area]                           NVARCHAR (10)      NOT NULL,
    [Transaction Specification]      NVARCHAR (10)      NOT NULL,
    [Tax Area Code]                  NVARCHAR (20)      NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [Tax Group Code]                 NVARCHAR (20)      NOT NULL,
    [Use Tax]                        TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)      NOT NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (20)      NOT NULL,
    [Blanket Order No_]              NVARCHAR (20)      NOT NULL,
    [Blanket Order Line No_]         INT                NOT NULL,
    [VAT Base Amount]                DECIMAL (18)       NOT NULL,
    [Unit Cost]                      DECIMAL (18)       NOT NULL,
    [System-Created Entry]           TINYINT            NOT NULL,
    [Line Amount]                    DECIMAL (18)       NOT NULL,
    [VAT Difference]                 DECIMAL (18)       NOT NULL,
    [VAT Identifier]                 NVARCHAR (20)      NOT NULL,
    [IC Partner Ref_ Type]           INT                NOT NULL,
    [IC Partner Reference]           NVARCHAR (20)      NOT NULL,
    [Prepayment Line]                TINYINT            NOT NULL,
    [IC Partner Code]                NVARCHAR (20)      NOT NULL,
    [Posting Date]                   DATETIME           NOT NULL,
    [IC Item Reference No_]          NVARCHAR (50)      NOT NULL,
    [Pmt_ Discount Amount]           DECIMAL (18)       NOT NULL,
    [Dimension Set ID]               INT                NOT NULL,
    [Job Task No_]                   NVARCHAR (20)      NOT NULL,
    [Job Line Type]                  INT                NOT NULL,
    [Job Unit Price]                 DECIMAL (18)       NOT NULL,
    [Job Total Price]                DECIMAL (18)       NOT NULL,
    [Job Line Amount]                DECIMAL (18)       NOT NULL,
    [Job Line Discount Amount]       DECIMAL (18)       NOT NULL,
    [Job Line Discount _]            DECIMAL (18)       NOT NULL,
    [Job Unit Price (LCY)]           DECIMAL (18)       NOT NULL,
    [Job Total Price (LCY)]          DECIMAL (18)       NOT NULL,
    [Job Line Amount (LCY)]          DECIMAL (18)       NOT NULL,
    [Job Line Disc_ Amount (LCY)]    DECIMAL (18)       NOT NULL,
    [Job Currency Factor]            DECIMAL (18)       NOT NULL,
    [Job Currency Code]              NVARCHAR (20)      NOT NULL,
    [Deferral Code]                  NVARCHAR (10)      NOT NULL,
    [Prod_ Order No_]                NVARCHAR (20)      NOT NULL,
    [Variant Code]                   NVARCHAR (10)      NOT NULL,
    [Bin Code]                       NVARCHAR (20)      NOT NULL,
    [Qty_ per Unit of Measure]       DECIMAL (18)       NOT NULL,
    [Unit of Measure Code]           NVARCHAR (10)      NOT NULL,
    [Quantity (Base)]                DECIMAL (18)       NOT NULL,
    [FA Posting Date]                DATETIME           NOT NULL,
    [FA Posting Type]                INT                NOT NULL,
    [Depreciation Book Code]         NVARCHAR (10)      NOT NULL,
    [Salvage Value]                  DECIMAL (18)       NOT NULL,
    [Depr_ until FA Posting Date]    TINYINT            NOT NULL,
    [Depr_ Acquisition Cost]         TINYINT            NOT NULL,
    [Maintenance Code]               NVARCHAR (10)      NOT NULL,
    [Insurance No_]                  NVARCHAR (20)      NOT NULL,
    [Budgeted FA No_]                NVARCHAR (20)      NOT NULL,
    [Duplicate in Depreciation Book] NVARCHAR (10)      NOT NULL,
    [Use Duplication List]           TINYINT            NOT NULL,
    [Responsibility Center]          NVARCHAR (10)      NOT NULL,
    [Cross-Reference No_]            NVARCHAR (20)      NOT NULL,
    [Unit of Measure (Cross Ref_)]   NVARCHAR (10)      NOT NULL,
    [Cross-Reference Type]           INT                NOT NULL,
    [Cross-Reference Type No_]       NVARCHAR (30)      NOT NULL,
    [Item Category Code]             NVARCHAR (20)      NOT NULL,
    [Nonstock]                       TINYINT            NOT NULL,
    [Purchasing Code]                NVARCHAR (10)      NOT NULL,
    [Product Group Code]             NVARCHAR (10)      NOT NULL,
    [Item Reference No_]             NVARCHAR (50)      NOT NULL,
    [Item Reference Unit of Measure] NVARCHAR (10)      NOT NULL,
    [Item Reference Type]            INT                NOT NULL,
    [Item Reference Type No_]        NVARCHAR (30)      NOT NULL,
    [Return Shipment No_]            NVARCHAR (20)      NOT NULL,
    [Return Shipment Line No_]       INT                NOT NULL,
    [Return Reason Code]             NVARCHAR (10)      NOT NULL,
    [Price Calculation Method]       INT                NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_PurchCrMemoLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_PurchCrMemoLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_PurchCrMemoLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_PurchCrMemoLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document No_] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

