CREATE TABLE [stg_bc].[RoutingLine] (
    [timestamp]                     VARBINARY (8)      NOT NULL,
    [Routing No_]                   NVARCHAR (20)      NOT NULL,
    [Version Code]                  NVARCHAR (20)      NOT NULL,
    [Operation No_]                 NVARCHAR (10)      NOT NULL,
    [Next Operation No_]            NVARCHAR (30)      NOT NULL,
    [Previous Operation No_]        NVARCHAR (30)      NOT NULL,
    [Type]                          INT                NOT NULL,
    [No_]                           NVARCHAR (20)      NOT NULL,
    [Work Center No_]               NVARCHAR (20)      NOT NULL,
    [Work Center Group Code]        NVARCHAR (10)      NOT NULL,
    [Description]                   NVARCHAR (100)     NOT NULL,
    [Setup Time]                    DECIMAL (38, 20)   NOT NULL,
    [Run Time]                      DECIMAL (38, 20)   NOT NULL,
    [Wait Time]                     DECIMAL (38, 20)   NOT NULL,
    [Move Time]                     DECIMAL (38, 20)   NOT NULL,
    [Fixed Scrap Quantity]          DECIMAL (38, 20)   NOT NULL,
    [Lot Size]                      DECIMAL (38, 20)   NOT NULL,
    [Scrap Factor _]                DECIMAL (38, 20)   NOT NULL,
    [Setup Time Unit of Meas_ Code] NVARCHAR (10)      NOT NULL,
    [Run Time Unit of Meas_ Code]   NVARCHAR (10)      NOT NULL,
    [Wait Time Unit of Meas_ Code]  NVARCHAR (10)      NOT NULL,
    [Move Time Unit of Meas_ Code]  NVARCHAR (10)      NOT NULL,
    [Minimum Process Time]          DECIMAL (38, 20)   NOT NULL,
    [Maximum Process Time]          DECIMAL (38, 20)   NOT NULL,
    [Concurrent Capacities]         DECIMAL (38, 20)   NOT NULL,
    [Send-Ahead Quantity]           DECIMAL (38, 20)   NOT NULL,
    [Routing Link Code]             NVARCHAR (10)      NOT NULL,
    [Standard Task Code]            NVARCHAR (10)      NOT NULL,
    [Unit Cost per]                 DECIMAL (38, 20)   NOT NULL,
    [Recalculate]                   TINYINT            NOT NULL,
    [Sequence No_ (Forward)]        INT                NOT NULL,
    [Sequence No_ (Backward)]       INT                NOT NULL,
    [Fixed Scrap Qty_ (Accum_)]     DECIMAL (38, 20)   NOT NULL,
    [Scrap Factor _ (Accumulated)]  DECIMAL (38, 20)   NOT NULL,
    [$systemId]                     NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]              DATETIME           NOT NULL,
    [$systemCreatedBy]              NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]             DATETIME           NOT NULL,
    [$systemModifiedBy]             NVARCHAR (36)      NOT NULL,
    [PipelineName]                  NVARCHAR (200)     CONSTRAINT [DF_RoutingLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                 NVARCHAR (36)      CONSTRAINT [DF_RoutingLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]           DATETIMEOFFSET (0) CONSTRAINT [DF_RoutingLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                     INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_RoutingLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Routing No_] ASC, [Version Code] ASC, [Operation No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

