CREATE TABLE [stg_bc].[SalesCrMemoLine] (
    [timestamp]                      VARBINARY (8)    NULL,
    [Document No_]                   NVARCHAR (20)    NULL,
    [Line No_]                       INT              NULL,
    [Sell-to Customer No_]           NVARCHAR (20)    NULL,
    [Type]                           INT              NULL,
    [No_]                            NVARCHAR (20)    NULL,
    [Location Code]                  NVARCHAR (10)    NULL,
    [Posting Group]                  NVARCHAR (20)    NULL,
    [Shipment Date]                  DATETIME         NULL,
    [Description]                    NVARCHAR (100)   NULL,
    [Description 2]                  NVARCHAR (50)    NULL,
    [Unit of Measure]                NVARCHAR (50)    NULL,
    [Quantity]                       DECIMAL (38, 20) NULL,
    [Unit Price]                     DECIMAL (38, 20) NULL,
    [Unit Cost (LCY)]                DECIMAL (38, 20) NULL,
    [VAT _]                          DECIMAL (38, 20) NULL,
    [Line Discount _]                DECIMAL (38, 20) NULL,
    [Line Discount Amount]           DECIMAL (38, 20) NULL,
    [Amount]                         DECIMAL (38, 20) NULL,
    [Amount Including VAT]           DECIMAL (38, 20) NULL,
    [Allow Invoice Disc_]            TINYINT          NULL,
    [Gross Weight]                   DECIMAL (38, 20) NULL,
    [Net Weight]                     DECIMAL (38, 20) NULL,
    [Units per Parcel]               DECIMAL (38, 20) NULL,
    [Unit Volume]                    DECIMAL (38, 20) NULL,
    [Appl_-to Item Entry]            INT              NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)    NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)    NULL,
    [Customer Price Group]           NVARCHAR (10)    NULL,
    [Job No_]                        NVARCHAR (20)    NULL,
    [Work Type Code]                 NVARCHAR (10)    NULL,
    [Order No_]                      NVARCHAR (20)    NULL,
    [Order Line No_]                 INT              NULL,
    [Bill-to Customer No_]           NVARCHAR (20)    NULL,
    [Inv_ Discount Amount]           DECIMAL (38, 20) NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)    NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (20)    NULL,
    [VAT Calculation Type]           INT              NULL,
    [Transaction Type]               NVARCHAR (10)    NULL,
    [Transport Method]               NVARCHAR (10)    NULL,
    [Attached to Line No_]           INT              NULL,
    [Exit Point]                     NVARCHAR (10)    NULL,
    [Area]                           NVARCHAR (10)    NULL,
    [Transaction Specification]      NVARCHAR (10)    NULL,
    [Tax Category]                   NVARCHAR (10)    NULL,
    [Tax Area Code]                  NVARCHAR (20)    NULL,
    [Tax Liable]                     TINYINT          NULL,
    [Tax Group Code]                 NVARCHAR (20)    NULL,
    [VAT Clause Code]                NVARCHAR (20)    NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)    NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (20)    NULL,
    [Blanket Order No_]              NVARCHAR (20)    NULL,
    [Blanket Order Line No_]         INT              NULL,
    [VAT Base Amount]                DECIMAL (38, 20) NULL,
    [Unit Cost]                      DECIMAL (38, 20) NULL,
    [System-Created Entry]           TINYINT          NULL,
    [Line Amount]                    DECIMAL (38, 20) NULL,
    [VAT Difference]                 DECIMAL (38, 20) NULL,
    [VAT Identifier]                 NVARCHAR (20)    NULL,
    [IC Partner Ref_ Type]           INT              NULL,
    [IC Partner Reference]           NVARCHAR (20)    NULL,
    [Prepayment Line]                TINYINT          NULL,
    [IC Partner Code]                NVARCHAR (20)    NULL,
    [Posting Date]                   DATETIME         NULL,
    [IC Item Reference No_]          NVARCHAR (50)    NULL,
    [Pmt_ Discount Amount]           DECIMAL (38, 20) NULL,
    [Line Discount Calculation]      INT              NULL,
    [Dimension Set ID]               INT              NULL,
    [Job Task No_]                   NVARCHAR (20)    NULL,
    [Job Contract Entry No_]         INT              NULL,
    [Deferral Code]                  NVARCHAR (10)    NULL,
    [Variant Code]                   NVARCHAR (10)    NULL,
    [Bin Code]                       NVARCHAR (20)    NULL,
    [Qty_ per Unit of Measure]       DECIMAL (38, 20) NULL,
    [Unit of Measure Code]           NVARCHAR (10)    NULL,
    [Quantity (Base)]                DECIMAL (38, 20) NULL,
    [FA Posting Date]                DATETIME         NULL,
    [Depreciation Book Code]         NVARCHAR (10)    NULL,
    [Depr_ until FA Posting Date]    TINYINT          NULL,
    [Duplicate in Depreciation Book] NVARCHAR (10)    NULL,
    [Use Duplication List]           TINYINT          NULL,
    [Responsibility Center]          NVARCHAR (10)    NULL,
    [Cross-Reference No_]            NVARCHAR (20)    NULL,
    [Unit of Measure (Cross Ref_)]   NVARCHAR (10)    NULL,
    [Cross-Reference Type]           INT              NULL,
    [Cross-Reference Type No_]       NVARCHAR (30)    NULL,
    [Item Category Code]             NVARCHAR (20)    NULL,
    [Nonstock]                       TINYINT          NULL,
    [Purchasing Code]                NVARCHAR (10)    NULL,
    [Product Group Code]             NVARCHAR (10)    NULL,
    [Item Reference No_]             NVARCHAR (50)    NULL,
    [Item Reference Unit of Measure] NVARCHAR (10)    NULL,
    [Item Reference Type]            INT              NULL,
    [Item Reference Type No_]        NVARCHAR (30)    NULL,
    [Appl_-from Item Entry]          INT              NULL,
    [Return Receipt No_]             NVARCHAR (20)    NULL,
    [Return Receipt Line No_]        INT              NULL,
    [Return Reason Code]             NVARCHAR (10)    NULL,
    [Price Calculation Method]       INT              NULL,
    [Allow Line Disc_]               TINYINT          NULL,
    [Customer Disc_ Group]           NVARCHAR (20)    NULL,
    [Account Code]                   NVARCHAR (30)    NULL,
    [$systemId]                      NVARCHAR (36)    NULL,
    [$systemCreatedAt]               DATETIME         NULL,
    [$systemCreatedBy]               NVARCHAR (36)    NULL,
    [$systemModifiedAt]              DATETIME         NULL,
    [$systemModifiedBy]              NVARCHAR (36)    NULL,
    [Yearcode Text]                  NVARCHAR (10)    NULL,
    [PipelineName]                   NVARCHAR (MAX)   NULL,
    [PipelineRunId]                  NVARCHAR (MAX)   NULL,
    [PipelineTriggerTime]            NVARCHAR (MAX)   NULL,
    [CompanyID]                      NVARCHAR (MAX)   NULL
);


GO

