CREATE TABLE [stg_bc].[SalesLine] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Document Type]                  INT                NOT NULL,
    [Document No_]                   NVARCHAR (20)      NOT NULL,
    [Line No_]                       INT                NOT NULL,
    [Sell-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Type]                           INT                NOT NULL,
    [No_]                            NVARCHAR (20)      NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Posting Group]                  NVARCHAR (20)      NOT NULL,
    [Shipment Date]                  DATETIME           NOT NULL,
    [Description]                    NVARCHAR (100)     NOT NULL,
    [Description 2]                  NVARCHAR (50)      NOT NULL,
    [Unit of Measure]                NVARCHAR (50)      NOT NULL,
    [Quantity]                       DECIMAL (38, 20)   NOT NULL,
    [Outstanding Quantity]           DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Invoice]                DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Ship]                   DECIMAL (38, 20)   NOT NULL,
    [Unit Price]                     DECIMAL (38, 20)   NOT NULL,
    [Unit Cost (LCY)]                DECIMAL (38, 20)   NOT NULL,
    [VAT _]                          DECIMAL (38, 20)   NOT NULL,
    [Line Discount _]                DECIMAL (38, 20)   NOT NULL,
    [Line Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Amount]                         DECIMAL (38, 20)   NOT NULL,
    [Amount Including VAT]           DECIMAL (38, 20)   NOT NULL,
    [Allow Invoice Disc_]            TINYINT            NOT NULL,
    [Gross Weight]                   DECIMAL (38, 20)   NOT NULL,
    [Net Weight]                     DECIMAL (38, 20)   NOT NULL,
    [Units per Parcel]               DECIMAL (38, 20)   NOT NULL,
    [Unit Volume]                    DECIMAL (38, 20)   NOT NULL,
    [Appl_-to Item Entry]            INT                NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Customer Price Group]           NVARCHAR (10)      NOT NULL,
    [Job No_]                        NVARCHAR (20)      NOT NULL,
    [Work Type Code]                 NVARCHAR (10)      NOT NULL,
    [Recalculate Invoice Disc_]      TINYINT            NOT NULL,
    [Outstanding Amount]             DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped Not Invoiced]      DECIMAL (38, 20)   NOT NULL,
    [Shipped Not Invoiced]           DECIMAL (38, 20)   NOT NULL,
    [Quantity Shipped]               DECIMAL (38, 20)   NOT NULL,
    [Quantity Invoiced]              DECIMAL (38, 20)   NOT NULL,
    [Shipment No_]                   NVARCHAR (20)      NOT NULL,
    [Shipment Line No_]              INT                NOT NULL,
    [Profit _]                       DECIMAL (38, 20)   NOT NULL,
    [Bill-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Inv_ Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Purchase Order No_]             NVARCHAR (20)      NOT NULL,
    [Purch_ Order Line No_]          INT                NOT NULL,
    [Drop Shipment]                  TINYINT            NOT NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)      NOT NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (20)      NOT NULL,
    [VAT Calculation Type]           INT                NOT NULL,
    [Transaction Type]               NVARCHAR (10)      NOT NULL,
    [Transport Method]               NVARCHAR (10)      NOT NULL,
    [Attached to Line No_]           INT                NOT NULL,
    [Exit Point]                     NVARCHAR (10)      NOT NULL,
    [Area]                           NVARCHAR (10)      NOT NULL,
    [Transaction Specification]      NVARCHAR (10)      NOT NULL,
    [Tax Category]                   NVARCHAR (10)      NOT NULL,
    [Tax Area Code]                  NVARCHAR (20)      NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [Tax Group Code]                 NVARCHAR (20)      NOT NULL,
    [VAT Clause Code]                NVARCHAR (20)      NOT NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)      NOT NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (20)      NOT NULL,
    [Currency Code]                  NVARCHAR (10)      NOT NULL,
    [Outstanding Amount (LCY)]       DECIMAL (38, 20)   NOT NULL,
    [Shipped Not Invoiced (LCY)]     DECIMAL (38, 20)   NOT NULL,
    [Shipped Not Inv_ (LCY) No VAT]  DECIMAL (38, 20)   NOT NULL,
    [Reserve]                        INT                NOT NULL,
    [Blanket Order No_]              NVARCHAR (20)      NOT NULL,
    [Blanket Order Line No_]         INT                NOT NULL,
    [VAT Base Amount]                DECIMAL (38, 20)   NOT NULL,
    [Unit Cost]                      DECIMAL (38, 20)   NOT NULL,
    [System-Created Entry]           TINYINT            NOT NULL,
    [Line Amount]                    DECIMAL (38, 20)   NOT NULL,
    [VAT Difference]                 DECIMAL (38, 20)   NOT NULL,
    [Inv_ Disc_ Amount to Invoice]   DECIMAL (38, 20)   NOT NULL,
    [VAT Identifier]                 NVARCHAR (20)      NOT NULL,
    [IC Partner Ref_ Type]           INT                NOT NULL,
    [IC Partner Reference]           NVARCHAR (20)      NOT NULL,
    [Prepayment _]                   DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Line Amount]            DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Amt_ Inv_]              DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Amt_ Incl_ VAT]         DECIMAL (38, 20)   NOT NULL,
    [Prepayment Amount]              DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ VAT Base Amt_]          DECIMAL (38, 20)   NOT NULL,
    [Prepayment VAT _]               DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ VAT Calc_ Type]         INT                NOT NULL,
    [Prepayment VAT Identifier]      NVARCHAR (20)      NOT NULL,
    [Prepayment Tax Area Code]       NVARCHAR (20)      NOT NULL,
    [Prepayment Tax Liable]          TINYINT            NOT NULL,
    [Prepayment Tax Group Code]      NVARCHAR (20)      NOT NULL,
    [Prepmt Amt to Deduct]           DECIMAL (38, 20)   NOT NULL,
    [Prepmt Amt Deducted]            DECIMAL (38, 20)   NOT NULL,
    [Prepayment Line]                TINYINT            NOT NULL,
    [Prepmt_ Amount Inv_ Incl_ VAT]  DECIMAL (38, 20)   NOT NULL,
    [Prepmt_ Amount Inv_ (LCY)]      DECIMAL (38, 20)   NOT NULL,
    [IC Partner Code]                NVARCHAR (20)      NOT NULL,
    [Prepmt_ VAT Amount Inv_ (LCY)]  DECIMAL (38, 20)   NOT NULL,
    [Prepayment VAT Difference]      DECIMAL (38, 20)   NOT NULL,
    [Prepmt VAT Diff_ to Deduct]     DECIMAL (38, 20)   NOT NULL,
    [Prepmt VAT Diff_ Deducted]      DECIMAL (38, 20)   NOT NULL,
    [IC Item Reference No_]          NVARCHAR (50)      NOT NULL,
    [Pmt_ Discount Amount]           DECIMAL (38, 20)   NOT NULL,
    [Line Discount Calculation]      INT                NOT NULL,
    [Dimension Set ID]               INT                NOT NULL,
    [Qty_ to Assemble to Order]      DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Asm_ to Order (Base)]   DECIMAL (38, 20)   NOT NULL,
    [Job Task No_]                   NVARCHAR (20)      NOT NULL,
    [Job Contract Entry No_]         INT                NOT NULL,
    [Deferral Code]                  NVARCHAR (10)      NOT NULL,
    [Returns Deferral Start Date]    DATETIME           NOT NULL,
    [Variant Code]                   NVARCHAR (10)      NOT NULL,
    [Bin Code]                       NVARCHAR (20)      NOT NULL,
    [Qty_ per Unit of Measure]       DECIMAL (38, 20)   NOT NULL,
    [Planned]                        TINYINT            NOT NULL,
    [Unit of Measure Code]           NVARCHAR (10)      NOT NULL,
    [Quantity (Base)]                DECIMAL (38, 20)   NOT NULL,
    [Outstanding Qty_ (Base)]        DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Invoice (Base)]         DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Ship (Base)]            DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped Not Invd_ (Base)]  DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped (Base)]            DECIMAL (38, 20)   NOT NULL,
    [Qty_ Invoiced (Base)]           DECIMAL (38, 20)   NOT NULL,
    [FA Posting Date]                DATETIME           NOT NULL,
    [Depreciation Book Code]         NVARCHAR (10)      NOT NULL,
    [Depr_ until FA Posting Date]    TINYINT            NOT NULL,
    [Duplicate in Depreciation Book] NVARCHAR (10)      NOT NULL,
    [Use Duplication List]           TINYINT            NOT NULL,
    [Responsibility Center]          NVARCHAR (10)      NOT NULL,
    [Out-of-Stock Substitution]      TINYINT            NOT NULL,
    [Originally Ordered No_]         NVARCHAR (20)      NOT NULL,
    [Originally Ordered Var_ Code]   NVARCHAR (10)      NOT NULL,
    [Cross-Reference No_]            NVARCHAR (20)      NOT NULL,
    [Unit of Measure (Cross Ref_)]   NVARCHAR (10)      NOT NULL,
    [Cross-Reference Type]           INT                NOT NULL,
    [Cross-Reference Type No_]       NVARCHAR (30)      NOT NULL,
    [Item Category Code]             NVARCHAR (20)      NOT NULL,
    [Nonstock]                       TINYINT            NOT NULL,
    [Purchasing Code]                NVARCHAR (10)      NOT NULL,
    [Product Group Code]             NVARCHAR (10)      NOT NULL,
    [Special Order]                  TINYINT            NOT NULL,
    [Special Order Purchase No_]     NVARCHAR (20)      NOT NULL,
    [Special Order Purch_ Line No_]  INT                NOT NULL,
    [Item Reference No_]             NVARCHAR (50)      NOT NULL,
    [Item Reference Unit of Measure] NVARCHAR (10)      NOT NULL,
    [Item Reference Type]            INT                NOT NULL,
    [Item Reference Type No_]        NVARCHAR (30)      NOT NULL,
    [Completely Shipped]             TINYINT            NOT NULL,
    [Requested Delivery Date]        DATETIME           NOT NULL,
    [Promised Delivery Date]         DATETIME           NOT NULL,
    [Shipping Time]                  VARCHAR (32)       NOT NULL,
    [Outbound Whse_ Handling Time]   VARCHAR (32)       NOT NULL,
    [Planned Delivery Date]          DATETIME           NOT NULL,
    [Planned Shipment Date]          DATETIME           NOT NULL,
    [Shipping Agent Code]            NVARCHAR (10)      NOT NULL,
    [Shipping Agent Service Code]    NVARCHAR (10)      NOT NULL,
    [Allow Item Charge Assignment]   TINYINT            NOT NULL,
    [Return Qty_ to Receive]         DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ to Receive (Base)]  DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ Rcd_ Not Invd_]     DECIMAL (38, 20)   NOT NULL,
    [Ret_ Qty_ Rcd_ Not Invd_(Base)] DECIMAL (38, 20)   NOT NULL,
    [Return Rcd_ Not Invd_]          DECIMAL (38, 20)   NOT NULL,
    [Return Rcd_ Not Invd_ (LCY)]    DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ Received]           DECIMAL (38, 20)   NOT NULL,
    [Return Qty_ Received (Base)]    DECIMAL (38, 20)   NOT NULL,
    [Appl_-from Item Entry]          INT                NOT NULL,
    [BOM Item No_]                   NVARCHAR (20)      NOT NULL,
    [Return Receipt No_]             NVARCHAR (20)      NOT NULL,
    [Return Receipt Line No_]        INT                NOT NULL,
    [Return Reason Code]             NVARCHAR (10)      NOT NULL,
    [Copied From Posted Doc_]        TINYINT            NOT NULL,
    [Price Calculation Method]       INT                NOT NULL,
    [Allow Line Disc_]               TINYINT            NOT NULL,
    [Customer Disc_ Group]           NVARCHAR (20)      NOT NULL,
    [Subtype]                        INT                NOT NULL,
    [Price description]              NVARCHAR (80)      NOT NULL,
    [Account Code]                   NVARCHAR (30)      NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_SalesLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_SalesLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_SalesLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    [Used Campaign NOTO]             NVARCHAR (255)     NULL,
    CONSTRAINT [PK_stg_bc_SalesLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document Type] ASC, [Document No_] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

CREATE NONCLUSTERED INDEX [NIX_stg_bc_SalesLine_DocumentNo_CompanyID_WithIncluded]
    ON [stg_bc].[SalesLine]([Document No_] ASC, [CompanyID] ASC)
    INCLUDE([Dimension Set ID]) WITH (DATA_COMPRESSION = ROW);


GO

