CREATE TABLE [stg_bc].[SalesHeader] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Document Type]                  INT                NOT NULL,
    [No_]                            NVARCHAR (20)      NOT NULL,
    [Sell-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Bill-to Customer No_]           NVARCHAR (20)      NOT NULL,
    [Bill-to Name]                   NVARCHAR (100)     NOT NULL,
    [Bill-to Name 2]                 NVARCHAR (50)      NOT NULL,
    [Bill-to Address]                NVARCHAR (100)     NOT NULL,
    [Bill-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Bill-to City]                   NVARCHAR (30)      NOT NULL,
    [Bill-to Contact]                NVARCHAR (100)     NOT NULL,
    [Your Reference]                 NVARCHAR (35)      NOT NULL,
    [Ship-to Code]                   NVARCHAR (10)      NOT NULL,
    [Ship-to Name]                   NVARCHAR (100)     NOT NULL,
    [Ship-to Name 2]                 NVARCHAR (50)      NOT NULL,
    [Ship-to Address]                NVARCHAR (100)     NOT NULL,
    [Ship-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Ship-to City]                   NVARCHAR (30)      NOT NULL,
    [Ship-to Contact]                NVARCHAR (100)     NOT NULL,
    [Order Date]                     DATETIME           NOT NULL,
    [Posting Date]                   DATETIME           NOT NULL,
    [Shipment Date]                  DATETIME           NOT NULL,
    [Posting Description]            NVARCHAR (100)     NOT NULL,
    [Payment Terms Code]             NVARCHAR (10)      NOT NULL,
    [Due Date]                       DATETIME           NOT NULL,
    [Payment Discount _]             DECIMAL (38, 20)   NOT NULL,
    [Pmt_ Discount Date]             DATETIME           NOT NULL,
    [Shipment Method Code]           NVARCHAR (10)      NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Customer Posting Group]         NVARCHAR (20)      NOT NULL,
    [Currency Code]                  NVARCHAR (10)      NOT NULL,
    [Currency Factor]                DECIMAL (38, 20)   NOT NULL,
    [Customer Price Group]           NVARCHAR (10)      NOT NULL,
    [Prices Including VAT]           TINYINT            NOT NULL,
    [Invoice Disc_ Code]             NVARCHAR (20)      NOT NULL,
    [Customer Disc_ Group]           NVARCHAR (20)      NOT NULL,
    [Language Code]                  NVARCHAR (10)      NOT NULL,
    [Salesperson Code]               NVARCHAR (20)      NOT NULL,
    [Order Class]                    NVARCHAR (10)      NOT NULL,
    [No_ Printed]                    INT                NOT NULL,
    [On Hold]                        NVARCHAR (3)       NOT NULL,
    [Applies-to Doc_ Type]           INT                NOT NULL,
    [Applies-to Doc_ No_]            NVARCHAR (20)      NOT NULL,
    [Bal_ Account No_]               NVARCHAR (20)      NOT NULL,
    [Ship]                           TINYINT            NOT NULL,
    [Invoice]                        TINYINT            NOT NULL,
    [Print Posted Documents]         TINYINT            NOT NULL,
    [Shipping No_]                   NVARCHAR (20)      NOT NULL,
    [Posting No_]                    NVARCHAR (20)      NOT NULL,
    [Last Shipping No_]              NVARCHAR (20)      NOT NULL,
    [Last Posting No_]               NVARCHAR (20)      NOT NULL,
    [Prepayment No_]                 NVARCHAR (20)      NOT NULL,
    [Last Prepayment No_]            NVARCHAR (20)      NOT NULL,
    [Prepmt_ Cr_ Memo No_]           NVARCHAR (20)      NOT NULL,
    [Last Prepmt_ Cr_ Memo No_]      NVARCHAR (20)      NOT NULL,
    [VAT Registration No_]           NVARCHAR (20)      NOT NULL,
    [Combine Shipments]              TINYINT            NOT NULL,
    [Reason Code]                    NVARCHAR (10)      NOT NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (20)      NOT NULL,
    [EU 3-Party Trade]               TINYINT            NOT NULL,
    [Transaction Type]               NVARCHAR (10)      NOT NULL,
    [Transport Method]               NVARCHAR (10)      NOT NULL,
    [VAT Country_Region Code]        NVARCHAR (10)      NOT NULL,
    [Sell-to Customer Name]          NVARCHAR (100)     NOT NULL,
    [Sell-to Customer Name 2]        NVARCHAR (50)      NOT NULL,
    [Sell-to Address]                NVARCHAR (100)     NOT NULL,
    [Sell-to Address 2]              NVARCHAR (50)      NOT NULL,
    [Sell-to City]                   NVARCHAR (30)      NOT NULL,
    [Sell-to Contact]                NVARCHAR (100)     NOT NULL,
    [Bill-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Bill-to County]                 NVARCHAR (30)      NOT NULL,
    [Bill-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [Sell-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Sell-to County]                 NVARCHAR (30)      NOT NULL,
    [Sell-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [Ship-to Post Code]              NVARCHAR (20)      NOT NULL,
    [Ship-to County]                 NVARCHAR (30)      NOT NULL,
    [Ship-to Country_Region Code]    NVARCHAR (10)      NOT NULL,
    [Bal_ Account Type]              INT                NOT NULL,
    [Exit Point]                     NVARCHAR (10)      NOT NULL,
    [Correction]                     TINYINT            NOT NULL,
    [Document Date]                  DATETIME           NOT NULL,
    [External Document No_]          NVARCHAR (35)      NOT NULL,
    [Area]                           NVARCHAR (10)      NOT NULL,
    [Transaction Specification]      NVARCHAR (10)      NOT NULL,
    [Payment Method Code]            NVARCHAR (10)      NOT NULL,
    [Shipping Agent Code]            NVARCHAR (10)      NOT NULL,
    [Package Tracking No_]           NVARCHAR (30)      NOT NULL,
    [No_ Series]                     NVARCHAR (20)      NOT NULL,
    [Posting No_ Series]             NVARCHAR (20)      NOT NULL,
    [Shipping No_ Series]            NVARCHAR (20)      NOT NULL,
    [Tax Area Code]                  NVARCHAR (20)      NOT NULL,
    [Tax Liable]                     TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (20)      NOT NULL,
    [Reserve]                        INT                NOT NULL,
    [Applies-to ID]                  NVARCHAR (50)      NOT NULL,
    [VAT Base Discount _]            DECIMAL (38, 20)   NOT NULL,
    [Status]                         INT                NOT NULL,
    [Invoice Discount Calculation]   INT                NOT NULL,
    [Invoice Discount Value]         DECIMAL (38, 20)   NOT NULL,
    [Send IC Document]               TINYINT            NOT NULL,
    [IC Status]                      INT                NOT NULL,
    [Sell-to IC Partner Code]        NVARCHAR (20)      NOT NULL,
    [Bill-to IC Partner Code]        NVARCHAR (20)      NOT NULL,
    [IC Direction]                   INT                NOT NULL,
    [Prepayment _]                   DECIMAL (38, 20)   NOT NULL,
    [Prepayment No_ Series]          NVARCHAR (20)      NOT NULL,
    [Compress Prepayment]            TINYINT            NOT NULL,
    [Prepayment Due Date]            DATETIME           NOT NULL,
    [Prepmt_ Cr_ Memo No_ Series]    NVARCHAR (20)      NOT NULL,
    [Prepmt_ Posting Description]    NVARCHAR (100)     NOT NULL,
    [Prepmt_ Pmt_ Discount Date]     DATETIME           NOT NULL,
    [Prepmt_ Payment Terms Code]     NVARCHAR (10)      NOT NULL,
    [Prepmt_ Payment Discount _]     DECIMAL (38, 20)   NOT NULL,
    [Quote No_]                      NVARCHAR (20)      NOT NULL,
    [Quote Valid Until Date]         DATETIME           NOT NULL,
    [Quote Sent to Customer]         DATETIME           NOT NULL,
    [Quote Accepted]                 TINYINT            NOT NULL,
    [Quote Accepted Date]            DATETIME           NOT NULL,
    [Job Queue Status]               INT                NOT NULL,
    [Job Queue Entry ID]             NVARCHAR (36)      NOT NULL,
    [Incoming Document Entry No_]    INT                NOT NULL,
    [IsTest]                         TINYINT            NOT NULL,
    [Sell-to Phone No_]              NVARCHAR (30)      NOT NULL,
    [Sell-to E-Mail]                 NVARCHAR (80)      NOT NULL,
    [Payment Instructions Id]        INT                NOT NULL,
    [Work Description]               VARBINARY (MAX)    NULL,
    [Dimension Set ID]               INT                NOT NULL,
    [Payment Service Set ID]         INT                NOT NULL,
    [Direct Debit Mandate ID]        NVARCHAR (35)      NOT NULL,
    [Doc_ No_ Occurrence]            INT                NOT NULL,
    [Campaign No_]                   NVARCHAR (20)      NOT NULL,
    [Sell-to Customer Template Code] NVARCHAR (10)      NOT NULL,
    [Sell-to Contact No_]            NVARCHAR (20)      NOT NULL,
    [Bill-to Contact No_]            NVARCHAR (20)      NOT NULL,
    [Bill-to Customer Template Code] NVARCHAR (10)      NOT NULL,
    [Opportunity No_]                NVARCHAR (20)      NOT NULL,
    [Sell-to Customer Templ_ Code]   NVARCHAR (20)      NOT NULL,
    [Bill-to Customer Templ_ Code]   NVARCHAR (20)      NOT NULL,
    [Responsibility Center]          NVARCHAR (10)      NOT NULL,
    [Shipping Advice]                INT                NOT NULL,
    [Posting from Whse_ Ref_]        INT                NOT NULL,
    [Requested Delivery Date]        DATETIME           NOT NULL,
    [Promised Delivery Date]         DATETIME           NOT NULL,
    [Shipping Time]                  VARCHAR (32)       NOT NULL,
    [Outbound Whse_ Handling Time]   VARCHAR (32)       NOT NULL,
    [Shipping Agent Service Code]    NVARCHAR (10)      NOT NULL,
    [Receive]                        TINYINT            NOT NULL,
    [Return Receipt No_]             NVARCHAR (20)      NOT NULL,
    [Return Receipt No_ Series]      NVARCHAR (20)      NOT NULL,
    [Last Return Receipt No_]        NVARCHAR (20)      NOT NULL,
    [Price Calculation Method]       INT                NOT NULL,
    [Allow Line Disc_]               TINYINT            NOT NULL,
    [Get Shipment Used]              TINYINT            NOT NULL,
    [Id]                             NVARCHAR (36)      NOT NULL,
    [Assigned User ID]               NVARCHAR (50)      NOT NULL,
    [EAN No_]                        NVARCHAR (13)      NOT NULL,
    [Account Code]                   NVARCHAR (30)      NOT NULL,
    [OIOUBL Profile Code]            NVARCHAR (10)      NOT NULL,
    [Sell-to Contact Phone No_]      NVARCHAR (30)      NOT NULL,
    [Sell-to Contact Fax No_]        NVARCHAR (30)      NOT NULL,
    [Sell-to Contact E-Mail]         NVARCHAR (80)      NOT NULL,
    [Sell-to Contact Role]           INT                NOT NULL,
    [Payment Channel]                INT                NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_SalesHeader_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_SalesHeader_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_SalesHeader_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_SalesHeader] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document Type] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

CREATE NONCLUSTERED INDEX [NIX_stg_bc_SalesHeader_No_CompanyID]
    ON [stg_bc].[SalesHeader]([No_] ASC, [CompanyID] ASC) WITH (DATA_COMPRESSION = ROW);


GO

