CREATE TABLE [stg_bc].[StockkeepingUnit] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [Location Code]                  NVARCHAR (10)      NOT NULL,
    [Item No_]                       NVARCHAR (20)      NOT NULL,
    [Variant Code]                   NVARCHAR (10)      NOT NULL,
    [Shelf No_]                      NVARCHAR (10)      NOT NULL,
    [Unit Cost]                      DECIMAL (38, 20)   NOT NULL,
    [Standard Cost]                  DECIMAL (38, 20)   NOT NULL,
    [Last Direct Cost]               DECIMAL (38, 20)   NOT NULL,
    [Vendor No_]                     NVARCHAR (20)      NOT NULL,
    [Vendor Item No_]                NVARCHAR (50)      NOT NULL,
    [Lead Time Calculation]          VARCHAR (32)       NOT NULL,
    [Reorder Point]                  DECIMAL (38, 20)   NOT NULL,
    [Maximum Inventory]              DECIMAL (38, 20)   NOT NULL,
    [Reorder Quantity]               DECIMAL (38, 20)   NOT NULL,
    [Last Date Modified]             DATETIME           NOT NULL,
    [Assembly Policy]                INT                NOT NULL,
    [Transfer-Level Code]            INT                NOT NULL,
    [Lot Size]                       DECIMAL (38, 20)   NOT NULL,
    [Discrete Order Quantity]        INT                NOT NULL,
    [Minimum Order Quantity]         DECIMAL (38, 20)   NOT NULL,
    [Maximum Order Quantity]         DECIMAL (38, 20)   NOT NULL,
    [Safety Stock Quantity]          DECIMAL (38, 20)   NOT NULL,
    [Order Multiple]                 DECIMAL (38, 20)   NOT NULL,
    [Safety Lead Time]               VARCHAR (32)       NOT NULL,
    [Components at Location]         NVARCHAR (10)      NOT NULL,
    [Flushing Method]                INT                NOT NULL,
    [Replenishment System]           INT                NOT NULL,
    [Time Bucket]                    VARCHAR (32)       NOT NULL,
    [Reordering Policy]              INT                NOT NULL,
    [Include Inventory]              TINYINT            NOT NULL,
    [Manufacturing Policy]           INT                NOT NULL,
    [Rescheduling Period]            VARCHAR (32)       NOT NULL,
    [Lot Accumulation Period]        VARCHAR (32)       NOT NULL,
    [Dampener Period]                VARCHAR (32)       NOT NULL,
    [Dampener Quantity]              DECIMAL (38, 20)   NOT NULL,
    [Overflow Level]                 DECIMAL (38, 20)   NOT NULL,
    [Transfer-from Code]             NVARCHAR (10)      NOT NULL,
    [Special Equipment Code]         NVARCHAR (10)      NOT NULL,
    [Put-away Template Code]         NVARCHAR (10)      NOT NULL,
    [Put-away Unit of Measure Code]  NVARCHAR (10)      NOT NULL,
    [Phys Invt Counting Period Code] NVARCHAR (10)      NOT NULL,
    [Last Counting Period Update]    DATETIME           NOT NULL,
    [Use Cross-Docking]              TINYINT            NOT NULL,
    [Next Counting Start Date]       DATETIME           NOT NULL,
    [Next Counting End Date]         DATETIME           NOT NULL,
    [Routing No_]                    NVARCHAR (20)      NOT NULL,
    [Production BOM No_]             NVARCHAR (20)      NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_StockkeepingUnit_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_StockkeepingUnit_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_StockkeepingUnit_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_StockkeepingUnit] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Location Code] ASC, [Item No_] ASC, [Variant Code] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

