CREATE TABLE [stg_bc].[TransferHeader] (
    [timestamp]                      VARBINARY (8)      NOT NULL,
    [No_]                            NVARCHAR (20)      NOT NULL,
    [Transfer-from Code]             NVARCHAR (10)      NOT NULL,
    [Transfer-from Name]             NVARCHAR (100)     NOT NULL,
    [Transfer-from Name 2]           NVARCHAR (50)      NOT NULL,
    [Transfer-from Address]          NVARCHAR (100)     NOT NULL,
    [Transfer-from Address 2]        NVARCHAR (50)      NOT NULL,
    [Transfer-from Post Code]        NVARCHAR (20)      NOT NULL,
    [Transfer-from City]             NVARCHAR (30)      NOT NULL,
    [Transfer-from County]           NVARCHAR (30)      NOT NULL,
    [Trsf_-from Country_Region Code] NVARCHAR (10)      NOT NULL,
    [Transfer-to Code]               NVARCHAR (10)      NOT NULL,
    [Transfer-to Name]               NVARCHAR (100)     NOT NULL,
    [Transfer-to Name 2]             NVARCHAR (50)      NOT NULL,
    [Transfer-to Address]            NVARCHAR (100)     NOT NULL,
    [Transfer-to Address 2]          NVARCHAR (50)      NOT NULL,
    [Transfer-to Post Code]          NVARCHAR (20)      NOT NULL,
    [Transfer-to City]               NVARCHAR (30)      NOT NULL,
    [Transfer-to County]             NVARCHAR (30)      NOT NULL,
    [Trsf_-to Country_Region Code]   NVARCHAR (10)      NOT NULL,
    [Posting Date]                   DATETIME           NOT NULL,
    [Shipment Date]                  DATETIME           NOT NULL,
    [Receipt Date]                   DATETIME           NOT NULL,
    [Status]                         INT                NOT NULL,
    [Shortcut Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [In-Transit Code]                NVARCHAR (10)      NOT NULL,
    [No_ Series]                     NVARCHAR (20)      NOT NULL,
    [Last Shipment No_]              NVARCHAR (20)      NOT NULL,
    [Last Receipt No_]               NVARCHAR (20)      NOT NULL,
    [Transfer-from Contact]          NVARCHAR (100)     NOT NULL,
    [Transfer-to Contact]            NVARCHAR (100)     NOT NULL,
    [External Document No_]          NVARCHAR (35)      NOT NULL,
    [Shipping Agent Code]            NVARCHAR (10)      NOT NULL,
    [Shipping Agent Service Code]    NVARCHAR (10)      NOT NULL,
    [Shipping Time]                  VARCHAR (32)       NOT NULL,
    [Shipment Method Code]           NVARCHAR (10)      NOT NULL,
    [Transaction Type]               NVARCHAR (10)      NOT NULL,
    [Transport Method]               NVARCHAR (10)      NOT NULL,
    [Entry_Exit Point]               NVARCHAR (10)      NOT NULL,
    [Area]                           NVARCHAR (10)      NOT NULL,
    [Transaction Specification]      NVARCHAR (10)      NOT NULL,
    [Direct Transfer]                TINYINT            NOT NULL,
    [Dimension Set ID]               INT                NOT NULL,
    [Shipping Advice]                INT                NOT NULL,
    [Posting from Whse_ Ref_]        INT                NOT NULL,
    [Outbound Whse_ Handling Time]   VARCHAR (32)       NOT NULL,
    [Inbound Whse_ Handling Time]    VARCHAR (32)       NOT NULL,
    [Assigned User ID]               NVARCHAR (50)      NOT NULL,
    [$systemId]                      NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]               DATETIME           NOT NULL,
    [$systemCreatedBy]               NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]              DATETIME           NOT NULL,
    [$systemModifiedBy]              NVARCHAR (36)      NOT NULL,
    [PipelineName]                   NVARCHAR (200)     CONSTRAINT [DF_TransferHeader_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                  NVARCHAR (36)      CONSTRAINT [DF_TransferHeader_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]            DATETIMEOFFSET (0) CONSTRAINT [DF_TransferHeader_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                      INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_TransferHeader] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

