CREATE TABLE [stg_bc].[TransferLine] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [Document No_]                 NVARCHAR (20)      NOT NULL,
    [Line No_]                     INT                NOT NULL,
    [Item No_]                     NVARCHAR (20)      NOT NULL,
    [Quantity]                     DECIMAL (38, 20)   NOT NULL,
    [Unit of Measure]              NVARCHAR (50)      NOT NULL,
    [Qty_ to Ship]                 DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Receive]              DECIMAL (38, 20)   NOT NULL,
    [Quantity Shipped]             DECIMAL (38, 20)   NOT NULL,
    [Quantity Received]            DECIMAL (38, 20)   NOT NULL,
    [Status]                       INT                NOT NULL,
    [Shortcut Dimension 1 Code]    NVARCHAR (20)      NOT NULL,
    [Shortcut Dimension 2 Code]    NVARCHAR (20)      NOT NULL,
    [Description]                  NVARCHAR (100)     NOT NULL,
    [Gen_ Prod_ Posting Group]     NVARCHAR (20)      NOT NULL,
    [Inventory Posting Group]      NVARCHAR (20)      NOT NULL,
    [Quantity (Base)]              DECIMAL (38, 20)   NOT NULL,
    [Outstanding Qty_ (Base)]      DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Ship (Base)]          DECIMAL (38, 20)   NOT NULL,
    [Qty_ Shipped (Base)]          DECIMAL (38, 20)   NOT NULL,
    [Qty_ to Receive (Base)]       DECIMAL (38, 20)   NOT NULL,
    [Qty_ Received (Base)]         DECIMAL (38, 20)   NOT NULL,
    [Qty_ per Unit of Measure]     DECIMAL (38, 20)   NOT NULL,
    [Unit of Measure Code]         NVARCHAR (10)      NOT NULL,
    [Outstanding Quantity]         DECIMAL (38, 20)   NOT NULL,
    [Gross Weight]                 DECIMAL (38, 20)   NOT NULL,
    [Net Weight]                   DECIMAL (38, 20)   NOT NULL,
    [Unit Volume]                  DECIMAL (38, 20)   NOT NULL,
    [Variant Code]                 NVARCHAR (10)      NOT NULL,
    [Units per Parcel]             DECIMAL (38, 20)   NOT NULL,
    [Description 2]                NVARCHAR (50)      NOT NULL,
    [In-Transit Code]              NVARCHAR (10)      NOT NULL,
    [Qty_ in Transit]              DECIMAL (38, 20)   NOT NULL,
    [Qty_ in Transit (Base)]       DECIMAL (38, 20)   NOT NULL,
    [Transfer-from Code]           NVARCHAR (10)      NOT NULL,
    [Transfer-to Code]             NVARCHAR (10)      NOT NULL,
    [Shipment Date]                DATETIME           NOT NULL,
    [Receipt Date]                 DATETIME           NOT NULL,
    [Derived From Line No_]        INT                NOT NULL,
    [Shipping Agent Code]          NVARCHAR (10)      NOT NULL,
    [Shipping Agent Service Code]  NVARCHAR (10)      NOT NULL,
    [Appl_-to Item Entry]          INT                NOT NULL,
    [Shipping Time]                VARCHAR (32)       NOT NULL,
    [Direct Transfer]              TINYINT            NOT NULL,
    [Dimension Set ID]             INT                NOT NULL,
    [Item Category Code]           NVARCHAR (20)      NOT NULL,
    [Product Group Code]           NVARCHAR (10)      NOT NULL,
    [Completely Shipped]           TINYINT            NOT NULL,
    [Completely Received]          TINYINT            NOT NULL,
    [Outbound Whse_ Handling Time] VARCHAR (32)       NOT NULL,
    [Inbound Whse_ Handling Time]  VARCHAR (32)       NOT NULL,
    [Transfer-from Bin Code]       NVARCHAR (20)      NOT NULL,
    [Transfer-To Bin Code]         NVARCHAR (20)      NOT NULL,
    [Planning Flexibility]         INT                NOT NULL,
    [$systemId]                    NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]             DATETIME           NOT NULL,
    [$systemCreatedBy]             NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]            DATETIME           NOT NULL,
    [$systemModifiedBy]            NVARCHAR (36)      NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_TransferLine_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_TransferLine_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_TransferLine_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_TransferLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [Document No_] ASC, [Line No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

