CREATE TABLE [stg_bc].[Vendor] (
    [timestamp]                    VARBINARY (8)      NOT NULL,
    [No_]                          NVARCHAR (20)      NOT NULL,
    [Name]                         NVARCHAR (100)     NOT NULL,
    [Search Name]                  NVARCHAR (100)     NOT NULL,
    [Name 2]                       NVARCHAR (50)      NOT NULL,
    [Address]                      NVARCHAR (100)     NOT NULL,
    [Address 2]                    NVARCHAR (50)      NOT NULL,
    [City]                         NVARCHAR (30)      NOT NULL,
    [Contact]                      NVARCHAR (100)     NOT NULL,
    [Phone No_]                    NVARCHAR (30)      NOT NULL,
    [Telex No_]                    NVARCHAR (20)      NOT NULL,
    [Our Account No_]              NVARCHAR (20)      NOT NULL,
    [Territory Code]               NVARCHAR (10)      NOT NULL,
    [Global Dimension 1 Code]      NVARCHAR (20)      NOT NULL,
    [Global Dimension 2 Code]      NVARCHAR (20)      NOT NULL,
    [Budgeted Amount]              DECIMAL (38, 20)   NOT NULL,
    [Vendor Posting Group]         NVARCHAR (20)      NOT NULL,
    [Currency Code]                NVARCHAR (10)      NOT NULL,
    [Language Code]                NVARCHAR (10)      NOT NULL,
    [Statistics Group]             INT                NOT NULL,
    [Payment Terms Code]           NVARCHAR (10)      NOT NULL,
    [Fin_ Charge Terms Code]       NVARCHAR (10)      NOT NULL,
    [Purchaser Code]               NVARCHAR (20)      NOT NULL,
    [Shipment Method Code]         NVARCHAR (10)      NOT NULL,
    [Shipping Agent Code]          NVARCHAR (10)      NOT NULL,
    [Invoice Disc_ Code]           NVARCHAR (20)      NOT NULL,
    [Country_Region Code]          NVARCHAR (10)      NOT NULL,
    [Blocked]                      INT                NOT NULL,
    [Pay-to Vendor No_]            NVARCHAR (20)      NOT NULL,
    [Priority]                     INT                NOT NULL,
    [Payment Method Code]          NVARCHAR (10)      NOT NULL,
    [Last Modified Date Time]      DATETIME           NOT NULL,
    [Last Date Modified]           DATETIME           NOT NULL,
    [Application Method]           INT                NOT NULL,
    [Prices Including VAT]         TINYINT            NOT NULL,
    [Fax No_]                      NVARCHAR (30)      NOT NULL,
    [Telex Answer Back]            NVARCHAR (20)      NOT NULL,
    [VAT Registration No_]         NVARCHAR (20)      NOT NULL,
    [Gen_ Bus_ Posting Group]      NVARCHAR (20)      NOT NULL,
    [Picture]                      VARBINARY (MAX)    NULL,
    [GLN]                          NVARCHAR (13)      NOT NULL,
    [Post Code]                    NVARCHAR (20)      NOT NULL,
    [County]                       NVARCHAR (30)      NOT NULL,
    [EORI Number]                  NVARCHAR (40)      NOT NULL,
    [E-Mail]                       NVARCHAR (80)      NOT NULL,
    [Home Page]                    NVARCHAR (80)      NOT NULL,
    [No_ Series]                   NVARCHAR (20)      NOT NULL,
    [Tax Area Code]                NVARCHAR (20)      NOT NULL,
    [Tax Liable]                   TINYINT            NOT NULL,
    [VAT Bus_ Posting Group]       NVARCHAR (20)      NOT NULL,
    [Block Payment Tolerance]      TINYINT            NOT NULL,
    [IC Partner Code]              NVARCHAR (20)      NOT NULL,
    [Prepayment _]                 DECIMAL (38, 20)   NOT NULL,
    [Partner Type]                 INT                NOT NULL,
    [Image]                        NVARCHAR (36)      NOT NULL,
    [Privacy Blocked]              TINYINT            NOT NULL,
    [Disable Search by Name]       TINYINT            NOT NULL,
    [Creditor No_]                 NVARCHAR (20)      NOT NULL,
    [Preferred Bank Account Code]  NVARCHAR (20)      NOT NULL,
    [Cash Flow Payment Terms Code] NVARCHAR (10)      NOT NULL,
    [Primary Contact No_]          NVARCHAR (20)      NOT NULL,
    [Mobile Phone No_]             NVARCHAR (30)      NOT NULL,
    [Responsibility Center]        NVARCHAR (10)      NOT NULL,
    [Location Code]                NVARCHAR (10)      NOT NULL,
    [Lead Time Calculation]        VARCHAR (32)       NOT NULL,
    [Price Calculation Method]     INT                NOT NULL,
    [Base Calendar Code]           NVARCHAR (10)      NOT NULL,
    [Document Sending Profile]     NVARCHAR (20)      NOT NULL,
    [Validate EU Vat Reg_ No_]     TINYINT            NOT NULL,
    [Id]                           NVARCHAR (36)      NOT NULL,
    [Currency Id]                  NVARCHAR (36)      NOT NULL,
    [Payment Terms Id]             NVARCHAR (36)      NOT NULL,
    [Payment Method Id]            NVARCHAR (36)      NOT NULL,
    [Over-Receipt Code]            NVARCHAR (20)      NOT NULL,
    [Giro Acc_ No_]                NVARCHAR (8)       NOT NULL,
    [$systemId]                    NVARCHAR (36)      NOT NULL,
    [$systemCreatedAt]             DATETIME           NOT NULL,
    [$systemCreatedBy]             NVARCHAR (36)      NOT NULL,
    [$systemModifiedAt]            DATETIME           NOT NULL,
    [$systemModifiedBy]            NVARCHAR (36)      NOT NULL,
    [PipelineName]                 NVARCHAR (200)     CONSTRAINT [DF_Vendor_PipelineName] DEFAULT ('Default') NOT NULL,
    [PipelineRunId]                NVARCHAR (36)      CONSTRAINT [DF_Vendor_PipelineRunId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [PipelineTriggerTime]          DATETIMEOFFSET (0) CONSTRAINT [DF_Vendor_PipelineTriggerTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CompanyID]                    INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_Vendor] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

