CREATE TABLE [stg_bc].[WorkCenter] (
    [timestamp]                     VARBINARY (8)      NOT NULL,
    [No_]                           NVARCHAR (20)      NOT NULL,
    [Name]                          NVARCHAR (100)     NULL,
    [Search Name]                   NVARCHAR (100)     NULL,
    [Name 2]                        NVARCHAR (50)      NULL,
    [Address]                       NVARCHAR (100)     NULL,
    [Address 2]                     NVARCHAR (50)      NULL,
    [City]                          NVARCHAR (30)      NULL,
    [Post Code]                     NVARCHAR (20)      NULL,
    [Alternate Work Center]         NVARCHAR (20)      NULL,
    [Work Center Group Code]        NVARCHAR (10)      NULL,
    [Global Dimension 1 Code]       NVARCHAR (20)      NULL,
    [Global Dimension 2 Code]       NVARCHAR (20)      NULL,
    [Subcontractor No_]             NVARCHAR (20)      NULL,
    [Direct Unit Cost]              DECIMAL (38, 20)   NULL,
    [Indirect Cost _]               DECIMAL (38, 20)   NULL,
    [Unit Cost]                     DECIMAL (38, 20)   NULL,
    [Queue Time]                    DECIMAL (38, 20)   NULL,
    [Queue Time Unit of Meas_ Code] NVARCHAR (10)      NULL,
    [Last Date Modified]            DATETIME           NULL,
    [Unit of Measure Code]          NVARCHAR (10)      NULL,
    [Capacity]                      DECIMAL (38, 20)   NULL,
    [Efficiency]                    DECIMAL (38, 20)   NULL,
    [Maximum Efficiency]            DECIMAL (38, 20)   NULL,
    [Minimum Efficiency]            DECIMAL (38, 20)   NULL,
    [Calendar Rounding Precision]   DECIMAL (38, 20)   NULL,
    [Simulation Type]               INT                NULL,
    [Shop Calendar Code]            NVARCHAR (10)      NULL,
    [Blocked]                       TINYINT            NULL,
    [Unit Cost Calculation]         INT                NULL,
    [Specific Unit Cost]            TINYINT            NULL,
    [Consolidated Calendar]         TINYINT            NULL,
    [Flushing Method]               INT                NULL,
    [No_ Series]                    NVARCHAR (20)      NULL,
    [Overhead Rate]                 DECIMAL (38, 20)   NULL,
    [Gen_ Prod_ Posting Group]      NVARCHAR (20)      NULL,
    [County]                        NVARCHAR (30)      NULL,
    [Country_Region Code]           NVARCHAR (10)      NULL,
    [Location Code]                 NVARCHAR (10)      NULL,
    [Open Shop Floor Bin Code]      NVARCHAR (20)      NULL,
    [To-Production Bin Code]        NVARCHAR (20)      NULL,
    [From-Production Bin Code]      NVARCHAR (20)      NULL,
    [$systemId]                     NVARCHAR (36)      NULL,
    [$systemCreatedAt]              DATETIME           NULL,
    [$systemCreatedBy]              NVARCHAR (36)      NULL,
    [$systemModifiedAt]             DATETIME           NULL,
    [$systemModifiedBy]             NVARCHAR (36)      NULL,
    [PipelineName]                  NVARCHAR (200)     NULL,
    [PipelineRunId]                 NVARCHAR (36)      NULL,
    [PipelineTriggerTime]           DATETIMEOFFSET (0) NULL,
    [CompanyID]                     INT                NOT NULL,
    CONSTRAINT [PK_stg_bc_WorkCenter] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [No_] ASC) WITH (DATA_COMPRESSION = ROW)
);


GO

