CREATE TABLE [fct_v1].[ItemBudgetEntry] (
    [PostingDateKey]        INT            CONSTRAINT [DF_ItemBudgetEntry_v1_PostingDate] DEFAULT ((-1)) NOT NULL,
    [CompanyKey]            INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Company] DEFAULT ((-1)) NOT NULL,
    [BudgetVersionKey]      INT            CONSTRAINT [DF_ItemBudgetEntry_v1_BudgetVersion] DEFAULT ((-1)) NOT NULL,
    [ItemKey]               INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Item] DEFAULT ((-1)) NOT NULL,
    [CustomerKey]           INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Customer] DEFAULT ((-1)) NOT NULL,
    [DepartmentKey]         INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Department] DEFAULT ((-1)) NOT NULL,
    [ChainKey]              INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Chain] DEFAULT ((-1)) NOT NULL,
    [GeographyKey]          INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Geography] DEFAULT ((-1)) NOT NULL,
    [EmployeeKey]           INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Employee] DEFAULT ((-1)) NOT NULL,
    [LocationKey]           INT            CONSTRAINT [DF_ItemBudgetEntry_v1_Location] DEFAULT ((-1)) NOT NULL,
    [CurrencyCompanyKey]    INT            CONSTRAINT [DF_ItemBudgetEntry_v1_CurrencyCompany] DEFAULT ((-1)) NOT NULL,
    [M_Quantity]            DECIMAL (18, 6) NULL,
    [M_CostPrice]           DECIMAL (18, 6) NULL,
    [M_SalesPrice]          DECIMAL (18, 6) NULL,
    [M_CostAmount_LCY]      DECIMAL (18, 6) NULL,
    [M_SalesAmount_LCY]     DECIMAL (18, 6) NULL,
    [ItemBudgetCompanyID]   INT            NOT NULL,
    [NK_BudgetAnalysisArea] NVARCHAR (8)   NOT NULL,
    [NK_BudgetSourceType]   NVARCHAR (8)   NOT NULL,
    [NK_EntryNo]            INT            NOT NULL,
    [NK_PostingDate]        DATE           NOT NULL,
    [ADF_FactSource]        NVARCHAR (128) NOT NULL,
    [ADF_SourceModifiedAt]  DATETIME2 (7)  NULL,
    [ADF_LastTimestamp]     VARBINARY (8)  CONSTRAINT [DF_ItemBudgetEntry_v1_timestamp] DEFAULT (0x) NOT NULL,
    CONSTRAINT [PK_ItemBudgetEntry_v1] PRIMARY KEY CLUSTERED (
        [ItemBudgetCompanyID] ASC,
        [NK_BudgetAnalysisArea] ASC,
        [NK_BudgetSourceType] ASC,
        [NK_EntryNo] ASC,
        [NK_PostingDate] ASC,
        [ADF_FactSource] ASC
    )
);
