CREATE TABLE [fct_v1].[ProductionOrderStatistics] (
    [CreatedDateKey] INT CONSTRAINT [DF_ProductionOrderStatistics_CreatedDate] DEFAULT ((-1)) NOT NULL,
    [DueDateKey] INT CONSTRAINT [DF_ProductionOrderStatistics_DueDate] DEFAULT ((-1)) NOT NULL,
    [StartingDateKey] INT CONSTRAINT [DF_ProductionOrderStatistics_StartingDate] DEFAULT ((-1)) NOT NULL,
    [EndingDateKey] INT CONSTRAINT [DF_ProductionOrderStatistics_EndingDate] DEFAULT ((-1)) NOT NULL,
    [StartingTimeKey] INT CONSTRAINT [DF_ProductionOrderStatistics_StartingTime] DEFAULT ((-1)) NOT NULL,
    [EndingTimeKey] INT CONSTRAINT [DF_ProductionOrderStatistics_EndingTime] DEFAULT ((-1)) NOT NULL,
    [CompanyKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Company] DEFAULT ((-1)) NOT NULL,
    [ItemKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Item] DEFAULT ((-1)) NOT NULL,
    [ProductionOrderKey] INT CONSTRAINT [DF_ProductionOrderStatistics_ProductionOrder] DEFAULT ((-1)) NOT NULL,
    [LocationKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Location] DEFAULT ((-1)) NOT NULL,
    [AdHocKey] INT CONSTRAINT [DF_ProductionOrderStatistics_AdHoc] DEFAULT ((-1)) NOT NULL,
    [DepartmentKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Department] DEFAULT ((-1)) NOT NULL,
    [ChainKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Chain] DEFAULT ((-1)) NOT NULL,
    [CountryKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Country] DEFAULT ((-1)) NOT NULL,
    [SupplierKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Supplier] DEFAULT ((-1)) NOT NULL,
    [MarketingKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Marketing] DEFAULT ((-1)) NOT NULL,
    [EmployeeKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Employee] DEFAULT ((-1)) NOT NULL,
    [MaintainanceKey] INT CONSTRAINT [DF_ProductionOrderStatistics_Maintainance] DEFAULT ((-1)) NOT NULL,
    [M_PlannedQuantity] DECIMAL (18, 4) NULL,
    [M_FinishedQuantity] DECIMAL (18, 4) NULL,
    [M_RemainingQuantity] DECIMAL (18, 4) NULL,
    [M_ExpectedMaterialQuantity] DECIMAL (18, 4) NULL,
    [M_RemainingMaterialQuantity] DECIMAL (18, 4) NULL,
    [M_ExpectedMaterialCostLCY] DECIMAL (18, 4) NULL,
    [M_ExpectedDirectMaterialCostLCY] DECIMAL (18, 4) NULL,
    [M_ExpectedSetupTime] DECIMAL (18, 4) NULL,
    [M_ExpectedRunTime] DECIMAL (18, 4) NULL,
    [M_ExpectedCapacityNeed] DECIMAL (18, 4) NULL,
    [M_ActualCapacityQuantity] DECIMAL (18, 4) NULL,
    [M_ActualCapacityInvoicedQuantity] DECIMAL (18, 4) NULL,
    [M_ActualOutputQuantity] DECIMAL (18, 4) NULL,
    [M_ActualScrapQuantity] DECIMAL (18, 4) NULL,
    [M_ActualRunTime] DECIMAL (18, 4) NULL,
    [M_ActualStopTime] DECIMAL (18, 4) NULL,
    [M_ActualCostLCY] DECIMAL (18, 4) NULL,
    [M_ExpectedCostLCY] DECIMAL (18, 4) NULL,
    [M_ActualMaterialCostLCY] DECIMAL (18, 4) NULL,
    [M_ExpectedMaterialCostFromEntryLCY] DECIMAL (18, 4) NULL,
    [M_ActualCapacityCostLCY] DECIMAL (18, 4) NULL,
    [M_ExpectedCapacityCostLCY] DECIMAL (18, 4) NULL,
    [M_ActualPurchaseCostLCY] DECIMAL (18, 4) NULL,
    [M_ExpectedPurchaseCostLCY] DECIMAL (18, 4) NULL,
    [M_TotalVarianceLCY] DECIMAL (18, 4) NULL,
    [M_MaterialVarianceLCY] DECIMAL (18, 4) NULL,
    [M_CapacityVarianceLCY] DECIMAL (18, 4) NULL,
    [M_SubcontractVarianceLCY] DECIMAL (18, 4) NULL,
    [M_OverheadVarianceLCY] DECIMAL (18, 4) NULL,
    [CompanyID] INT NOT NULL,
    [NK_ProductionOrderNumber] NVARCHAR (20) NOT NULL,
    [NK_ProductionOrderLineNumber] INT NOT NULL,
    [ADF_FactSource] NVARCHAR (128) NOT NULL,
    [timestamp] VARBINARY (8) CONSTRAINT [DF_ProductionOrderStatistics_timestamp] DEFAULT (0x) NOT NULL,
    CONSTRAINT [PK_ProductionOrderStatistics] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [NK_ProductionOrderNumber] ASC, [NK_ProductionOrderLineNumber] ASC, [ADF_FactSource] ASC)
);
