CREATE TABLE [fct_v1].[ProductionOrderRoutingLine] (
    [StartingDateKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_StartingDate] DEFAULT ((-1)) NOT NULL,
    [EndingDateKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_EndingDate] DEFAULT ((-1)) NOT NULL,
    [StartingTimeKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_StartingTime] DEFAULT ((-1)) NOT NULL,
    [EndingTimeKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_EndingTime] DEFAULT ((-1)) NOT NULL,
    [CompanyKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_Company] DEFAULT ((-1)) NOT NULL,
    [ProductionOrderKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_ProductionOrder] DEFAULT ((-1)) NOT NULL,
    [RoutingKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_Routing] DEFAULT ((-1)) NOT NULL,
    [WorkCenterKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_WorkCenter] DEFAULT ((-1)) NOT NULL,
    [LocationKey] INT CONSTRAINT [DF_ProductionOrderRoutingLine_Location] DEFAULT ((-1)) NOT NULL,
    [RoutingLineTypeID] INT NULL,
    [RoutingLineStatusID] INT NULL,
    [FlushingMethodID] INT NULL,
    [M_SetupTime] DECIMAL (18, 4) NULL,
    [M_RunTime] DECIMAL (18, 4) NULL,
    [M_WaitTime] DECIMAL (18, 4) NULL,
    [M_MoveTime] DECIMAL (18, 4) NULL,
    [M_FixedScrapQuantity] DECIMAL (18, 4) NULL,
    [M_LotSize] DECIMAL (18, 4) NULL,
    [M_ScrapFactorPct] DECIMAL (18, 4) NULL,
    [M_MinimumProcessTime] DECIMAL (18, 4) NULL,
    [M_MaximumProcessTime] DECIMAL (18, 4) NULL,
    [M_ConcurrentCapacities] DECIMAL (18, 4) NULL,
    [M_SendAheadQuantity] DECIMAL (18, 4) NULL,
    [M_UnitCostPer] DECIMAL (18, 4) NULL,
    [M_DirectUnitCost] DECIMAL (18, 4) NULL,
    [M_IndirectUnitCost] DECIMAL (18, 4) NULL,
    [M_OverheadRate] DECIMAL (18, 4) NULL,
    [M_InputQuantity] DECIMAL (18, 4) NULL,
    [M_ExpectedOperationCostAmount] DECIMAL (18, 4) NULL,
    [M_ExpectedCapacityNeed] DECIMAL (18, 4) NULL,
    [M_ExpectedCapacityOverheadCost] DECIMAL (18, 4) NULL,
    [CompanyID] INT NOT NULL,
    [NK_ProductionOrderNumber] NVARCHAR (20) NOT NULL,
    [NK_ProductionOrderLineNumber] INT NOT NULL,
    [NK_RoutingNumber] NVARCHAR (20) NULL,
    [NK_RoutingReferenceNumber] INT NOT NULL,
    [NK_OperationNumber] NVARCHAR (20) NOT NULL,
    [BK_RoutingLineResourceNumber] NVARCHAR (20) NULL,
    [ADF_FactSource] NVARCHAR (128) NOT NULL,
    [timestamp] VARBINARY (8) CONSTRAINT [DF_ProductionOrderRoutingLine_timestamp] DEFAULT (0x) NOT NULL,
    CONSTRAINT [PK_ProductionOrderRoutingLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [NK_ProductionOrderNumber] ASC, [NK_ProductionOrderLineNumber] ASC, [NK_RoutingReferenceNumber] ASC, [NK_OperationNumber] ASC, [ADF_FactSource] ASC)
);
