CREATE TABLE [fct_v1].[ProductionOrderLine] (
    [CreatedDateKey] INT CONSTRAINT [DF_ProductionOrderLine_CreatedDate] DEFAULT ((-1)) NOT NULL,
    [DueDateKey] INT CONSTRAINT [DF_ProductionOrderLine_DueDate] DEFAULT ((-1)) NOT NULL,
    [StartingDateKey] INT CONSTRAINT [DF_ProductionOrderLine_StartingDate] DEFAULT ((-1)) NOT NULL,
    [EndingDateKey] INT CONSTRAINT [DF_ProductionOrderLine_EndingDate] DEFAULT ((-1)) NOT NULL,
    [StartingTimeKey] INT CONSTRAINT [DF_ProductionOrderLine_StartingTime] DEFAULT ((-1)) NOT NULL,
    [EndingTimeKey] INT CONSTRAINT [DF_ProductionOrderLine_EndingTime] DEFAULT ((-1)) NOT NULL,
    [CompanyKey] INT CONSTRAINT [DF_ProductionOrderLine_Company] DEFAULT ((-1)) NOT NULL,
    [ItemKey] INT CONSTRAINT [DF_ProductionOrderLine_Item] DEFAULT ((-1)) NOT NULL,
    [ProductionOrderKey] INT CONSTRAINT [DF_ProductionOrderLine_ProductionOrder] DEFAULT ((-1)) NOT NULL,
    [LocationKey] INT CONSTRAINT [DF_ProductionOrderLine_Location] DEFAULT ((-1)) NOT NULL,
    [AdHocKey] INT CONSTRAINT [DF_ProductionOrderLine_AdHoc] DEFAULT ((-1)) NOT NULL,
    [DepartmentKey] INT CONSTRAINT [DF_ProductionOrderLine_Department] DEFAULT ((-1)) NOT NULL,
    [ChainKey] INT CONSTRAINT [DF_ProductionOrderLine_Chain] DEFAULT ((-1)) NOT NULL,
    [CountryKey] INT CONSTRAINT [DF_ProductionOrderLine_Country] DEFAULT ((-1)) NOT NULL,
    [SupplierKey] INT CONSTRAINT [DF_ProductionOrderLine_Supplier] DEFAULT ((-1)) NOT NULL,
    [MarketingKey] INT CONSTRAINT [DF_ProductionOrderLine_Marketing] DEFAULT ((-1)) NOT NULL,
    [EmployeeKey] INT CONSTRAINT [DF_ProductionOrderLine_Employee] DEFAULT ((-1)) NOT NULL,
    [MaintainanceKey] INT CONSTRAINT [DF_ProductionOrderLine_Maintainance] DEFAULT ((-1)) NOT NULL,
    [M_Quantity] DECIMAL (18, 4) NULL,
    [M_QuantityFinished] DECIMAL (18, 4) NULL,
    [M_QuantityRemaining] DECIMAL (18, 4) NULL,
    [CompanyID] INT NOT NULL,
    [NK_ProductionOrderNumber] NVARCHAR (20) NOT NULL,
    [NK_ProductionOrderLineNumber] INT NOT NULL,
    [ADF_FactSource] NVARCHAR (128) NOT NULL,
    [timestamp] VARBINARY (8) CONSTRAINT [DF_ProductionOrderLine_timestamp] DEFAULT (0x) NOT NULL,
    [ItemProductionQuantity] INT CONSTRAINT [DF__Productio__ItemP__19A271E9] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ProductionOrderLine] PRIMARY KEY CLUSTERED ([CompanyID] ASC, [NK_ProductionOrderNumber] ASC, [NK_ProductionOrderLineNumber] ASC, [ADF_FactSource] ASC)
);
