CREATE TABLE [fct_v1].[Purchase] (
    [PostingDateKey] INT CONSTRAINT [DF_Purchase_PostingDate] DEFAULT ((-1)) NOT NULL,
    [OrderDateKey] INT CONSTRAINT [DF_Purchase_OrderDate] DEFAULT ((-1)) NOT NULL,
    [ExpectedReceiptDateKey] INT CONSTRAINT [DF_Purchase_ExpectedReceiptDate] DEFAULT ((-1)) NOT NULL,
    [DocumentDateKey] INT CONSTRAINT [DF_Purchase_DocumentDate] DEFAULT ((-1)) NOT NULL,
    [CompanyKey] INT CONSTRAINT [DF_Purchase_Company] DEFAULT ((-1)) NOT NULL,
    [VendorKey] INT CONSTRAINT [DF_Purchase_Vendor] DEFAULT ((-1)) NOT NULL,
    [ItemKey] INT CONSTRAINT [DF_Purchase_Item] DEFAULT ((-1)) NOT NULL,
    [PurchaseDocumentKey] INT CONSTRAINT [DF_Purchase_PurchaseDocument] DEFAULT ((-1)) NOT NULL,
    [LocationKey] INT CONSTRAINT [DF_Purchase_Location] DEFAULT ((-1)) NOT NULL,
    [DocumentCurrencyKey] INT CONSTRAINT [DF_Purchase_DocumentCurrecy] DEFAULT ((-1)) NOT NULL,
    [CompanyCurrencyKey] INT CONSTRAINT [DF_Purchase_CompanyCurrecy] DEFAULT ((-1)) NOT NULL,
    [AdHocKey] INT CONSTRAINT [DF_Purchase_AdHoc] DEFAULT ((-1)) NOT NULL,
    [DepartmentKey] INT CONSTRAINT [DF_Purchase_Department] DEFAULT ((-1)) NOT NULL,
    [ChainKey] INT CONSTRAINT [DF_Purchase_Chain] DEFAULT ((-1)) NOT NULL,
    [CountryKey] INT CONSTRAINT [DF_Purchase_Country] DEFAULT ((-1)) NOT NULL,
    [SupplierKey] INT CONSTRAINT [DF_Purchase_Supplier] DEFAULT ((-1)) NOT NULL,
    [MarketingKey] INT CONSTRAINT [DF_Purchase_Marketing] DEFAULT ((-1)) NOT NULL,
    [EmployeeKey] INT CONSTRAINT [DF_Purchase_Employee] DEFAULT ((-1)) NOT NULL,
    [MaintainanceKey] INT CONSTRAINT [DF_Purchase_Maintainance] DEFAULT ((-1)) NOT NULL,
    [M_Quantity] DECIMAL (18, 4) NULL,
    [M_OutstandingQuantity] DECIMAL (18, 4) NULL,
    [M_QtyToReceive] DECIMAL (18, 4) NULL,
    [M_ReceivedNotInvoicedQuantity] DECIMAL (18, 4) NULL,
    [M_UnitCost] DECIMAL (18, 4) NULL,
    [M_DirectUnitCost] DECIMAL (18, 4) NULL,
    [M_UnitCost_LCY] DECIMAL (18, 4) NULL,
    [M_UnitPrice_LCY] DECIMAL (18, 4) NULL,
    [M_OutstandingAmount] DECIMAL (18, 4) NULL,
    [M_OutstandingAmount_LCY] DECIMAL (18, 4) NULL,
    [M_ReceivedNotInvoicedAmount] DECIMAL (18, 4) NULL,
    [LineTypeNumber] INT NULL,
    [CompanyID] INT NOT NULL,
    [NK_PostingDate] DATETIME NOT NULL,
    [NK_PurchaseOrderNumber] NVARCHAR (20) NOT NULL,
    [NK_PurchaseOrderLineNumber] INT NOT NULL,
    [ADF_FactSource] NVARCHAR (128) NOT NULL,
    [timestamp] VARBINARY (8) CONSTRAINT [DF_Purchase_timestamp] DEFAULT (0x) NOT NULL,
    CONSTRAINT [PK_Purchase] PRIMARY KEY CLUSTERED ([NK_PostingDate] ASC, [CompanyID] ASC, [NK_PurchaseOrderNumber] ASC, [NK_PurchaseOrderLineNumber] ASC, [ADF_FactSource] ASC)
);
