CREATE TABLE [fct_v1].[Transfer] (
    [PostingDateKey] INT CONSTRAINT [DF_Transfer_v1_PostingDate] DEFAULT ((-1)) NOT NULL,
    [ShipmentDateKey] INT CONSTRAINT [DF_Transfer_v1_ShipmentDate] DEFAULT ((-1)) NOT NULL,
    [ExpectedReceiptDateKey] INT CONSTRAINT [DF_Transfer_v1_ExpectedReceiptDate] DEFAULT ((-1)) NOT NULL,
    [CompanyKey] INT CONSTRAINT [DF_Transfer_v1_Company] DEFAULT ((-1)) NOT NULL,
    [ItemKey] INT CONSTRAINT [DF_Transfer_v1_Item] DEFAULT ((-1)) NOT NULL,
    [TransferDocumentKey] INT CONSTRAINT [DF_Transfer_v1_TransferDocument] DEFAULT ((-1)) NOT NULL,
    [LocationFromKey] INT CONSTRAINT [DF_Transfer_v1_FromLocation] DEFAULT ((-1)) NOT NULL,
    [LocationToKey] INT CONSTRAINT [DF_Transfer_v1_ToLocation] DEFAULT ((-1)) NOT NULL,
    [LocationTransitKey] INT CONSTRAINT [DF_Transfer_v1_TransitLocation] DEFAULT ((-1)) NOT NULL,
    [AdHocKey] INT CONSTRAINT [DF_Transfer_v1_AdHoc] DEFAULT ((-1)) NOT NULL,
    [DepartmentKey] INT CONSTRAINT [DF_Transfer_v1_Department] DEFAULT ((-1)) NOT NULL,
    [ChainKey] INT CONSTRAINT [DF_Transfer_v1_Chain] DEFAULT ((-1)) NOT NULL,
    [CountryKey] INT CONSTRAINT [DF_Transfer_v1_Country] DEFAULT ((-1)) NOT NULL,
    [SupplierKey] INT CONSTRAINT [DF_Transfer_v1_Supplier] DEFAULT ((-1)) NOT NULL,
    [MarketingKey] INT CONSTRAINT [DF_Transfer_v1_Marketing] DEFAULT ((-1)) NOT NULL,
    [EmployeeKey] INT CONSTRAINT [DF_Transfer_v1_Employee] DEFAULT ((-1)) NOT NULL,
    [MaintainanceKey] INT CONSTRAINT [DF_Transfer_v1_Maintainance] DEFAULT ((-1)) NOT NULL,
    [M_Quantity] DECIMAL (18, 4) NULL,
    [M_OutstandingQuantity] DECIMAL (18, 4) NULL,
    [M_QtyToReceive] DECIMAL (18, 4) NULL,
    [CompanyID] INT NOT NULL,
    [NK_PostingDate] DATETIME NOT NULL,
    [NK_TransferDocumentNumber] NVARCHAR (20) NOT NULL,
    [NK_TransferLineNumber] INT NOT NULL,
    [ADF_FactSource] NVARCHAR (128) NOT NULL,
    [ADF_SourceModifiedAt] DATETIME2 (7) NULL,
    [ADF_LastTimestamp] VARBINARY (8) CONSTRAINT [DF_Transfer_v1_LastTimestamp] DEFAULT (0x) NOT NULL,
    CONSTRAINT [PK_Transfer_v1] PRIMARY KEY CLUSTERED (
        [NK_PostingDate] ASC,
        [CompanyID] ASC,
        [NK_TransferDocumentNumber] ASC,
        [NK_TransferLineNumber] ASC,
        [ADF_FactSource] ASC
    )
);
