CREATE TABLE [stg_bc_api].[CapacityLedgerEntry] (
    [CompanyId]              INT                NOT NULL,
    [entryNo]                INT                NOT NULL,
    [no]                     NVARCHAR (20)      NOT NULL,
    [type]                   NVARCHAR (50)      NULL,
    [typeInt]                INT                NULL,
    [postingDate]            DATE               NULL,
    [documentNo]             NVARCHAR (50)      NULL,
    [documentDate]           DATE               NULL,
    [externalDocumentNo]     NVARCHAR (50)      NULL,
    [startingTime]           TIME (0)           NULL,
    [endingTime]             TIME (0)           NULL,
    [description]            NVARCHAR (100)     NULL,
    [operationNo]            NVARCHAR (20)      NULL,
    [workCenterNo]           NVARCHAR (20)      NULL,
    [routingNo]              NVARCHAR (20)      NULL,
    [routingReferenceNo]     INT                NULL,
    [itemNo]                 NVARCHAR (20)      NULL,
    [variantCode]            NVARCHAR (20)      NULL,
    [unitOfMeasureCode]      NVARCHAR (20)      NULL,
    [qtyPerUnitOfMeasure]    DECIMAL (38, 20)   NULL,
    [quantity]               DECIMAL (38, 20)   NULL,
    [setupTime]              DECIMAL (38, 20)   NULL,
    [runTime]                DECIMAL (38, 20)   NULL,
    [stopTime]               DECIMAL (38, 20)   NULL,
    [invoicedQuantity]       DECIMAL (38, 20)   NULL,
    [outputQuantity]         DECIMAL (38, 20)   NULL,
    [scrapQuantity]          DECIMAL (38, 20)   NULL,
    [concurrentCapacity]     DECIMAL (38, 20)   NULL,
    [capUnitOfMeasureCode]   NVARCHAR (20)      NULL,
    [qtyPerCapUnitOfMeasure] DECIMAL (38, 20)   NULL,
    [workCenterGroupCode]    NVARCHAR (20)      NULL,
    [workShiftCode]          NVARCHAR (20)      NULL,
    [lastOutputLine]         BIT                NULL,
    [completelyInvoiced]     BIT                NULL,
    [subcontracting]         BIT                NULL,
    [stopCode]               NVARCHAR (20)      NULL,
    [scrapCode]              NVARCHAR (20)      NULL,
    [orderType]              NVARCHAR (50)      NULL,
    [orderTypeInt]           INT                NULL,
    [orderNo]                NVARCHAR (20)      NULL,
    [orderLineNo]            INT                NULL,
    [globalDimension1Code]   NVARCHAR (20)      NULL,
    [globalDimension2Code]   NVARCHAR (20)      NULL,
    [dimensionSetId]         INT                NULL,
    [shortcutDim3Code]       NVARCHAR (20)      NULL,
    [shortcutDim4Code]       NVARCHAR (20)      NULL,
    [shortcutDim5Code]       NVARCHAR (20)      NULL,
    [shortcutDim6Code]       NVARCHAR (20)      NULL,
    [shortcutDim7Code]       NVARCHAR (20)      NULL,
    [shortcutDim8Code]       NVARCHAR (20)      NULL,
    [directCost]             DECIMAL (38, 20)   NULL,
    [overheadCost]           DECIMAL (38, 20)   NULL,
    [directCostACY]          DECIMAL (38, 20)   NULL,
    [overheadCostACY]        DECIMAL (38, 20)   NULL,
    [systemId]               UNIQUEIDENTIFIER   NULL,
    [systemCreatedAt]        DATETIMEOFFSET (7) NULL,
    [systemCreatedBy]        UNIQUEIDENTIFIER   NULL,
    [systemModifiedAt]       DATETIMEOFFSET (7) NULL,
    [systemModifiedBy]       UNIQUEIDENTIFIER   NULL,
    [PipelineName]           NVARCHAR (200)     NULL,
    [PipelineRunId]          NVARCHAR (100)     NULL,
    [PipelineTriggerTime]    DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_CapacityLedgerEntry] PRIMARY KEY CLUSTERED ([CompanyId] ASC, [entryNo] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_CapacityLedgerEntry_Company_PostingDate]
    ON [stg_bc_api].[CapacityLedgerEntry]([CompanyId] ASC, [postingDate] ASC);


GO

