CREATE TABLE [stg_bc_api].[CompanyInformation] (
    [CompanyId]                   INT                NOT NULL,
    [primaryKey]                  NVARCHAR (10)      NOT NULL,
    [name]                        NVARCHAR (100)     NULL,
    [name2]                       NVARCHAR (100)     NULL,
    [contactPerson]               NVARCHAR (100)     NULL,
    [phoneNo]                     NVARCHAR (30)      NULL,
    [phoneNo2]                    NVARCHAR (30)      NULL,
    [faxNo]                       NVARCHAR (30)      NULL,
    [email]                       NVARCHAR (80)      NULL,
    [homePage]                    NVARCHAR (250)     NULL,
    [address]                     NVARCHAR (100)     NULL,
    [address2]                    NVARCHAR (50)      NULL,
    [city]                        NVARCHAR (30)      NULL,
    [postCode]                    NVARCHAR (20)      NULL,
    [county]                      NVARCHAR (30)      NULL,
    [countryRegionCode]           NVARCHAR (10)      NULL,
    [shipToName]                  NVARCHAR (100)     NULL,
    [shipToName2]                 NVARCHAR (100)     NULL,
    [shipToAddress]               NVARCHAR (100)     NULL,
    [shipToAddress2]              NVARCHAR (50)      NULL,
    [shipToCity]                  NVARCHAR (30)      NULL,
    [shipToPostCode]              NVARCHAR (20)      NULL,
    [shipToCounty]                NVARCHAR (30)      NULL,
    [shipToCountryRegionCode]     NVARCHAR (10)      NULL,
    [bankName]                    NVARCHAR (100)     NULL,
    [bankBranchNo]                NVARCHAR (20)      NULL,
    [bankAccountNo]               NVARCHAR (30)      NULL,
    [paymentRoutingNo]            NVARCHAR (20)      NULL,
    [giroNo]                      NVARCHAR (20)      NULL,
    [iban]                        NVARCHAR (50)      NULL,
    [swiftCode]                   NVARCHAR (20)      NULL,
    [vatRegistrationNo]           NVARCHAR (20)      NULL,
    [registrationNo]              NVARCHAR (20)      NULL,
    [eoriNumber]                  NVARCHAR (20)      NULL,
    [gln]                         NVARCHAR (13)      NULL,
    [useGLNInElectronicDocument]  BIT                NULL,
    [allowBlankPaymentInfo]       BIT                NULL,
    [telexNo]                     NVARCHAR (20)      NULL,
    [telexAnswerBack]             NVARCHAR (20)      NULL,
    [customsPermitNo]             NVARCHAR (20)      NULL,
    [customsPermitDate]           DATE               NULL,
    [industrialClassification]    NVARCHAR (20)      NULL,
    [alternativeLanguageCode]     NVARCHAR (10)      NULL,
    [responsibilityCenter]        NVARCHAR (20)      NULL,
    [checkAvailPeriodCalc]        NVARCHAR (32)      NULL,
    [checkAvailTimeBucket]        NVARCHAR (50)      NULL,
    [baseCalendarCode]            NVARCHAR (10)      NULL,
    [calConvergenceTimeFrame]     NVARCHAR (32)      NULL,
    [systemIndicator]             NVARCHAR (50)      NULL,
    [customSystemIndicatorText]   NVARCHAR (250)     NULL,
    [systemIndicatorStyle]        NVARCHAR (50)      NULL,
    [pictureLastModifiedDateTime] DATETIMEOFFSET (7) NULL,
    [lastModifiedDateTimeTbl]     DATETIMEOFFSET (7) NULL,
    [createdDateTime]             DATETIMEOFFSET (7) NULL,
    [demoCompany]                 BIT                NULL,
    [locationCode]                NVARCHAR (10)      NULL,
    [systemId]                    UNIQUEIDENTIFIER   NULL,
    [systemCreatedAt]             DATETIMEOFFSET (7) NULL,
    [systemCreatedBy]             UNIQUEIDENTIFIER   NULL,
    [systemModifiedAt]            DATETIMEOFFSET (7) NULL,
    [systemModifiedBy]            UNIQUEIDENTIFIER   NULL,
    [PipelineName]                NVARCHAR (200)     NULL,
    [PipelineRunId]               NVARCHAR (100)     NULL,
    [PipelineTriggerTime]         DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_CompanyInformation] PRIMARY KEY CLUSTERED ([CompanyId] ASC, [primaryKey] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_CompanyInformation_Company_LastModified]
    ON [stg_bc_api].[CompanyInformation]([CompanyId] ASC, [lastModifiedDateTimeTbl] ASC);


GO

