CREATE TABLE [stg_bc_api].[Employee] (
    [CompanyId]             INT                NOT NULL,
    [no]                    NVARCHAR (20)      NOT NULL,
    [firstName]             NVARCHAR (50)      NULL,
    [middleName]            NVARCHAR (50)      NULL,
    [lastName]              NVARCHAR (50)      NULL,
    [initials]              NVARCHAR (20)      NULL,
    [jobTitle]              NVARCHAR (100)     NULL,
    [searchName]            NVARCHAR (100)     NULL,
    [title]                 NVARCHAR (50)      NULL,
    [address]               NVARCHAR (100)     NULL,
    [address2]              NVARCHAR (50)      NULL,
    [city]                  NVARCHAR (30)      NULL,
    [postCode]              NVARCHAR (20)      NULL,
    [county]                NVARCHAR (30)      NULL,
    [countryRegionCode]     NVARCHAR (10)      NULL,
    [phoneNo]               NVARCHAR (30)      NULL,
    [mobilePhoneNo]         NVARCHAR (30)      NULL,
    [faxNo]                 NVARCHAR (30)      NULL,
    [eMail]                 NVARCHAR (80)      NULL,
    [companyEmail]          NVARCHAR (80)      NULL,
    [extension]             NVARCHAR (30)      NULL,
    [pager]                 NVARCHAR (30)      NULL,
    [jobStatus]             NVARCHAR (50)      NULL,
    [statusInt]             INT                NULL,
    [managerNo]             NVARCHAR (20)      NULL,
    [emplymtContractCode]   NVARCHAR (20)      NULL,
    [employmentDate]        DATE               NULL,
    [inactiveDate]          DATE               NULL,
    [causeOfInactivityCode] NVARCHAR (20)      NULL,
    [terminationDate]       DATE               NULL,
    [groundsForTermCode]    NVARCHAR (20)      NULL,
    [birthDate]             DATE               NULL,
    [socialSecurityNo]      NVARCHAR (30)      NULL,
    [gender]                NVARCHAR (50)      NULL,
    [genderInt]             INT                NULL,
    [unionCode]             NVARCHAR (20)      NULL,
    [unionMembershipNo]     NVARCHAR (30)      NULL,
    [statisticsGroupCode]   NVARCHAR (20)      NULL,
    [privayBlocked]         BIT                NULL,
    [employeePostingGroup]  NVARCHAR (20)      NULL,
    [applicationMethod]     NVARCHAR (50)      NULL,
    [bankBranchNo]          NVARCHAR (20)      NULL,
    [bankAccountNo]         NVARCHAR (30)      NULL,
    [iban]                  NVARCHAR (50)      NULL,
    [swiftCode]             NVARCHAR (20)      NULL,
    [balance]               DECIMAL (38, 20)   NULL,
    [globalDimension1Code]  NVARCHAR (20)      NULL,
    [globalDimension2Code]  NVARCHAR (20)      NULL,
    [costCenterCode]        NVARCHAR (20)      NULL,
    [costObjectCode]        NVARCHAR (20)      NULL,
    [resourceNo]            NVARCHAR (20)      NULL,
    [salesPurchCode]        NVARCHAR (20)      NULL,
    [lastDateModified]      DATE               NULL,
    [lastModifiedDateTime]  DATETIMEOFFSET (7) NULL,
    [systemId]              UNIQUEIDENTIFIER   NULL,
    [systemCreatedAt]       DATETIMEOFFSET (7) NULL,
    [systemCreatedBy]       UNIQUEIDENTIFIER   NULL,
    [systemModifiedAt]      DATETIMEOFFSET (7) NULL,
    [systemModifiedBy]      UNIQUEIDENTIFIER   NULL,
    [PipelineName]          NVARCHAR (200)     NULL,
    [PipelineRunId]         NVARCHAR (100)     NULL,
    [PipelineTriggerTime]   DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([CompanyId] ASC, [no] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_Employee_Company_LastModified]
    ON [stg_bc_api].[Employee]([CompanyId] ASC, [lastModifiedDateTime] ASC);


GO

