CREATE TABLE [stg_bc_api].[GLEntry] (
    [CompanyId]                INT                NOT NULL,
    [entryNo]                  INT                NOT NULL,
    [glAccountNo]              NVARCHAR (20)      NULL,
    [postingDate]              DATE               NULL,
    [documentType]             NVARCHAR (30)      NULL,
    [documentTypeInt]          INT                NULL,
    [documentNo]               NVARCHAR (50)      NULL,
    [description]              NVARCHAR (250)     NULL,
    [balAccountNo]             NVARCHAR (20)      NULL,
    [amount]                   DECIMAL (38, 18)   NULL,
    [globalDimension1Code]     NVARCHAR (20)      NULL,
    [globalDimension2Code]     NVARCHAR (20)      NULL,
    [userId]                   NVARCHAR (50)      NULL,
    [sourceCode]               NVARCHAR (20)      NULL,
    [systemCreatedEntry]       BIT                NULL,
    [priorYearEntry]           BIT                NULL,
    [jobNo]                    NVARCHAR (20)      NULL,
    [quantity]                 DECIMAL (38, 18)   NULL,
    [vatAmount]                DECIMAL (38, 18)   NULL,
    [businessUnitCode]         NVARCHAR (20)      NULL,
    [journalBatchName]         NVARCHAR (50)      NULL,
    [reasonCode]               NVARCHAR (20)      NULL,
    [genPostingType]           NVARCHAR (20)      NULL,
    [genPostingTypeInt]        INT                NULL,
    [genBusPostingGroup]       NVARCHAR (20)      NULL,
    [genProdPostingGroup]      NVARCHAR (20)      NULL,
    [balAccountType]           NVARCHAR (20)      NULL,
    [balAccountTypeInt]        INT                NULL,
    [transactionNo]            INT                NULL,
    [debitAmount]              DECIMAL (38, 18)   NULL,
    [creditAmount]             DECIMAL (38, 18)   NULL,
    [documentDate]             DATE               NULL,
    [externalDocumentNo]       NVARCHAR (50)      NULL,
    [sourceType]               NVARCHAR (20)      NULL,
    [sourceTypeInt]            INT                NULL,
    [sourceNo]                 NVARCHAR (50)      NULL,
    [noSeries]                 NVARCHAR (20)      NULL,
    [taxAreaCode]              NVARCHAR (20)      NULL,
    [taxLiable]                BIT                NULL,
    [taxGroupCode]             NVARCHAR (20)      NULL,
    [useTax]                   BIT                NULL,
    [vatBusPostingGroup]       NVARCHAR (20)      NULL,
    [vatProdPostingGroup]      NVARCHAR (20)      NULL,
    [additionalCurrencyAmount] DECIMAL (38, 18)   NULL,
    [addCurrencyDebitAmount]   DECIMAL (38, 18)   NULL,
    [addCurrencyCreditAmount]  DECIMAL (38, 18)   NULL,
    [icPartnerCode]            NVARCHAR (20)      NULL,
    [reversed]                 BIT                NULL,
    [reversedByEntryNo]        INT                NULL,
    [reversedEntryNo]          INT                NULL,
    [glAccountName]            NVARCHAR (100)     NULL,
    [dimensionSetId]           INT                NULL,
    [shortcutDim3Code]         NVARCHAR (20)      NULL,
    [shortcutDim4Code]         NVARCHAR (20)      NULL,
    [shortcutDim5Code]         NVARCHAR (20)      NULL,
    [shortcutDim6Code]         NVARCHAR (20)      NULL,
    [shortcutDim7Code]         NVARCHAR (20)      NULL,
    [shortcutDim8Code]         NVARCHAR (20)      NULL,
    [accountId]                UNIQUEIDENTIFIER   NULL,
    [systemId]                 UNIQUEIDENTIFIER   NULL,
    [systemCreatedAt]          DATETIMEOFFSET (7) NULL,
    [systemCreatedBy]          UNIQUEIDENTIFIER   NULL,
    [systemModifiedAt]         DATETIMEOFFSET (7) NULL,
    [systemModifiedBy]         UNIQUEIDENTIFIER   NULL,
    [lastModifiedDateTime]     DATETIMEOFFSET (7) NULL,
    [PipelineName]             NVARCHAR (128)     NULL,
    [PipelineRunId]            NVARCHAR (64)      NULL,
    [PipelineTriggerTime]      DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_GLEntry] PRIMARY KEY CLUSTERED ([CompanyId] ASC, [entryNo] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_GLEntry_Company_LastModified]
    ON [stg_bc_api].[GLEntry]([CompanyId] ASC, [lastModifiedDateTime] ASC)
    INCLUDE([entryNo]);


GO

