CREATE TABLE [stg_bc_api].[Item] (
    [CompanyId]                   INT                NOT NULL,
    [number]                      NVARCHAR (20)      NOT NULL,
    [systemId]                    UNIQUEIDENTIFIER   NULL,
    [number2]                     NVARCHAR (20)      NULL,
    [legacyId]                    UNIQUEIDENTIFIER   NULL,
    [description]                 NVARCHAR (100)     NULL,
    [description2]                NVARCHAR (50)      NULL,
    [searchDescription]           NVARCHAR (100)     NULL,
    [shelfNo]                     NVARCHAR (10)      NULL,
    [commonItemNo]                NVARCHAR (20)      NULL,
    [type]                        NVARCHAR (30)      NULL,
    [typeInt]                     INT                NULL,
    [itemCategoryCode]            NVARCHAR (20)      NULL,
    [itemCategoryId]              UNIQUEIDENTIFIER   NULL,
    [manufacturerCode]            NVARCHAR (10)      NULL,
    [serviceItemGroup]            NVARCHAR (10)      NULL,
    [inventoryPostingGroup]       NVARCHAR (20)      NULL,
    [genProdPostingGroup]         NVARCHAR (20)      NULL,
    [vatProdPostingGroup]         NVARCHAR (20)      NULL,
    [vatBusPostingGrpPrice]       NVARCHAR (20)      NULL,
    [taxGroupCode]                NVARCHAR (20)      NULL,
    [taxGroupId]                  UNIQUEIDENTIFIER   NULL,
    [dutyCode]                    NVARCHAR (10)      NULL,
    [dutyDuePct]                  DECIMAL (38, 20)   NULL,
    [dutyUnitConversion]          DECIMAL (38, 20)   NULL,
    [tariffNo]                    NVARCHAR (20)      NULL,
    [countryRegionPurchasedCode]  NVARCHAR (10)      NULL,
    [countryRegionOfOriginCode]   NVARCHAR (10)      NULL,
    [baseUnitOfMeasure]           NVARCHAR (10)      NULL,
    [unitOfMeasureId]             UNIQUEIDENTIFIER   NULL,
    [salesUnitOfMeasure]          NVARCHAR (10)      NULL,
    [purchUnitOfMeasure]          NVARCHAR (10)      NULL,
    [putAwayUnitOfMeasureCode]    NVARCHAR (10)      NULL,
    [priceUnitConversion]         INT                NULL,
    [unitPrice]                   DECIMAL (38, 20)   NULL,
    [unitCost]                    DECIMAL (38, 20)   NULL,
    [standardCost]                DECIMAL (38, 20)   NULL,
    [lastDirectCost]              DECIMAL (38, 20)   NULL,
    [unitListPrice]               DECIMAL (38, 20)   NULL,
    [priceIncludesVAT]            BIT                NULL,
    [priceProfitCalculation]      NVARCHAR (50)      NULL,
    [priceProfitCalculationInt]   INT                NULL,
    [profitPct]                   DECIMAL (38, 20)   NULL,
    [costingMethod]               NVARCHAR (30)      NULL,
    [costingMethodInt]            INT                NULL,
    [indirectCostPct]             DECIMAL (38, 20)   NULL,
    [overheadRate]                DECIMAL (38, 20)   NULL,
    [costIsAdjusted]              BIT                NULL,
    [allowOnlineAdjustment]       BIT                NULL,
    [costIsPostedToGL]            BIT                NULL,
    [vendorNo]                    NVARCHAR (20)      NULL,
    [vendorItemNo]                NVARCHAR (50)      NULL,
    [leadTimeCalculation]         NVARCHAR (30)      NULL,
    [purchasingCode]              NVARCHAR (10)      NULL,
    [gtin]                        NVARCHAR (14)      NULL,
    [identifierCode]              NVARCHAR (20)      NULL,
    [alternativeItemNo]           NVARCHAR (20)      NULL,
    [itemDiscGroup]               NVARCHAR (20)      NULL,
    [allowInvoiceDisc]            BIT                NULL,
    [statisticsGroup]             INT                NULL,
    [commissionGroup]             INT                NULL,
    [globalDimension1Code]        NVARCHAR (20)      NULL,
    [globalDimension2Code]        NVARCHAR (20)      NULL,
    [blockReason]                 NVARCHAR (250)     NULL,
    [noSeries]                    NVARCHAR (20)      NULL,
    [defaultDeferralTemplateCode] NVARCHAR (10)      NULL,
    [applicationWkshUserId]       NVARCHAR (128)     NULL,
    [blocked]                     BIT                NULL,
    [salesBlocked]                BIT                NULL,
    [purchasingBlocked]           BIT                NULL,
    [stockoutWarning]             NVARCHAR (20)      NULL,
    [stockoutWarningInt]          INT                NULL,
    [preventNegativeInventory]    NVARCHAR (20)      NULL,
    [preventNegativeInventoryInt] INT                NULL,
    [createdFromNonstockItem]     BIT                NULL,
    [automaticExtTexts]           BIT                NULL,
    [useCrossDocking]             BIT                NULL,
    [critical]                    BIT                NULL,
    [inventoryValueZero]          BIT                NULL,
    [grossWeight]                 DECIMAL (38, 20)   NULL,
    [netWeight]                   DECIMAL (38, 20)   NULL,
    [unitsPerParcel]              DECIMAL (38, 20)   NULL,
    [unitVolume]                  DECIMAL (38, 20)   NULL,
    [durability]                  NVARCHAR (10)      NULL,
    [freightType]                 NVARCHAR (10)      NULL,
    [warehouseClassCode]          NVARCHAR (10)      NULL,
    [specialEquipmentCode]        NVARCHAR (10)      NULL,
    [putAwayTemplateCode]         NVARCHAR (10)      NULL,
    [physInvtCountingPeriodCode]  NVARCHAR (10)      NULL,
    [lastCountingPeriodUpdate]    DATE               NULL,
    [nextCountingStartDate]       DATE               NULL,
    [nextCountingEndDate]         DATE               NULL,
    [reserve]                     NVARCHAR (30)      NULL,
    [reserveInt]                  INT                NULL,
    [assemblyPolicy]              NVARCHAR (30)      NULL,
    [assemblyPolicyInt]           INT                NULL,
    [replenishmentSystem]         NVARCHAR (30)      NULL,
    [replenishmentSystemInt]      INT                NULL,
    [reorderingPolicy]            NVARCHAR (30)      NULL,
    [reorderingPolicyInt]         INT                NULL,
    [manufacturingPolicy]         NVARCHAR (30)      NULL,
    [manufacturingPolicyInt]      INT                NULL,
    [flushingMethod]              NVARCHAR (30)      NULL,
    [flushingMethodInt]           INT                NULL,
    [orderTrackingPolicy]         NVARCHAR (30)      NULL,
    [orderTrackingPolicyInt]      INT                NULL,
    [routingNo]                   NVARCHAR (20)      NULL,
    [productionBomNo]             NVARCHAR (20)      NULL,
    [overReceiptCode]             NVARCHAR (20)      NULL,
    [reorderPoint]                DECIMAL (38, 20)   NULL,
    [maximumInventory]            DECIMAL (38, 20)   NULL,
    [reorderQuantity]             DECIMAL (38, 20)   NULL,
    [lotSize]                     DECIMAL (38, 20)   NULL,
    [scrapPct]                    DECIMAL (38, 20)   NULL,
    [discreteOrderQuantity]       INT                NULL,
    [minimumOrderQuantity]        DECIMAL (38, 20)   NULL,
    [maximumOrderQuantity]        DECIMAL (38, 20)   NULL,
    [safetyStockQuantity]         DECIMAL (38, 20)   NULL,
    [orderMultiple]               DECIMAL (38, 20)   NULL,
    [safetyLeadTime]              NVARCHAR (30)      NULL,
    [timeBucket]                  NVARCHAR (30)      NULL,
    [roundingPrecision]           DECIMAL (38, 20)   NULL,
    [includeInventory]            BIT                NULL,
    [reschedulingPeriod]          NVARCHAR (30)      NULL,
    [lotAccumulationPeriod]       NVARCHAR (30)      NULL,
    [dampenerPeriod]              NVARCHAR (30)      NULL,
    [dampenerQuantity]            DECIMAL (38, 20)   NULL,
    [overflowLevel]               DECIMAL (38, 20)   NULL,
    [lowLevelCode]                INT                NULL,
    [lastUnitCostCalcDate]        DATE               NULL,
    [rolledUpMaterialCost]        DECIMAL (38, 20)   NULL,
    [rolledUpCapacityCost]        DECIMAL (38, 20)   NULL,
    [singleLevelMaterialCost]     DECIMAL (38, 20)   NULL,
    [singleLevelCapacityCost]     DECIMAL (38, 20)   NULL,
    [singleLevelSubcontrdCost]    DECIMAL (38, 20)   NULL,
    [singleLevelCapOvhdCost]      DECIMAL (38, 20)   NULL,
    [singleLevelMfgOvhdCost]      DECIMAL (38, 20)   NULL,
    [rolledUpSubcontractedCost]   DECIMAL (38, 20)   NULL,
    [rolledUpMfgOvhdCost]         DECIMAL (38, 20)   NULL,
    [rolledUpCapOverheadCost]     DECIMAL (38, 20)   NULL,
    [itemTrackingCode]            NVARCHAR (10)      NULL,
    [serialNos]                   NVARCHAR (20)      NULL,
    [lotNos]                      NVARCHAR (20)      NULL,
    [expirationCalculation]       NVARCHAR (30)      NULL,
    [lastDateTimeModified]        DATETIME2 (7)      NULL,
    [lastDateModified]            DATE               NULL,
    [lastTimeModified]            TIME (7)           NULL,
    [assemblyBom]                 BIT                NULL,
    [inventory]                   DECIMAL (38, 20)   NULL,
    [netInvoicedQty]              DECIMAL (38, 20)   NULL,
    [netChange]                   DECIMAL (38, 20)   NULL,
    [purchasesQty]                DECIMAL (38, 20)   NULL,
    [salesQty]                    DECIMAL (38, 20)   NULL,
    [positiveAdjmtQty]            DECIMAL (38, 20)   NULL,
    [negativeAdjmtQty]            DECIMAL (38, 20)   NULL,
    [purchasesLCY]                DECIMAL (38, 20)   NULL,
    [salesLCY]                    DECIMAL (38, 20)   NULL,
    [positiveAdjmtLCY]            DECIMAL (38, 20)   NULL,
    [negativeAdjmtLCY]            DECIMAL (38, 20)   NULL,
    [cogsLCY]                     DECIMAL (38, 20)   NULL,
    [qtyOnPurchOrder]             DECIMAL (38, 20)   NULL,
    [qtyOnSalesOrder]             DECIMAL (38, 20)   NULL,
    [transferredQty]              DECIMAL (38, 20)   NULL,
    [transferredLCY]              DECIMAL (38, 20)   NULL,
    [comment]                     BIT                NULL,
    [reservedQtyOnInventory]      DECIMAL (38, 20)   NULL,
    [reservedQtyOnPurchOrders]    DECIMAL (38, 20)   NULL,
    [reservedQtyOnSalesOrders]    DECIMAL (38, 20)   NULL,
    [resQtyOnOutboundTransfer]    DECIMAL (38, 20)   NULL,
    [resQtyOnInboundTransfer]     DECIMAL (38, 20)   NULL,
    [resQtyOnSalesReturns]        DECIMAL (38, 20)   NULL,
    [resQtyOnPurchReturns]        DECIMAL (38, 20)   NULL,
    [costOfOpenProductionOrders]  DECIMAL (38, 20)   NULL,
    [resQtyOnAssemblyOrder]       DECIMAL (38, 20)   NULL,
    [resQtyOnAsmComp]             DECIMAL (38, 20)   NULL,
    [qtyOnAssemblyOrder]          DECIMAL (38, 20)   NULL,
    [qtyOnAsmComponent]           DECIMAL (38, 20)   NULL,
    [qtyOnJobOrder]               DECIMAL (38, 20)   NULL,
    [resQtyOnJobOrder]            DECIMAL (38, 20)   NULL,
    [scheduledReceiptQty]         DECIMAL (38, 20)   NULL,
    [reservedQtyOnProdOrder]      DECIMAL (38, 20)   NULL,
    [resQtyOnProdOrderComp]       DECIMAL (38, 20)   NULL,
    [resQtyOnReqLine]             DECIMAL (38, 20)   NULL,
    [planningTransferShipQty]     DECIMAL (38, 20)   NULL,
    [planningWorksheetQty]        DECIMAL (38, 20)   NULL,
    [stockkeepingUnitExists]      BIT                NULL,
    [substitutesExist]            BIT                NULL,
    [qtyInTransit]                DECIMAL (38, 20)   NULL,
    [transOrdReceiptQty]          DECIMAL (38, 20)   NULL,
    [transOrdShipmentQty]         DECIMAL (38, 20)   NULL,
    [qtyAssignedToShip]           DECIMAL (38, 20)   NULL,
    [qtyPicked]                   DECIMAL (38, 20)   NULL,
    [qtyOnServiceOrder]           DECIMAL (38, 20)   NULL,
    [resQtyOnServiceOrders]       DECIMAL (38, 20)   NULL,
    [qtyOnPurchReturn]            DECIMAL (38, 20)   NULL,
    [qtyOnSalesReturn]            DECIMAL (38, 20)   NULL,
    [noOfSubstitutes]             INT                NULL,
    [lastPhysInvtDate]            DATE               NULL,
    [prodForecastQuantityBase]    DECIMAL (38, 20)   NULL,
    [qtyOnProdOrder]              DECIMAL (38, 20)   NULL,
    [qtyOnComponentLines]         DECIMAL (38, 20)   NULL,
    [planningIssuesQty]           DECIMAL (38, 20)   NULL,
    [planningReceiptQty]          DECIMAL (38, 20)   NULL,
    [plannedOrderReceiptQty]      DECIMAL (38, 20)   NULL,
    [fpOrderReceiptQty]           DECIMAL (38, 20)   NULL,
    [relOrderReceiptQty]          DECIMAL (38, 20)   NULL,
    [planningReleaseQty]          DECIMAL (38, 20)   NULL,
    [plannedOrderReleaseQty]      DECIMAL (38, 20)   NULL,
    [purchReqReceiptQty]          DECIMAL (38, 20)   NULL,
    [purchReqReleaseQty]          DECIMAL (38, 20)   NULL,
    [itemBrand]                   NVARCHAR (50)      NULL,
    [productLineCode]             NVARCHAR (50)      NULL,
    [productUsage]                NVARCHAR (50)      NULL,
    [productGroupCode]            NVARCHAR (50)      NULL,
    [itemSize]                    NVARCHAR (50)      NULL,
    [itemSizeUnit]                NVARCHAR (10)      NULL,
    [itemFeature]                 NVARCHAR (50)      NULL,
    [packingMethod]               NVARCHAR (50)      NULL,
    [abcdCategory]                NVARCHAR (20)      NULL,
    [coating]                     NVARCHAR (50)      NULL,
    [quality]                     NVARCHAR (30)      NULL,
    [qualityInt]                  INT                NULL,
    [withLid]                     BIT                NULL,
    [weightClassification]        INT                NULL,
    [calculatedAvailable]         DECIMAL (38, 20)   NULL,
    [calculatedAvailableExternal] DECIMAL (38, 20)   NULL,
    [calculatedAvailableDate]     DATE               NULL,
    [itemBodyType]                NVARCHAR (30)      NULL,
    [itemBodyTypeInt]             INT                NULL,
    [systemCreatedAt]             DATETIME2 (7)      NULL,
    [systemCreatedBy]             UNIQUEIDENTIFIER   NULL,
    [systemModifiedAt]            DATETIME2 (7)      NULL,
    [systemModifiedBy]            UNIQUEIDENTIFIER   NULL,
    [PipelineName]                NVARCHAR (200)     NULL,
    [PipelineRunId]               UNIQUEIDENTIFIER   NULL,
    [PipelineTriggerTime]         DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED ([CompanyId] ASC, [number] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_Item_CompanyId_vendorNo]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [vendorNo] ASC)
    INCLUDE([number], [description]) WHERE ([vendorNo] IS NOT NULL);


GO

CREATE NONCLUSTERED INDEX [IX_Item_CompanyId_systemId]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [systemId] ASC) WHERE ([systemId] IS NOT NULL);


GO

CREATE NONCLUSTERED INDEX [IX_Item_CompanyId_itemCategoryCode]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [itemCategoryCode] ASC)
    INCLUDE([number], [description], [type], [typeInt]) WHERE ([itemCategoryCode] IS NOT NULL);


GO

CREATE NONCLUSTERED INDEX [IX_Item_CompanyId_gtin]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [gtin] ASC)
    INCLUDE([number], [description]) WHERE ([gtin] IS NOT NULL);


GO

CREATE NONCLUSTERED INDEX [IX_Item_CompanyId_genProdPostingGroup]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [genProdPostingGroup] ASC)
    INCLUDE([number], [description]) WHERE ([genProdPostingGroup] IS NOT NULL);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_Item_CompanyId_number]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [number] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_Item_CompanyId_systemModifiedAt]
    ON [stg_bc_api].[Item]([CompanyId] ASC, [systemModifiedAt] ASC)
    INCLUDE([number], [systemId], [description], [type], [typeInt]);


GO

